local CountryPosition = {} 
CountryPosition[1] = {ID = 1, positionGroup = 3, positionType = 1, name = '皇帝', appointPosition = '[2,3,4,5,6]', cancelPosition = '[2,3,4,5,6]', appointWanted = '[1,2,3,4]', cancelWanted = '[1,2,3,4]', wantedLimit = 4, positionBuff = '[30021,30022]', skill = '[1,2,3,4]', appointCD = 0}
CountryPosition[2] = {ID = 2, positionGroup = 3, positionType = 2, name = '将军', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30023,30024]', skill = '[1]', appointCD = 3600}
CountryPosition[3] = {ID = 3, positionGroup = 3, positionType = 3, name = '廷尉', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30025,30026]', skill = '[2]', appointCD = 3600}
CountryPosition[4] = {ID = 4, positionGroup = 3, positionType = 4, name = '中尉', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30027,30028]', skill = '[3]', appointCD = 3600}
CountryPosition[5] = {ID = 5, positionGroup = 3, positionType = 5, name = '御史', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30029,30030]', skill = '[4]', appointCD = 3600}
CountryPosition[6] = {ID = 6, positionGroup = 3, positionType = 6, name = '护国侯', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30031,30032]', skill = '[]', appointCD = 3600}
CountryPosition[7] = {ID = 7, positionGroup = 3, positionType = 6, name = '护国侯', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30031,30032]', skill = '[]', appointCD = 3600}
CountryPosition[8] = {ID = 8, positionGroup = 3, positionType = 6, name = '护国侯', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30031,30032]', skill = '[]', appointCD = 3600}
CountryPosition[9] = {ID = 9, positionGroup = 3, positionType = 6, name = '护国侯', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30031,30032]', skill = '[]', appointCD = 3600}
CountryPosition[10] = {ID = 10, positionGroup = 2, positionType = 7, name = '文王', appointPosition = '[8]', cancelPosition = '[8]', appointWanted = '[1,2,3,4]', cancelWanted = '[]', wantedLimit = 4, positionBuff = '[30033,30034]', skill = '[1,2,3,4]', appointCD = 0}
CountryPosition[11] = {ID = 11, positionGroup = 2, positionType = 8, name = '文官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30035,30036]', skill = '[]', appointCD = 3600}
CountryPosition[12] = {ID = 12, positionGroup = 2, positionType = 8, name = '文官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30035,30036]', skill = '[]', appointCD = 3600}
CountryPosition[13] = {ID = 13, positionGroup = 2, positionType = 8, name = '文官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30035,30036]', skill = '[]', appointCD = 3600}
CountryPosition[14] = {ID = 14, positionGroup = 2, positionType = 8, name = '文官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30035,30036]', skill = '[]', appointCD = 3600}
CountryPosition[15] = {ID = 15, positionGroup = 1, positionType = 9, name = '武王', appointPosition = '[10]', cancelPosition = '[10]', appointWanted = '[1,2,3,4]', cancelWanted = '[]', wantedLimit = 4, positionBuff = '[30037,30038]', skill = '[1,2,3,4]', appointCD = 0}
CountryPosition[16] = {ID = 16, positionGroup = 1, positionType = 10, name = '武官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30039,30040]', skill = '[]', appointCD = 3600}
CountryPosition[17] = {ID = 17, positionGroup = 1, positionType = 10, name = '武官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30039,30040]', skill = '[]', appointCD = 3600}
CountryPosition[18] = {ID = 18, positionGroup = 1, positionType = 10, name = '武官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30039,30040]', skill = '[]', appointCD = 3600}
CountryPosition[19] = {ID = 19, positionGroup = 1, positionType = 10, name = '武官', appointPosition = '[]', cancelPosition = '[]', appointWanted = '[]', cancelWanted = '[]', wantedLimit = 0, positionBuff = '[30039,30040]', skill = '[]', appointCD = 3600}
return CountryPosition