local Fightvalue = {} 
Fightvalue[1] = {ID = 1, type = 1, name = '统率等级', icon = 10401, info1 = '拥有统率令:', info2 = '拥有统率令:', info3 = '拥有统率令:', itempower = '[401,4013]', clickinfo = '当统率等级等于主公等级\n此项可达100%', linktype = 'PersonInfoModule', reaches = 'PersonInfoDetailsPanel', lvneed = 4, sort = 1}
Fightvalue[2] = {ID = 2, type = 2, name = '战法等级', icon = 10402, info1 = '拥有战法秘籍:', info2 = '拥有战法秘籍:', info3 = '拥有战法秘籍:', itempower = '[401,4012]', clickinfo = '当所有战法等级等于主公等级\n此项可达100%', linktype = 'PersonInfoModule', reaches = 'PersonInfoSkillPanel', lvneed = 6, sort = 2}
Fightvalue[3] = {ID = 3, type = 5, name = '军械品质', icon = 10405, info1 = '军械坊中的军械:', info2 = '军械坊中的军械:', info3 = '军械坊中的军械:', itempower = '[]', clickinfo = '当所有兵种装配的配件全部为最高等级\n此项可达100%', linktype = 'RegionModule', reaches = 'RegionPanel', lvneed = 25, sort = 5}
Fightvalue[4] = {ID = 4, type = 6, name = '军械强化', icon = 10406, info1 = '军械可强化', info2 = '军械可强化', info3 = '军械强化已满级', itempower = '[]', clickinfo = '当所有兵种配件等级等于主公等级\n此项可达100%', linktype = 'PartsModule', reaches = 0, lvneed = 25, sort = 6}
Fightvalue[5] = {ID = 5, type = 7, name = '军械改造', icon = 10407, info1 = '军械可改造', info2 = '军械可改造', info3 = '军械改造已满级', itempower = '[]', clickinfo = '当所有兵种配件改造等级等于10级\n此项可达100%', linktype = 'PartsModule', reaches = 0, lvneed = 25, sort = 7}
Fightvalue[6] = {ID = 6, type = 8, name = '科研等级', icon = 10408, info1 = '太学院等级过低,马上前往升级', info2 = '有可升级战斗科技', info3 = '战斗科技已满级', itempower = '[]', clickinfo = '当8项战斗科技（攻击和生命）等级等于主公等级\n此项可达100%', linktype = 'ScienceMuseumModule', reaches = 'ScienceResearchPanel', lvneed = 1, sort = 8}
Fightvalue[7] = {ID = 7, type = 9, name = '主力部队', icon = 10409, info1 = '提升兵营等级,开启更高级兵种生产', info2 = '最强制造兵种:%s,还差%d个', info3 = '提升兵营等级,开启更高级兵种生产', itempower = '[]', clickinfo = '当一支部队每个部队位为最强兵种最大带兵数\n此项可达100%', linktype = 'BarrackModule', reaches = 'BarrackRecruitPanel', lvneed = 1, sort = 9}
Fightvalue[8] = {ID = 8, type = 10, name = '部队满编', icon = 10410, info1 = '还差%d个满编', info2 = '还差%d个满编', info3 = '兵贵多，继续生产和改装吧！', itempower = '[]', clickinfo = '可出战多支部队全部满编\n此项可达100%', linktype = 'BarrackModule', reaches = 'BarrackRecruitPanel', lvneed = 1, sort = 10}
Fightvalue[9] = {ID = 9, type = 11, name = '繁荣战力', icon = 10411, info1 = '可提升建筑等级增加繁荣度', info2 = '可提升建筑等级增加繁荣度', info3 = '繁荣度战力加成已达最高', itempower = '[]', clickinfo = '当前繁荣度达到10级\n此项可达100%', linktype = 'PersonInfoModule', reaches = 'PersonInfoBuildPanel', lvneed = 1, sort = 11}
return Fightvalue