local JuniorQu = {} 
JuniorQu[1] = {ID = 1, examType = 1, question = '一天可免费领取军令的总数是', trueAnswerId = 1, trueAnswer = 30, falseAnswer1 = 10, falseAnswer2 = 20}
JuniorQu[2] = {ID = 2, examType = 1, question = '军令多长时候恢复一点', trueAnswerId = 1, trueAnswer = '30分钟', falseAnswer1 = '20分钟', falseAnswer2 = '15分钟'}
JuniorQu[3] = {ID = 3, examType = 1, question = '重置西域远征需要消耗的是', trueAnswerId = 1, trueAnswer = '军令', falseAnswer1 = '讨伐令', falseAnswer2 = '元宝'}
JuniorQu[4] = {ID = 4, examType = 1, question = '重置西域远征消耗的军令数量是', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 0}
JuniorQu[5] = {ID = 5, examType = 1, question = '西域远征初始单关的挑战次数是', trueAnswerId = 1, trueAnswer = 3, falseAnswer1 = 1, falseAnswer2 = 5}
JuniorQu[6] = {ID = 6, examType = 1, question = '声望等级影响', trueAnswerId = 1, trueAnswer = '科技等级', falseAnswer1 = '战法等级', falseAnswer2 = '统率等级'}
JuniorQu[7] = {ID = 7, examType = 1, question = '统率等级影响', trueAnswerId = 1, trueAnswer = '带兵量', falseAnswer1 = '先手值', falseAnswer2 = '科技等级'}
JuniorQu[8] = {ID = 8, examType = 1, question = '铸币所建筑可建造多少个', trueAnswerId = 1, trueAnswer = 1, falseAnswer1 = 3, falseAnswer2 = 5}
JuniorQu[9] = {ID = 9, examType = 1, question = '校场建筑的作用是', trueAnswerId = 1, trueAnswer = '升级兵种', falseAnswer1 = '升级武将', falseAnswer2 = '升级军械'}
JuniorQu[10] = {ID = 10, examType = 1, question = '战法等级不能超过', trueAnswerId = 1, trueAnswer = '主公等级', falseAnswer1 = '官邸等级', falseAnswer2 = '声望等级'}
JuniorQu[11] = {ID = 11, examType = 1, question = '重置一次战法等级需要消耗多少元宝', trueAnswerId = 1, trueAnswer = 58, falseAnswer1 = 48, falseAnswer2 = 68}
JuniorQu[12] = {ID = 12, examType = 1, question = '主城最多拥有多少个仓库建筑', trueAnswerId = 1, trueAnswer = 2, falseAnswer1 = 1, falseAnswer2 = 3}
JuniorQu[13] = {ID = 13, examType = 1, question = 'vip0玩家升级建筑的免费建造时间是', trueAnswerId = 1, trueAnswer = '5分钟', falseAnswer1 = '4分钟', falseAnswer2 = '3分钟'}
JuniorQu[14] = {ID = 14, examType = 1, question = 'vip0玩家每日可购买军令次数为', trueAnswerId = 1, trueAnswer = '1次', falseAnswer1 = '0次', falseAnswer2 = '2次'}
JuniorQu[15] = {ID = 15, examType = 1, question = '哪类品质的军师不能任命内政', trueAnswerId = 1, trueAnswer = '橙色军师', falseAnswer1 = '紫色军师', falseAnswer2 = '白色军师'}
JuniorQu[16] = {ID = 16, examType = 1, question = '每日中午免费领取军令的时候从12:00到', trueAnswerId = 1, trueAnswer = '14点', falseAnswer1 = '13点', falseAnswer2 = '13点30分'}
JuniorQu[17] = {ID = 17, examType = 1, question = '每日晚上免费领取军令的时候从18:00到', trueAnswerId = 1, trueAnswer = '20点', falseAnswer1 = '19点', falseAnswer2 = '19点30分'}
JuniorQu[18] = {ID = 18, examType = 1, question = '单次免费领取军令的个数是', trueAnswerId = 1, trueAnswer = 10, falseAnswer1 = 5, falseAnswer2 = 20}
JuniorQu[19] = {ID = 19, examType = 1, question = '西域远征每日可重置的次数是', trueAnswerId = 1, trueAnswer = 1, falseAnswer1 = 2, falseAnswer2 = 3}
JuniorQu[20] = {ID = 20, examType = 1, question = '匈奴远征不会产出', trueAnswerId = 1, trueAnswer = '军械', falseAnswer1 = '兵法册', falseAnswer2 = '经验书'}
JuniorQu[21] = {ID = 21, examType = 1, question = '匈奴远征每日免费挑战次数', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 0}
JuniorQu[22] = {ID = 22, examType = 1, question = '鲜卑远征不会产出', trueAnswerId = 1, trueAnswer = '突破丹', falseAnswer1 = '改造金属', falseAnswer2 = '改造精华'}
JuniorQu[23] = {ID = 23, examType = 1, question = '鲜卑远征每日免费挑战次数', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 0}
JuniorQu[24] = {ID = 24, examType = 1, question = '中原战役副本挑战损失兵种百分比', trueAnswerId = 1, trueAnswer = '百分之0', falseAnswer1 = '百分之1', falseAnswer2 = '百分之2'}
JuniorQu[25] = {ID = 25, examType = 1, question = '祝福好友获得经验值只限前几次祝福', trueAnswerId = 1, trueAnswer = 10, falseAnswer1 = 15, falseAnswer2 = 20}
JuniorQu[26] = {ID = 26, examType = 1, question = '目前添加好友的数量上限是', trueAnswerId = 1, trueAnswer = 20, falseAnswer1 = 15, falseAnswer2 = 30}
JuniorQu[27] = {ID = 27, examType = 1, question = '每日可领取好友祝福获得军令的上限是', trueAnswerId = 1, trueAnswer = 10, falseAnswer1 = 15, falseAnswer2 = 20}
JuniorQu[28] = {ID = 28, examType = 1, question = '军械单个兵种类型可穿戴的军械个数是', trueAnswerId = 1, trueAnswer = 8, falseAnswer1 = 6, falseAnswer2 = 7}
JuniorQu[29] = {ID = 29, examType = 1, question = '军械碎片不足时可通过什么合成', trueAnswerId = 1, trueAnswer = '万年寒铁', falseAnswer1 = '千年寒铁', falseAnswer2 = '百年寒铁'}
JuniorQu[30] = {ID = 30, examType = 1, question = '军械提升包括强化、改造和', trueAnswerId = 1, trueAnswer = '进阶', falseAnswer1 = '锻造', falseAnswer2 = '吞噬'}
JuniorQu[31] = {ID = 31, examType = 1, question = '什么品质的军械可进行进阶', trueAnswerId = 1, trueAnswer = '紫色', falseAnswer1 = '蓝色', falseAnswer2 = '绿色'}
JuniorQu[32] = {ID = 32, examType = 1, question = '军械强化消耗', trueAnswerId = 1, trueAnswer = '银币', falseAnswer1 = '元宝', falseAnswer2 = '木材'}
JuniorQu[33] = {ID = 33, examType = 1, question = '军械改造会降低当前军械多少强化等级', trueAnswerId = 1, trueAnswer = 3, falseAnswer1 = 5, falseAnswer2 = 1}
JuniorQu[34] = {ID = 34, examType = 1, question = '发送聊天信息的间隔时间是', trueAnswerId = 1, trueAnswer = '5秒', falseAnswer1 = '10秒', falseAnswer2 = '1秒'}
JuniorQu[35] = {ID = 35, examType = 1, question = '武将可上阵', trueAnswerId = 1, trueAnswer = '6个', falseAnswer1 = '5个', falseAnswer2 = '8个'}
JuniorQu[36] = {ID = 36, examType = 1, question = '演武场每日免费挑战次数', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 8}
JuniorQu[37] = {ID = 37, examType = 1, question = '演武场挑战失败后的冷却时间为', trueAnswerId = 1, trueAnswer = '10分钟', falseAnswer1 = '5分钟', falseAnswer2 = '15分钟'}
JuniorQu[38] = {ID = 38, examType = 1, question = '先手值一样时，演武场谁先手', trueAnswerId = 1, trueAnswer = '攻方', falseAnswer1 = '守方', falseAnswer2 = '双方随机'}
JuniorQu[39] = {ID = 39, examType = 1, question = '同盟作战所每日免费挑战次数为', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 15}
JuniorQu[40] = {ID = 40, examType = 2, question = '“古今多少事，都付笑谈中”与哪句相呼应?', trueAnswerId = 1, trueAnswer = '青山依旧在，几度夕阳红', falseAnswer1 = '社稷今将建，江山忽已移', falseAnswer2 = '上下五千年，弹指一挥间'}
JuniorQu[41] = {ID = 41, examType = 2, question = '汉灵帝即位后，宦官谁弄权?', trueAnswerId = 1, trueAnswer = '曹节', falseAnswer1 = '张让', falseAnswer2 = '赵忠'}
JuniorQu[42] = {ID = 42, examType = 2, question = '刘焉发榜招军时，刘备多少岁?', trueAnswerId = 1, trueAnswer = '二十八岁', falseAnswer1 = '十八岁', falseAnswer2 = '三十六岁'}
JuniorQu[43] = {ID = 43, examType = 2, question = '《太平要术》是南华老仙送给谁的三卷天书?', trueAnswerId = 1, trueAnswer = '张角', falseAnswer1 = '张宝', falseAnswer2 = '张梁'}
JuniorQu[44] = {ID = 44, examType = 2, question = '刘备几岁时，其母就让他云游学习了?', trueAnswerId = 1, trueAnswer = '十五', falseAnswer1 = '十四', falseAnswer2 = '十六'}
JuniorQu[45] = {ID = 45, examType = 2, question = '“地公将军”是指谁?', trueAnswerId = 1, trueAnswer = '张宝', falseAnswer1 = '张角', falseAnswer2 = '张梁'}
JuniorQu[46] = {ID = 46, examType = 2, question = '关羽的籍贯是今什么省?', trueAnswerId = 1, trueAnswer = '山西', falseAnswer1 = '河北', falseAnswer2 = '河南'}
JuniorQu[47] = {ID = 47, examType = 2, question = '家住楼桑村的是谁?', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '刘焉', falseAnswer2 = '关羽'}
JuniorQu[48] = {ID = 48, examType = 2, question = '关羽的美髯有多长?', trueAnswerId = 1, trueAnswer = '二尺', falseAnswer1 = '一尺', falseAnswer2 = '一尺八寸'}
JuniorQu[49] = {ID = 49, examType = 2, question = '桃园三结义的时候，除了用马做祭祀物品外，还用了什么牛做祭祀品?', trueAnswerId = 1, trueAnswer = '黑牛', falseAnswer1 = '水牛', falseAnswer2 = '黄牛'}
JuniorQu[50] = {ID = 50, examType = 2, question = '以下谁为丹凤眼?', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '吕布', falseAnswer2 = '马超'}
JuniorQu[51] = {ID = 51, examType = 2, question = '桃园三结义时，在桃园中痛饮有多少人?', trueAnswerId = 1, trueAnswer = '三百余人', falseAnswer1 = '一百余人', falseAnswer2 = '五百余人'}
JuniorQu[52] = {ID = 52, examType = 2, question = '苏双、张世平两人是从事什么职业的?', trueAnswerId = 1, trueAnswer = '贩马', falseAnswer1 = '卖酒', falseAnswer2 = '打铁匠'}
JuniorQu[53] = {ID = 53, examType = 2, question = '“冷艳锯”是谁的兵器?', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '刘备', falseAnswer2 = '黄忠'}
JuniorQu[54] = {ID = 54, examType = 2, question = '“吉利”是谁的小名?', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '刘备', falseAnswer2 = '孙策'}
JuniorQu[55] = {ID = 55, examType = 2, question = '张宝被刘备射中何部位?', trueAnswerId = 1, trueAnswer = '左臂', falseAnswer1 = '左背', falseAnswer2 = '左肩'}
JuniorQu[56] = {ID = 56, examType = 2, question = '刘关张出道后杀死的第一个副将是谁?', trueAnswerId = 1, trueAnswer = '邓茂', falseAnswer1 = '程远志', falseAnswer2 = '孙仲'}
JuniorQu[57] = {ID = 57, examType = 2, question = '直言曹操是“治世之能臣，乱世之奸雄”的是谁?', trueAnswerId = 1, trueAnswer = '许劭', falseAnswer1 = '曹嵩', falseAnswer2 = '桥玄'}
JuniorQu[58] = {ID = 58, examType = 2, question = '最早预言曹操“将来能安天下”的是谁?', trueAnswerId = 1, trueAnswer = '何颙', falseAnswer1 = '曹操叔父', falseAnswer2 = '曹嵩'}
JuniorQu[59] = {ID = 59, examType = 2, question = '“人情势利古犹今，谁识英雄是白身”这句话指的是谁?', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '曹操', falseAnswer2 = '孙坚'}
JuniorQu[60] = {ID = 60, examType = 2, question = '以下何人作法大败刘备?', trueAnswerId = 1, trueAnswer = '张宝', falseAnswer1 = '张角', falseAnswer2 = '张梁'}
JuniorQu[61] = {ID = 61, examType = 2, question = '张梁是被何部所杀的?', trueAnswerId = 1, trueAnswer = '皇甫嵩', falseAnswer1 = '曹操', falseAnswer2 = '卢植'}
JuniorQu[62] = {ID = 62, examType = 2, question = '张宝的首级被严政献给了何部?', trueAnswerId = 1, trueAnswer = '朱隽', falseAnswer1 = '曹操', falseAnswer2 = '卢植'}
JuniorQu[63] = {ID = 63, examType = 2, question = '以下何人不是黄巾军余党?', trueAnswerId = 1, trueAnswer = '许韶', falseAnswer1 = '赵弘', falseAnswer2 = '韩忠'}
JuniorQu[64] = {ID = 64, examType = 2, question = '孙坚当上校尉时几岁?', trueAnswerId = 1, trueAnswer = '十七', falseAnswer1 = '十八', falseAnswer2 = '十九'}
JuniorQu[65] = {ID = 65, examType = 2, question = '刘备的“来喜县尉”官职是靠谁力陈利害而得来的?', trueAnswerId = 1, trueAnswer = '张钧', falseAnswer1 = '朱隽', falseAnswer2 = '皇甫嵩'}
JuniorQu[66] = {ID = 66, examType = 2, question = '张飞鞭打督邮用的是什么工具?', trueAnswerId = 1, trueAnswer = '柳条', falseAnswer1 = '马鞭', falseAnswer2 = '藤条'}
JuniorQu[67] = {ID = 67, examType = 2, question = '刘备听从了关羽的劝说，将印绶放在何处，宣告辞职?', trueAnswerId = 1, trueAnswer = '挂在督邮脖子上', falseAnswer1 = '挂在树上', falseAnswer2 = '放在案上'}
JuniorQu[68] = {ID = 68, examType = 2, question = '以下何人是自缢而死的?', trueAnswerId = 1, trueAnswer = '张举', falseAnswer1 = '刘陶', falseAnswer2 = '陈耽'}
JuniorQu[69] = {ID = 69, examType = 2, question = '何进以妹为贵，得以重权，其原来是何出身?', trueAnswerId = 1, trueAnswer = '屠夫', falseAnswer1 = '铁匠', falseAnswer2 = '贩马'}
JuniorQu[70] = {ID = 70, examType = 2, question = '何后因嫉妒谁，用毒酒杀了她?', trueAnswerId = 1, trueAnswer = '王美人', falseAnswer1 = '周美人', falseAnswer2 = '吴美人'}
JuniorQu[71] = {ID = 71, examType = 2, question = '汉灵帝之母是谁?', trueAnswerId = 1, trueAnswer = '董太后', falseAnswer1 = '何皇后', falseAnswer2 = '王美人'}
JuniorQu[72] = {ID = 72, examType = 2, question = '袁绍之父袁逢居何职?', trueAnswerId = 1, trueAnswer = '司徒', falseAnswer1 = '司隶', falseAnswer2 = '司马'}
JuniorQu[73] = {ID = 73, examType = 2, question = '谁进言何进应该先立君位?', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '司马潘', falseAnswer2 = '袁绍'}
JuniorQu[74] = {ID = 74, examType = 2, question = '董后被何进派人毒死时几月?', trueAnswerId = 1, trueAnswer = '六', falseAnswer1 = '三', falseAnswer2 = '九'}
JuniorQu[75] = {ID = 75, examType = 2, question = '“乱天下者，必何进也”是谁的断言?', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '刘备', falseAnswer2 = '董卓'}
JuniorQu[76] = {ID = 76, examType = 2, question = '以下谁破黄巾军无功，差点被治罪?', trueAnswerId = 1, trueAnswer = '董卓', falseAnswer1 = '朱隽', falseAnswer2 = '孙坚'}
JuniorQu[77] = {ID = 77, examType = 2, question = '以下除谁外，余者均劝何进不要进宫?', trueAnswerId = 1, trueAnswer = '袁术', falseAnswer1 = '曹操', falseAnswer2 = '袁绍'}
JuniorQu[78] = {ID = 78, examType = 2, question = '何进的首级被张让等人如何处理的?', trueAnswerId = 1, trueAnswer = '扔出墙外', falseAnswer1 = '就地掩埋', falseAnswer2 = '悬挂午门'}
JuniorQu[79] = {ID = 79, examType = 2, question = '张让是如何而死的?', trueAnswerId = 1, trueAnswer = '投河', falseAnswer1 = '被曹操部所杀', falseAnswer2 = '自缢'}
JuniorQu[80] = {ID = 80, examType = 2, question = '“帝非帝，王非王，千乘万骑走北邙”是何处的童谣?', trueAnswerId = 1, trueAnswer = '洛阳', falseAnswer1 = '开封', falseAnswer2 = '西凉'}
JuniorQu[81] = {ID = 81, examType = 2, question = '第一个出来反对董卓废帝的是谁?', trueAnswerId = 1, trueAnswer = '丁原', falseAnswer1 = '王允', falseAnswer2 = '鲍信'}
JuniorQu[82] = {ID = 82, examType = 2, question = '“有伊尹之志则可，无伊尹之志则篡”是谁对董卓说的话?', trueAnswerId = 1, trueAnswer = '卢植', falseAnswer1 = '李儒', falseAnswer2 = '丁原'}
JuniorQu[83] = {ID = 83, examType = 2, question = '赤兔马从蹿至项高多少?', trueAnswerId = 1, trueAnswer = '八尺', falseAnswer1 = '七尺', falseAnswer2 = '九尺'}
JuniorQu[84] = {ID = 84, examType = 2, question = '吕布吃里扒外，接受了礼品后在什么时分将其义父丁原杀了?', trueAnswerId = 1, trueAnswer = '二更', falseAnswer1 = '三更', falseAnswer2 = '四更'}
JuniorQu[85] = {ID = 85, examType = 2, question = '董卓听了谁的劝说，拜了与他刚闹翻的袁绍为渤海太守?', trueAnswerId = 1, trueAnswer = '伍琼', falseAnswer1 = '李儒', falseAnswer2 = '李肃'}
JuniorQu[86] = {ID = 86, examType = 2, question = '孝灵帝从登基至被废只有多长时间?', trueAnswerId = 1, trueAnswer = '五月', falseAnswer1 = '六月', falseAnswer2 = '八月'}
JuniorQu[87] = {ID = 87, examType = 2, question = '汉献帝登基时几岁?', trueAnswerId = 1, trueAnswer = '九', falseAnswer1 = '六', falseAnswer2 = '七'}
JuniorQu[88] = {ID = 88, examType = 2, question = '“为臣逼兮命不久，大势去兮空泪潸”这首歌词是何人所作?', trueAnswerId = 1, trueAnswer = '少帝', falseAnswer1 = '唐妃', falseAnswer2 = '何太后'}
JuniorQu[89] = {ID = 89, examType = 2, question = '“朝堂杀贼名犹在，万古堪称大丈夫”此诗是赞谁的?', trueAnswerId = 1, trueAnswer = '伍孚', falseAnswer1 = '丁原', falseAnswer2 = '王允'}
JuniorQu[90] = {ID = 90, examType = 2, question = '见众官皆哭，谁说道“满朝公卿，夜哭到明，明哭到夜，还能哭死董卓否”?', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '王允', falseAnswer2 = '袁绍'}
JuniorQu[91] = {ID = 91, examType = 2, question = '曹操行刺董卓不成，逃出城外，被陈宫手下所获，起初谎称自己姓什么?', trueAnswerId = 1, trueAnswer = '皇甫', falseAnswer1 = '夏侯', falseAnswer2 = '端木'}
JuniorQu[92] = {ID = 92, examType = 2, question = '“七星宝刀”是谁献给董卓的?', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '王允', falseAnswer2 = '陈宫'}
JuniorQu[93] = {ID = 93, examType = 2, question = '“宁教我负天下人，休教天下人负我”曹操的这句“名言”是对谁说的?', trueAnswerId = 1, trueAnswer = '陈宫', falseAnswer1 = '董卓', falseAnswer2 = '吕伯奢'}
JuniorQu[94] = {ID = 94, examType = 2, question = '曹操因猜疑心重，杀了吕伯奢一家共多少人?', trueAnswerId = 1, trueAnswer = '九', falseAnswer1 = '三', falseAnswer2 = '六'}
JuniorQu[95] = {ID = 95, examType = 2, question = '曹操发檄文后，各镇诸侯皆起兵相应的有几路兵马?', trueAnswerId = 1, trueAnswer = '十七', falseAnswer1 = '十五', falseAnswer2 = '十九'}
JuniorQu[96] = {ID = 96, examType = 2, question = '曹操竖旗发矫诏后，至发檄文前，以下除谁外均来投奔操?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '乐进', falseAnswer2 = '李典'}
JuniorQu[97] = {ID = 97, examType = 2, question = '曹操发矫诏后，谁最早来与操结盟的?', trueAnswerId = 1, trueAnswer = '袁绍', falseAnswer1 = '公孙瓒', falseAnswer2 = '马腾'}
JuniorQu[98] = {ID = 98, examType = 2, question = '以下谁十四岁时因别人辱骂其师父而把那人给杀了?', trueAnswerId = 1, trueAnswer = '夏侯惇', falseAnswer1 = '曹仁', falseAnswer2 = '曹洪'}
JuniorQu[99] = {ID = 99, examType = 2, question = '各镇诸侯皆起兵讨伐董卓，谁是第一镇的头领?', trueAnswerId = 1, trueAnswer = '袁术', falseAnswer1 = '袁绍', falseAnswer2 = '公孙瓒'}
JuniorQu[100] = {ID = 100, examType = 2, question = '袁绍被众人推选为讨伐军盟主，谁请缨当先锋?', trueAnswerId = 1, trueAnswer = '孙坚', falseAnswer1 = '刘备', falseAnswer2 = '曹操'}
JuniorQu[101] = {ID = 101, examType = 2, question = '以下谁急于抢功抄小路作先锋反被华雄斩于马下?', trueAnswerId = 1, trueAnswer = '鲍忠', falseAnswer1 = '鲍信', falseAnswer2 = '张杨'}
JuniorQu[102] = {ID = 102, examType = 2, question = '以下孙坚手下四将，何人是使双刀的?', trueAnswerId = 1, trueAnswer = '祖茂', falseAnswer1 = '程普', falseAnswer2 = '黄盖'}
JuniorQu[103] = {ID = 103, examType = 2, question = '华雄躲过了孙坚射来的几支箭?', trueAnswerId = 1, trueAnswer = '二', falseAnswer1 = '一', falseAnswer2 = '三'}
JuniorQu[104] = {ID = 104, examType = 2, question = '孙坚为华雄所追，谁与孙坚换了头盔使孙得以逃脱?', trueAnswerId = 1, trueAnswer = '祖茂', falseAnswer1 = '程普', falseAnswer2 = '黄盖'}
JuniorQu[105] = {ID = 105, examType = 2, question = '孙坚部不敌华雄部最关键的原因是什么?', trueAnswerId = 1, trueAnswer = '孙坚缺粮军心不稳', falseAnswer1 = '孙坚战略战术有问题', falseAnswer2 = '华雄部进行了夜间偷袭'}
JuniorQu[106] = {ID = 106, examType = 2, question = '孙坚大败于华雄后，袁绍无计可施时，以下除谁外，当场发作在冷笑?', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '刘备', falseAnswer2 = '关羽'}
JuniorQu[107] = {ID = 107, examType = 2, question = '孙坚的头巾被华雄部所获用长竿挑出进行羞辱，孙坚的头巾是什么颜色的?', trueAnswerId = 1, trueAnswer = '红色', falseAnswer1 = '白色', falseAnswer2 = '绿色'}
JuniorQu[108] = {ID = 108, examType = 2, question = '以下何人不是守虎牢关的?', trueAnswerId = 1, trueAnswer = '李傕', falseAnswer1 = '吕布', falseAnswer2 = '樊稠'}
JuniorQu[109] = {ID = 109, examType = 2, question = '袁绍命公孙瓒等几路诸侯去往虎牢关迎敌?', trueAnswerId = 1, trueAnswer = '八', falseAnswer1 = '四', falseAnswer2 = '六'}
JuniorQu[110] = {ID = 110, examType = 2, question = '哪路诸侯最先到达虎牢关与吕布交锋?', trueAnswerId = 1, trueAnswer = '王匡', falseAnswer1 = '公孙瓒', falseAnswer2 = '陶谦'}
JuniorQu[111] = {ID = 111, examType = 2, question = '以下何人只被吕布砍断手腕，幸运存活?', trueAnswerId = 1, trueAnswer = '武安国', falseAnswer1 = '方悦', falseAnswer2 = '穆顺'}
JuniorQu[112] = {ID = 112, examType = 2, question = '嘲笑吕布是“三姓家奴”的是谁?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '公孙瓒', falseAnswer2 = '刘备'}
JuniorQu[113] = {ID = 113, examType = 2, question = '以下谁来找孙坚告之董卓愿将女儿嫁给孙?', trueAnswerId = 1, trueAnswer = '李儒', falseAnswer1 = '李傕', falseAnswer2 = '杨彪'}
JuniorQu[114] = {ID = 114, examType = 2, question = '以下除谁外，均反对董卓迁都?', trueAnswerId = 1, trueAnswer = '李儒', falseAnswer1 = '伍琼', falseAnswer2 = '周毖'}
JuniorQu[115] = {ID = 115, examType = 2, question = '谁救了被徐荣射中的曹操?', trueAnswerId = 1, trueAnswer = '曹洪', falseAnswer1 = '夏侯惇', falseAnswer2 = '李典'}
JuniorQu[116] = {ID = 116, examType = 2, question = '曹操几乎“三死”指的是除何项外的“三死”?', trueAnswerId = 1, trueAnswer = '华容道死里逃生', falseAnswer1 = '献刀而逃，为军士所获', falseAnswer2 = '陈宫客店欲杀之'}
JuniorQu[117] = {ID = 117, examType = 2, question = '“受命于天，既寿永昌”是传国玉玺上的八字，这是谁篆上去的?', trueAnswerId = 1, trueAnswer = '李斯', falseAnswer1 = '吕不韦', falseAnswer2 = '秦始皇'}
JuniorQu[118] = {ID = 118, examType = 2, question = '孙坚得的传国玉玺方圆多少寸?', trueAnswerId = 1, trueAnswer = '四', falseAnswer1 = '一', falseAnswer2 = '二'}
JuniorQu[119] = {ID = 119, examType = 2, question = '是谁告诉孙坚这传国玉玺的来龙去脉的?', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '韩当', falseAnswer2 = '黄盖'}
JuniorQu[120] = {ID = 120, examType = 2, question = '孙坚得了玉玺后离开洛阳，袁绍让谁阻拦孙?', trueAnswerId = 1, trueAnswer = '刘表', falseAnswer1 = '袁术', falseAnswer2 = '刘岱'}
JuniorQu[121] = {ID = 121, examType = 2, question = '第七镇首领乔瑁为谁所杀?', trueAnswerId = 1, trueAnswer = '刘岱', falseAnswer1 = '公孙瓒', falseAnswer2 = '张飞'}
JuniorQu[122] = {ID = 122, examType = 2, question = '刘表与名士七人为友，被称为什么?', trueAnswerId = 1, trueAnswer = '江夏八俊', falseAnswer1 = '江陵八俊', falseAnswer2 = '荆州八杰'}
JuniorQu[123] = {ID = 123, examType = 2, question = '公孙瓒上了袁绍的当，以为发兵可以平分何州?', trueAnswerId = 1, trueAnswer = '冀州', falseAnswer1 = '江州', falseAnswer2 = '豫州'}
JuniorQu[124] = {ID = 124, examType = 2, question = '书中赵云一出场便救了谁?', trueAnswerId = 1, trueAnswer = '公孙瓒', falseAnswer1 = '袁绍', falseAnswer2 = '刘表'}
JuniorQu[125] = {ID = 125, examType = 2, question = '赵云最初是谁的手下?', trueAnswerId = 1, trueAnswer = '袁绍', falseAnswer1 = '袁术', falseAnswer2 = '公孙瓒'}
JuniorQu[126] = {ID = 126, examType = 2, question = '被羌人称为“白马将军”的是谁?', trueAnswerId = 1, trueAnswer = '公孙瓒', falseAnswer1 = '赵云', falseAnswer2 = '文丑'}
JuniorQu[127] = {ID = 127, examType = 2, question = '孙坚有四子，皆是谁所生?', trueAnswerId = 1, trueAnswer = '吴夫人', falseAnswer1 = '周夫人', falseAnswer2 = '郑夫人'}
JuniorQu[128] = {ID = 128, examType = 2, question = '蔡瑁与刘表是何关系?', trueAnswerId = 1, trueAnswer = '蔡是刘的大舅子', falseAnswer1 = '刘是蔡的表哥', falseAnswer2 = '刘是蔡的连襟'}
JuniorQu[129] = {ID = 129, examType = 2, question = '孙坚受何人伏击而死?', trueAnswerId = 1, trueAnswer = '吕公', falseAnswer1 = '黄祖', falseAnswer2 = '蒯越'}
JuniorQu[130] = {ID = 130, examType = 2, question = '孙坚死时几岁?', trueAnswerId = 1, trueAnswer = '三十七', falseAnswer1 = '三十五', falseAnswer2 = '三十九'}
JuniorQu[131] = {ID = 131, examType = 2, question = '生擒黄祖的是谁?', trueAnswerId = 1, trueAnswer = '黄盖', falseAnswer1 = '韩当', falseAnswer2 = '程普'}
JuniorQu[132] = {ID = 132, examType = 2, question = '将伏击孙坚的吕公刺死的是谁?', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '韩当', falseAnswer2 = '黄盖'}
JuniorQu[133] = {ID = 133, examType = 2, question = '谁认为“貂蝉是假意对吕布，心中只有王允一人”?', trueAnswerId = 1, trueAnswer = '毛宗岗', falseAnswer1 = '毛纶', falseAnswer2 = '易中天'}
JuniorQu[134] = {ID = 134, examType = 2, question = '谁称董卓为“尚父”?', trueAnswerId = 1, trueAnswer = '董卓自封的', falseAnswer1 = '吕布', falseAnswer2 = '献帝'}
JuniorQu[135] = {ID = 135, examType = 2, question = '董卓筑郿，动用了民夫多少人?', trueAnswerId = 1, trueAnswer = '二十五万', falseAnswer1 = '五千', falseAnswer2 = '五万'}
JuniorQu[136] = {ID = 136, examType = 2, question = '李儒以昔日何人“摘缨会”的故事劝谏董卓，让他把貂蝉让给吕布?', trueAnswerId = 1, trueAnswer = '楚庄王', falseAnswer1 = '楚怀王', falseAnswer2 = '楚灵王'}
JuniorQu[137] = {ID = 137, examType = 2, question = '谁想到让李肃去骗董卓还朝，继而诛杀董?', trueAnswerId = 1, trueAnswer = '吕布', falseAnswer1 = '王允', falseAnswer2 = '黄琬'}
JuniorQu[138] = {ID = 138, examType = 2, question = '董卓准备去受禅前告别其母，董母已多少余岁?', trueAnswerId = 1, trueAnswer = '九十', falseAnswer1 = '六十', falseAnswer2 = '七十'}
JuniorQu[139] = {ID = 139, examType = 2, question = '董卓回京路上发生了三件怪事，以下哪项不对?', trueAnswerId = 1, trueAnswer = '暴雨倾盆，昏天黑地', falseAnswer1 = '车轮突然坏了', falseAnswer2 = '马突然咆哮嘶喊，并断了马辔'}
JuniorQu[140] = {ID = 140, examType = 2, question = '“千里草，何青青!十日卜，不得生”这首隐喻董卓将死的儿歌是谁作的?', trueAnswerId = 1, trueAnswer = '以上均错', falseAnswer1 = '李肃', falseAnswer2 = '王允'}
JuniorQu[141] = {ID = 141, examType = 2, question = '董卓的头是被谁割下的?', trueAnswerId = 1, trueAnswer = '李肃', falseAnswer1 = '吕布', falseAnswer2 = '王允'}
JuniorQu[142] = {ID = 142, examType = 2, question = '闻之吕布已死，李傕等人率什么军连夜奔凉州去了?', trueAnswerId = 1, trueAnswer = '飞熊军', falseAnswer1 = '飞虎军', falseAnswer2 = '飞龙军'}
JuniorQu[143] = {ID = 143, examType = 2, question = '董卓的女婿牛辅被谁所杀?', trueAnswerId = 1, trueAnswer = '胡赤儿', falseAnswer1 = '吕布', falseAnswer2 = '李肃'}
JuniorQu[144] = {ID = 144, examType = 2, question = '诛杀董卓的大功臣李肃被谁所杀?', trueAnswerId = 1, trueAnswer = '吕布', falseAnswer1 = '牛辅', falseAnswer2 = '张济'}
JuniorQu[145] = {ID = 145, examType = 2, question = '王允是如何而死?', trueAnswerId = 1, trueAnswer = '被李傕郭汜刺死', falseAnswer1 = '跳楼而亡', falseAnswer2 = '献帝下令斩首'}
JuniorQu[146] = {ID = 146, examType = 2, question = '以下何人不同意杀献帝?', trueAnswerId = 1, trueAnswer = '张济', falseAnswer1 = '李傕', falseAnswer2 = '郭汜'}
JuniorQu[147] = {ID = 147, examType = 2, question = '以下三人密奏献帝封马腾为征西将军，除外何人?', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '种邵', falseAnswer2 = '刘范'}
JuniorQu[148] = {ID = 148, examType = 2, question = '马超十七岁刚出道时，刺死的第一人是谁?', trueAnswerId = 1, trueAnswer = '王方', falseAnswer1 = '李蒙', falseAnswer2 = '刘范'}
JuniorQu[149] = {ID = 149, examType = 2, question = '樊稠为何被李傕所杀?', trueAnswerId = 1, trueAnswer = '放走韩遂', falseAnswer1 = '为献帝求情', falseAnswer2 = '私通马腾部'}
JuniorQu[150] = {ID = 150, examType = 2, question = '曹操招降到多少余万人，精组成“青州兵”?', trueAnswerId = 1, trueAnswer = '三十', falseAnswer1 = '五', falseAnswer2 = '十'}
JuniorQu[151] = {ID = 151, examType = 2, question = '以下哪句话不正确?', trueAnswerId = 1, trueAnswer = '满宠是毛玠推荐的', falseAnswer1 = '程昱是荀彧推荐的', falseAnswer2 = '郭嘉是程昱推荐的'}
JuniorQu[152] = {ID = 152, examType = 2, question = '典韦是何人保荐的?', trueAnswerId = 1, trueAnswer = '夏侯惇', falseAnswer1 = '于禁', falseAnswer2 = '乐进'}
JuniorQu[153] = {ID = 153, examType = 2, question = '典韦的铁戟重多少斤?', trueAnswerId = 1, trueAnswer = '八十', falseAnswer1 = '六十二', falseAnswer2 = '七十四'}
JuniorQu[154] = {ID = 154, examType = 2, question = '曹操之父被乱军杀死于何处?', trueAnswerId = 1, trueAnswer = '厕所', falseAnswer1 = '驿站', falseAnswer2 = '马车'}
JuniorQu[155] = {ID = 155, examType = 2, question = '路遇火德星君扮的美人，能做到目不邪视的是谁?', trueAnswerId = 1, trueAnswer = '孔融', falseAnswer1 = '糜竺', falseAnswer2 = '糜芳'}
JuniorQu[156] = {ID = 156, examType = 2, question = '以下何句错误?', trueAnswerId = 1, trueAnswer = '曹操来打徐州，陶谦让糜竺先去北海', falseAnswer1 = '曹操来打徐州，陶谦让陈登去青州求援', falseAnswer2 = '曹操来打徐州，陶谦让糜竺去北海求援'}
JuniorQu[157] = {ID = 157, examType = 2, question = '孔融是“孔子”的第几代世孙?', trueAnswerId = 1, trueAnswer = '二十', falseAnswer1 = '十五', falseAnswer2 = '十八'}
JuniorQu[158] = {ID = 158, examType = 2, question = '孔融十岁时去见河南尹告之其祖宗孔子与谁关系交好，故两家属世交?', trueAnswerId = 1, trueAnswer = '老子', falseAnswer1 = '孟子', falseAnswer2 = '庄子'}
JuniorQu[159] = {ID = 159, examType = 2, question = '认为孔融小时聪明，长大未必就见聪明的是谁?', trueAnswerId = 1, trueAnswer = '陈炜', falseAnswer1 = '李膺', falseAnswer2 = '孟旻'}
JuniorQu[160] = {ID = 160, examType = 2, question = '黄巾军管亥以向孔融借多少石粮食为名来攻打北海?', trueAnswerId = 1, trueAnswer = '一万', falseAnswer1 = '三千', falseAnswer2 = '五千'}
JuniorQu[161] = {ID = 161, examType = 2, question = '太史慈为何来救孔融?', trueAnswerId = 1, trueAnswer = '其母常得孔融照顾，为报恩，命儿子去救孔', falseAnswer1 = '早就对孔融仰慕已久', falseAnswer2 = '回来路上遇见孔融兵败'}
JuniorQu[162] = {ID = 162, examType = 2, question = '黄巾军管亥在乱军中被谁所杀?', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '太史慈', falseAnswer2 = '张飞'}
JuniorQu[163] = {ID = 163, examType = 2, question = '刘备率部来救徐州，与曹军何部先交上了火?', trueAnswerId = 1, trueAnswer = '于禁', falseAnswer1 = '夏侯惇', falseAnswer2 = '曹洪'}
JuniorQu[164] = {ID = 164, examType = 2, question = '袁绍为何想杀投靠的吕布?', trueAnswerId = 1, trueAnswer = '吕布对袁绍手下将士不屑一顾', falseAnswer1 = '觉得吕布六亲不认，反复无常，早除为妙', falseAnswer2 = '听袁术劝说，不要养虎为患'}
JuniorQu[165] = {ID = 165, examType = 2, question = '在长安城中，帮吕布私藏妻小的是谁?', trueAnswerId = 1, trueAnswer = '庞舒', falseAnswer1 = '张超', falseAnswer2 = '袁绘'}
JuniorQu[166] = {ID = 166, examType = 2, question = '是谁想到曹操正在攻打徐州，应该去将军事要地兖州拿下?', trueAnswerId = 1, trueAnswer = '陈宫', falseAnswer1 = '吕布', falseAnswer2 = '张超'}
JuniorQu[167] = {ID = 167, examType = 2, question = '曹军偷袭吕布营寨，以下哪两人联手敌不过吕布?', trueAnswerId = 1, trueAnswer = '于禁,乐进', falseAnswer1 = '夏侯惇,夏侯渊', falseAnswer2 = '曹仁,曹洪'}
JuniorQu[168] = {ID = 168, examType = 2, question = '糜竺家中是如何着火的?', trueAnswerId = 1, trueAnswer = '无任何原因着火', falseAnswer1 = '厨子不慎打翻烛火引致', falseAnswer2 = '有旧怨怀恨夜间纵火'}
JuniorQu[169] = {ID = 169, examType = 2, question = '濮阳城中的老田与曹操约定暗号是旗上书何字?', trueAnswerId = 1, trueAnswer = '义', falseAnswer1 = '忠', falseAnswer2 = '诚'}
JuniorQu[170] = {ID = 170, examType = 2, question = '在濮阳城上何方位竖着一面与曹操约定好的白旗?', trueAnswerId = 1, trueAnswer = '西门', falseAnswer1 = '东门', falseAnswer2 = '南门'}
JuniorQu[171] = {ID = 171, examType = 2, question = '以下谁劝曹操不要进濮阳城，操不听?', trueAnswerId = 1, trueAnswer = '李典', falseAnswer1 = '夏侯渊', falseAnswer2 = '乐进'}
JuniorQu[172] = {ID = 172, examType = 2, question = '曹操差点被吕布认出擒获，急中生智地指出骑何色马者是曹操?', trueAnswerId = 1, trueAnswer = '黄', falseAnswer1 = '白', falseAnswer2 = '红'}
JuniorQu[173] = {ID = 173, examType = 2, question = '曹操在濮阳城内被火梁烧伤，是以下哪两将救了操?', trueAnswerId = 1, trueAnswer = '典韦,夏侯渊', falseAnswer1 = '李典,乐进', falseAnswer2 = '于禁,夏侯惇'}
JuniorQu[174] = {ID = 174, examType = 2, question = '陶谦三让徐州时，已经几岁了?', trueAnswerId = 1, trueAnswer = '六十三', falseAnswer1 = '五十五', falseAnswer2 = '五十八'}
JuniorQu[175] = {ID = 175, examType = 2, question = '以下谁用了拖刀计将截天夜叉何曼杀死?', trueAnswerId = 1, trueAnswer = '曹洪', falseAnswer1 = '夏侯渊', falseAnswer2 = '李典'}
JuniorQu[176] = {ID = 176, examType = 2, question = '与许褚不打不相识的是谁?', trueAnswerId = 1, trueAnswer = '典韦', falseAnswer1 = '夏侯惇', falseAnswer2 = '曹仁'}
JuniorQu[177] = {ID = 177, examType = 2, question = '薛兰、李封是被以下哪两人分别所杀?', trueAnswerId = 1, trueAnswer = '许褚,吕虔', falseAnswer1 = '典韦,许褚', falseAnswer2 = '吕虔,乐进'}
JuniorQu[178] = {ID = 178, examType = 2, question = '张超自刎，张邈投袁术后，曹操全部占领了何地?', trueAnswerId = 1, trueAnswer = '山东', falseAnswer1 = '河南', falseAnswer2 = '河北'}
JuniorQu[179] = {ID = 179, examType = 2, question = '以下谁称刘备是“金枝玉叶”?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '糜竺', falseAnswer2 = '陶谦'}
JuniorQu[180] = {ID = 180, examType = 2, question = '以下何人妻子妒忌心最强?', trueAnswerId = 1, trueAnswer = '郭汜', falseAnswer1 = '杨彪', falseAnswer2 = '皇甫郦'}
JuniorQu[181] = {ID = 181, examType = 2, question = '郭汜从什么时候起对李傕起疑了?', trueAnswerId = 1, trueAnswer = '郭汜用犬试了李傕家的食物后', falseAnswer1 = '杨彪妻子来告诉郭妻李有害郭之心', falseAnswer2 = '郭汜在李傕家吃后回家腹痛'}
JuniorQu[182] = {ID = 182, examType = 2, question = '以下谁最喜左道妖邪之术?', trueAnswerId = 1, trueAnswer = '李傕', falseAnswer1 = '郭汜', falseAnswer2 = '杨奉'}
JuniorQu[183] = {ID = 183, examType = 2, question = '郭汜原来是什么出身?', trueAnswerId = 1, trueAnswer = '盗马贼', falseAnswer1 = '掘墓人', falseAnswer2 = '屠夫'}
JuniorQu[184] = {ID = 184, examType = 2, question = '李傕告诉皇甫郦他已经辅政献帝多少年了?', trueAnswerId = 1, trueAnswer = '四', falseAnswer1 = '半', falseAnswer2 = '一'}
JuniorQu[185] = {ID = 185, examType = 2, question = '勤王之师杨奉军的旗上写着什么字?', trueAnswerId = 1, trueAnswer = '大汉杨奉', falseAnswer1 = '平原杨奉', falseAnswer2 = '终南山杨奉'}
JuniorQu[186] = {ID = 186, examType = 2, question = '徐晃原是谁手下的大将?', trueAnswerId = 1, trueAnswer = '杨奉', falseAnswer1 = '李乐', falseAnswer2 = '董承'}
JuniorQu[187] = {ID = 187, examType = 2, question = '“前番两贼分为二，今番三贼合为一”吓得献帝心惊胆战，其中第三贼是指的谁?', trueAnswerId = 1, trueAnswer = '李乐', falseAnswer1 = '韩暹', falseAnswer2 = '杨奉'}
JuniorQu[188] = {ID = 188, examType = 2, question = '三贼之一的李乐被谁所杀?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '杨奉', falseAnswer2 = '韩暹'}
JuniorQu[189] = {ID = 189, examType = 2, question = '李傕、郭汜攻洛阳，谁向献帝建议往山东避逃?', trueAnswerId = 1, trueAnswer = '董承', falseAnswer1 = '杨彪', falseAnswer2 = '杨奉'}
JuniorQu[190] = {ID = 190, examType = 2, question = '曹操称赞谁是当今的“樊哙”?', trueAnswerId = 1, trueAnswer = '许褚', falseAnswer1 = '典韦', falseAnswer2 = '张飞'}
JuniorQu[191] = {ID = 191, examType = 2, question = '建议曹操迁都许都的是谁?', trueAnswerId = 1, trueAnswer = '董昭', falseAnswer1 = '荀彧', falseAnswer2 = '郭嘉'}
JuniorQu[192] = {ID = 192, examType = 2, question = '去劝降徐晃的谋士是谁?', trueAnswerId = 1, trueAnswer = '满宠', falseAnswer1 = '毛玠', falseAnswer2 = '刘晔'}
JuniorQu[193] = {ID = 193, examType = 2, question = '向曹操献“二虎竞食”及“驱虎吞狼”之计的是谁?', trueAnswerId = 1, trueAnswer = '荀彧', falseAnswer1 = '郭嘉', falseAnswer2 = '程昱'}
JuniorQu[194] = {ID = 194, examType = 2, question = '纪灵与谁交手不分胜负?', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '糜芳', falseAnswer2 = '乐进'}
JuniorQu[195] = {ID = 195, examType = 2, question = '曹豹是谁的岳丈?', trueAnswerId = 1, trueAnswer = '吕布', falseAnswer1 = '陈登', falseAnswer2 = '糜竺'}
JuniorQu[196] = {ID = 196, examType = 2, question = '张飞被吕布夜袭后，一直逃到哪里才与刘备相会?', trueAnswerId = 1, trueAnswer = '盱眙', falseAnswer1 = '徐州', falseAnswer2 = '小沛'}
JuniorQu[197] = {ID = 197, examType = 2, question = '孙策在庭院中想起孙坚时放声大哭，以下谁出来劝慰?', trueAnswerId = 1, trueAnswer = '朱治', falseAnswer1 = '周瑜', falseAnswer2 = '吕范'}
JuniorQu[198] = {ID = 198, examType = 2, question = '孙策将传国玉玺作为抵押物，才向袁术借得多少兵?', trueAnswerId = 1, trueAnswer = '三千', falseAnswer1 = '一千', falseAnswer2 = '二千'}
JuniorQu[199] = {ID = 199, examType = 2, question = '以下何句正确?', trueAnswerId = 1, trueAnswer = '孙策和周瑜同岁', falseAnswer1 = '孙策比周瑜大一岁', falseAnswer2 = '孙策比周瑜大二岁'}
JuniorQu[200] = {ID = 200, examType = 2, question = '以下谁属于周瑜推荐的“二张”?', trueAnswerId = 1, trueAnswer = '张昭', falseAnswer1 = '张英', falseAnswer2 = '张宠'}
JuniorQu[201] = {ID = 201, examType = 2, question = '刘繇是谁的兄弟?', trueAnswerId = 1, trueAnswer = '刘岱', falseAnswer1 = '刘宠', falseAnswer2 = '刘秀'}
JuniorQu[202] = {ID = 202, examType = 2, question = '孙策去烧香，带了随从多少人?', trueAnswerId = 1, trueAnswer = '十二', falseAnswer1 = '八', falseAnswer2 = '十'}
JuniorQu[203] = {ID = 203, examType = 2, question = '孙策与太史慈扭打滚到地上后，孙策手快拿了太史慈的什么东西?', trueAnswerId = 1, trueAnswer = '短戟', falseAnswer1 = '短刀', falseAnswer2 = '头盔'}
JuniorQu[204] = {ID = 204, examType = 2, question = '孙策手下谁长得面黄眼赤，形容古怪?', trueAnswerId = 1, trueAnswer = '陈武', falseAnswer1 = '张纮', falseAnswer2 = '朱治'}
JuniorQu[205] = {ID = 205, examType = 2, question = '孙策为何被众人皆呼“小霸王”?', trueAnswerId = 1, trueAnswer = '孙策曾经喝死挟死过二将', falseAnswer1 = '孙策为人比较刚愎自用', falseAnswer2 = '孙策有时非常不讲道理'}
JuniorQu[206] = {ID = 206, examType = 2, question = '以下何句正确?', trueAnswerId = 1, trueAnswer = '孙策诈死令薛礼中计', falseAnswer1 = '孙策将樊能挟死', falseAnswer2 = '孙策将于糜喝死'}
JuniorQu[207] = {ID = 207, examType = 2, question = '“孙郎”是指谁?', trueAnswerId = 1, trueAnswer = '孙策', falseAnswer1 = '孙坚', falseAnswer2 = '孙权'}
JuniorQu[208] = {ID = 208, examType = 2, question = '以下谁的箭术非常了得?', trueAnswerId = 1, trueAnswer = '太史慈', falseAnswer1 = '陈武', falseAnswer2 = '周泰'}
JuniorQu[209] = {ID = 209, examType = 2, question = '谁提了严白虎的首级来献给孙策?', trueAnswerId = 1, trueAnswer = '董袭', falseAnswer1 = '周昕', falseAnswer2 = '凌操'}
JuniorQu[210] = {ID = 210, examType = 2, question = '以下周泰为救孙权，身中多少枪?', trueAnswerId = 1, trueAnswer = '十二', falseAnswer1 = '六', falseAnswer2 = '八'}
JuniorQu[211] = {ID = 211, examType = 2, question = '“不去江东图虎豹，却来徐郡斗蛟龙”一句是指谁为袁术出谋画策?', trueAnswerId = 1, trueAnswer = '杨大将', falseAnswer1 = '陈兰', falseAnswer2 = '雷薄'}
JuniorQu[212] = {ID = 212, examType = 2, question = '袁术给了吕布多少斛粮食，让其去打刘备?', trueAnswerId = 1, trueAnswer = '二十万', falseAnswer1 = '五万', falseAnswer2 = '十万'}
JuniorQu[213] = {ID = 213, examType = 2, question = '吕布辕门射戟的目的是什么?', trueAnswerId = 1, trueAnswer = '为了不想参与争斗，而又想白赚粮食', falseAnswer1 = '为了展示一下自己射箭的功夫', falseAnswer2 = '为了调解刘备与曹操之间的矛盾'}
JuniorQu[214] = {ID = 214, examType = 2, question = '吕布辕门射戟的距离是多少?', trueAnswerId = 1, trueAnswer = '一百五十步', falseAnswer1 = '一百步', falseAnswer2 = '二百步'}
JuniorQu[215] = {ID = 215, examType = 2, question = '吕布的哪个妻妾的女儿及笄了，袁术派人为儿子来求亲?', trueAnswerId = 1, trueAnswer = '曹氏', falseAnswer1 = '严氏', falseAnswer2 = '貂蝉'}
JuniorQu[216] = {ID = 216, examType = 2, question = '以下哪句正确?', trueAnswerId = 1, trueAnswer = '吕布有一妻三妾', falseAnswer1 = '吕布有一妻一妾', falseAnswer2 = '吕布有一妻二妾'}
JuniorQu[217] = {ID = 217, examType = 2, question = '袁术派谁来作媒人向吕布提亲的?', trueAnswerId = 1, trueAnswer = '韩胤', falseAnswer1 = '纪灵', falseAnswer2 = '宋宪'}
JuniorQu[218] = {ID = 218, examType = 2, question = '识破袁术求亲是“疏不间亲”之计的是谁?', trueAnswerId = 1, trueAnswer = '陈珪', falseAnswer1 = '吕布', falseAnswer2 = '陈宫'}
JuniorQu[219] = {ID = 219, examType = 2, question = '张飞故意拦路抢了吕布部的好马多少匹?', trueAnswerId = 1, trueAnswer = '一百五十', falseAnswer1 = '一百', falseAnswer2 = '二百'}
JuniorQu[220] = {ID = 220, examType = 2, question = '谁劝张绣投降曹操的?', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '程昱', falseAnswer2 = '郭嘉'}
JuniorQu[221] = {ID = 221, examType = 2, question = '在宛城，给曹操介绍美女邹氏的是谁?', trueAnswerId = 1, trueAnswer = '曹安民', falseAnswer1 = '曹昂', falseAnswer2 = '曹丕'}
JuniorQu[222] = {ID = 222, examType = 2, question = '以下何句正确?', trueAnswerId = 1, trueAnswer = '邹氏是张绣的婶婶', falseAnswer1 = '邹氏是张绣的小妾', falseAnswer2 = '邹氏是张绣的表妹'}
JuniorQu[223] = {ID = 223, examType = 2, question = '张绣的偏将胡车儿能日行多少里?', trueAnswerId = 1, trueAnswer = '七百', falseAnswer1 = '二百', falseAnswer2 = '四百'}
JuniorQu[224] = {ID = 224, examType = 2, question = '曹操的长子是如何而死的?', trueAnswerId = 1, trueAnswer = '被乱军射死的', falseAnswer1 = '被胡车儿砍死', falseAnswer2 = '被乱军剁死'}
JuniorQu[225] = {ID = 225, examType = 2, question = '以下谁因为治兵不严受到曹操的惩罚?', trueAnswerId = 1, trueAnswer = '夏侯惇', falseAnswer1 = '曹洪', falseAnswer2 = '乐进'}
JuniorQu[226] = {ID = 226, examType = 2, question = '曹操封谁为益寿亭侯?', trueAnswerId = 1, trueAnswer = '于禁', falseAnswer1 = '夏侯惇', falseAnswer2 = '典韦'}
JuniorQu[227] = {ID = 227, examType = 2, question = '袁术认为袁姓出于陈，陈是谁的后代?', trueAnswerId = 1, trueAnswer = '禹', falseAnswer1 = '尧', falseAnswer2 = '舜'}
JuniorQu[228] = {ID = 228, examType = 2, question = '袁术称帝后，起七路军征徐州，其中上将纪灵是第几路军首领?', trueAnswerId = 1, trueAnswer = '三', falseAnswer1 = '一', falseAnswer2 = '五'}
JuniorQu[229] = {ID = 229, examType = 2, question = '袁术七路军征徐州，其中以下哪路军首领是汉室降将?', trueAnswerId = 1, trueAnswer = '韩暹', falseAnswer1 = '张勋', falseAnswer2 = '陈纪'}
JuniorQu[230] = {ID = 230, examType = 2, question = '骂吕布是“背主家奴”的是谁?', trueAnswerId = 1, trueAnswer = '袁术', falseAnswer1 = '曹操', falseAnswer2 = '纪灵'}
JuniorQu[231] = {ID = 231, examType = 2, question = '决定杀掉韩暹、杨奉两名降将的是谁?', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '吕布', falseAnswer2 = '陈宫'}
JuniorQu[232] = {ID = 232, examType = 2, question = '曹操粮草吃紧，将谁推出当替死鬼以稳定军心?', trueAnswerId = 1, trueAnswer = '王垕', falseAnswer1 = '阎象', falseAnswer2 = '李丰'}
JuniorQu[233] = {ID = 233, examType = 2, question = '以下何句不正确?', trueAnswerId = 1, trueAnswer = '吕布杀了杨奉', falseAnswer1 = '桥蕤为夏侯惇所杀', falseAnswer2 = '段煨杀了李傕'}
JuniorQu[234] = {ID = 234, examType = 2, question = '曹操马踏麦田，欲装模作样自刎，郭嘉以何书上的“法不加于尊”劝慰曹操?', trueAnswerId = 1, trueAnswer = '《春秋》', falseAnswer1 = '《左传》', falseAnswer2 = '《尙书》'}
JuniorQu[235] = {ID = 235, examType = 2, question = '毛宗岗对以下哪个谋士最为欣赏?', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '郭嘉', falseAnswer2 = '荀彧'}
JuniorQu[236] = {ID = 236, examType = 2, question = '贾诩识破曹操绕城三日侦查后必然会选定攻城的何方?', trueAnswerId = 1, trueAnswer = '东南角', falseAnswer1 = '东北角', falseAnswer2 = '西南角'}
JuniorQu[237] = {ID = 237, examType = 2, question = '曹操攻城被贾诩识破后折兵五万，另有哪两大将受伤?', trueAnswerId = 1, trueAnswer = '吕虔,于禁', falseAnswer1 = '夏侯惇,夏侯渊', falseAnswer2 = '李典,许褚'}
JuniorQu[238] = {ID = 238, examType = 2, question = '来接应被张绣和刘表夹击的曹操部的是谁?', trueAnswerId = 1, trueAnswer = '李通', falseAnswer1 = '许褚', falseAnswer2 = '夏侯渊'}
JuniorQu[239] = {ID = 239, examType = 2, question = '“十胜十败说”是谁的理论?', trueAnswerId = 1, trueAnswer = '郭嘉', falseAnswer1 = '贾诩', falseAnswer2 = '荀彧'}
JuniorQu[240] = {ID = 240, examType = 2, question = '夏侯惇的左眼是被谁射中的?', trueAnswerId = 1, trueAnswer = '曹性', falseAnswer1 = '高顺', falseAnswer2 = '宋宪'}
JuniorQu[241] = {ID = 241, examType = 2, question = '猎户刘安杀了妻子给刘备下酒，谎称是什么肉?', trueAnswerId = 1, trueAnswer = '狼肉', falseAnswer1 = '猪肉', falseAnswer2 = '狗肉'}
JuniorQu[242] = {ID = 242, examType = 2, question = '泰山土匪孙观、吴敦等四人敌不过谁一人?', trueAnswerId = 1, trueAnswer = '许褚', falseAnswer1 = '张飞', falseAnswer2 = '关羽'}
JuniorQu[243] = {ID = 243, examType = 2, question = '吕布自恃粮食充足，准备死守何处?', trueAnswerId = 1, trueAnswer = '下邳', falseAnswer1 = '小沛', falseAnswer2 = '徐州'}
JuniorQu[244] = {ID = 244, examType = 2, question = '陈宫在城头上偷袭曹操，射中其何部位?', trueAnswerId = 1, trueAnswer = '头盔', falseAnswer1 = '战马', falseAnswer2 = '左肩'}
JuniorQu[245] = {ID = 245, examType = 2, question = '陈宫建议吕布亲率兵去断曹操的粮道，以下谁第一个出来表示反对?', trueAnswerId = 1, trueAnswer = '严氏', falseAnswer1 = '高顺', falseAnswer2 = '许汜'}
JuniorQu[246] = {ID = 246, examType = 2, question = '护送许汜、王楷杀出重围去向袁术求救兵的是以下哪两将?', trueAnswerId = 1, trueAnswer = '郝萌,张辽', falseAnswer1 = '张辽,高顺', falseAnswer2 = '高顺,郝萌'}
JuniorQu[247] = {ID = 247, examType = 2, question = '郝萌被谁生擒后招出了吕布求救许婚之事?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '许褚', falseAnswer2 = '徐晃'}
JuniorQu[248] = {ID = 248, examType = 2, question = '许汜建议吕布在何时分，将吕布之女送出城外?', trueAnswerId = 1, trueAnswer = '戌、亥时', falseAnswer1 = '子、丑时', falseAnswer2 = '寅、卯时'}
JuniorQu[249] = {ID = 249, examType = 2, question = '河内太守谁准备发兵救吕布，被部将杨丑杀了?', trueAnswerId = 1, trueAnswer = '张杨', falseAnswer1 = '晆固', falseAnswer2 = '李远'}
JuniorQu[250] = {ID = 250, examType = 2, question = '见攻城两月未下后，谁建议放水淹城困死吕布?', trueAnswerId = 1, trueAnswer = '郭嘉', falseAnswer1 = '程昱', falseAnswer2 = '毛玠'}
JuniorQu[251] = {ID = 251, examType = 2, question = '曹操采纳了谋士的建议后，决堤放了哪两河之水?', trueAnswerId = 1, trueAnswer = '沂、泗', falseAnswer1 = '泾、渭', falseAnswer2 = '沅、洼'}
JuniorQu[252] = {ID = 252, examType = 2, question = '曹操命人放水后，吕布见城内只有何门无水淹?', trueAnswerId = 1, trueAnswer = '东', falseAnswer1 = '南', falseAnswer2 = '西'}
JuniorQu[253] = {ID = 253, examType = 2, question = '吕布将违酒令的谁痛打了一番?', trueAnswerId = 1, trueAnswer = '侯成', falseAnswer1 = '宋宪', falseAnswer2 = '魏续'}
JuniorQu[254] = {ID = 254, examType = 2, question = '为使夏侯渊相信吕布已被生擒，谁将吕布的画戟掷下城楼?', trueAnswerId = 1, trueAnswer = '宋宪', falseAnswer1 = '侯成', falseAnswer2 = '魏续'}
JuniorQu[255] = {ID = 255, examType = 2, question = '陈宫告诉曹操为何愿意跟随吕布?', trueAnswerId = 1, trueAnswer = '吕布为人不像曹操奸诈', falseAnswer1 = '吕布一身好武艺，只要有高人为其出谋画策，可成大事', falseAnswer2 = '当年曹操杀吕伯奢一家，陈宫至今无法原谅'}
JuniorQu[256] = {ID = 256, examType = 2, question = '“生死无二志，丈夫何壮哉”是称赞谁的?', trueAnswerId = 1, trueAnswer = '陈宫', falseAnswer1 = '王允', falseAnswer2 = '伍孚'}
JuniorQu[257] = {ID = 257, examType = 2, question = '山东强盗中只有何人不肯受臧霸招安?', trueAnswerId = 1, trueAnswer = '昌豨', falseAnswer1 = '孙观', falseAnswer2 = '吴敦'}
JuniorQu[258] = {ID = 258, examType = 2, question = '曹操斩吕布后，暂时让谁管辖徐州?', trueAnswerId = 1, trueAnswer = '车胄', falseAnswer1 = '臧霸', falseAnswer2 = '张辽'}
JuniorQu[259] = {ID = 259, examType = 2, question = '献帝查汉族宗谱，记载中山靖王刘胜是孝景皇帝的第几子?', trueAnswerId = 1, trueAnswer = '七', falseAnswer1 = '三', falseAnswer2 = '五'}
JuniorQu[260] = {ID = 260, examType = 2, question = '曹操将怀袁术有亲戚关系的谁收监了?', trueAnswerId = 1, trueAnswer = '杨彪', falseAnswer1 = '赵彦', falseAnswer2 = '吴硕'}
JuniorQu[261] = {ID = 261, examType = 2, question = '许田打围，献帝射中的是何猎物?', trueAnswerId = 1, trueAnswer = '什么也没射中', falseAnswer1 = '羚羊', falseAnswer2 = '兔子'}
JuniorQu[262] = {ID = 262, examType = 2, question = '许田打围，谁对曹操射中鹿后，群起呼万岁最为动怒?', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '献帝', falseAnswer2 = '刘备'}
JuniorQu[263] = {ID = 263, examType = 2, question = '董承是如何发现玉带里有献帝的血诏?', trueAnswerId = 1, trueAnswer = '灯花落于带上，破洞口显出血迹素绢', falseAnswer1 = '献帝赐给时有暗示', falseAnswer2 = '曹操路遇时对玉带锦袍表现出的特殊兴趣神情'}
JuniorQu[264] = {ID = 264, examType = 2, question = '献帝给董承的血诏上写着是建安几年?', trueAnswerId = 1, trueAnswer = '四', falseAnswer1 = '六', falseAnswer2 = '八'}
JuniorQu[265] = {ID = 265, examType = 2, question = '董承血诏素绢未收好，被王子服看见了上面的何字?', trueAnswerId = 1, trueAnswer = '联', falseAnswer1 = '曹贼', falseAnswer2 = '弄权'}
JuniorQu[266] = {ID = 266, examType = 2, question = '马腾教人取来的《鸳行鹭序簿》是本什么书?', trueAnswerId = 1, trueAnswer = '族谱', falseAnswer1 = '地图', falseAnswer2 = '官员名册'}
JuniorQu[267] = {ID = 267, examType = 2, question = '董承给刘备看过献帝的血诏后，又将义状拿出，上面已经有几人签名了?', trueAnswerId = 1, trueAnswer = '六', falseAnswer1 = '三', falseAnswer2 = '四'}
JuniorQu[268] = {ID = 268, examType = 2, question = '煮酒论英雄时，刘备所说的天下第一个英雄是谁?', trueAnswerId = 1, trueAnswer = '袁术', falseAnswer1 = '袁绍', falseAnswer2 = '刘表'}
JuniorQu[269] = {ID = 269, examType = 2, question = '袁绍“四世三公”出身，东汉时的“三公”是指除外以下哪项?', trueAnswerId = 1, trueAnswer = '司马', falseAnswer1 = '司空', falseAnswer2 = '司徒'}
JuniorQu[270] = {ID = 270, examType = 2, question = '刘备是被曹操手下哪两位请去饮酒品青梅?', trueAnswerId = 1, trueAnswer = '许褚,张辽', falseAnswer1 = '夏侯渊,夏侯惇', falseAnswer2 = '曹洪,曹仁'}
JuniorQu[271] = {ID = 271, examType = 2, question = '公孙瓒被袁绍击败后，如何而死?', trueAnswerId = 1, trueAnswer = '自缢', falseAnswer1 = '被乱军射死', falseAnswer2 = '被乱军砍死'}
JuniorQu[272] = {ID = 272, examType = 2, question = '大将纪灵死于何人之手?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '许褚', falseAnswer2 = '张辽'}
JuniorQu[273] = {ID = 273, examType = 2, question = '袁术病死于今何省?', trueAnswerId = 1, trueAnswer = '安徽', falseAnswer1 = '河北', falseAnswer2 = '山东'}
JuniorQu[274] = {ID = 274, examType = 2, question = '袁术死后，玉玺被谁夺得献给曹操?', trueAnswerId = 1, trueAnswer = '徐璆', falseAnswer1 = '袁胤', falseAnswer2 = '刘勋'}
JuniorQu[275] = {ID = 275, examType = 2, question = '朱灵、路昭两将对刘备无可奈何，没有起到监督、胁持作用差点被曹操杀了，是谁出面求情方才使两人免于死罪?', trueAnswerId = 1, trueAnswer = '孔融', falseAnswer1 = '郭嘉', falseAnswer2 = '程昱'}
JuniorQu[276] = {ID = 276, examType = 2, question = '关羽冒充曹操手下何部夜半将车胄杀了?', trueAnswerId = 1, trueAnswer = '张辽', falseAnswer1 = '曹洪', falseAnswer2 = '夏侯惇'}
JuniorQu[277] = {ID = 277, examType = 2, question = '以下何人连家里的侍婢也熟读《诗经》?', trueAnswerId = 1, trueAnswer = '郑玄', falseAnswer1 = '马融', falseAnswer2 = '陈琳'}
JuniorQu[278] = {ID = 278, examType = 2, question = '袁绍让谁起草攻伐曹操的檄文?', trueAnswerId = 1, trueAnswer = '陈琳', falseAnswer1 = '荀攸', falseAnswer2 = '郭图'}
JuniorQu[279] = {ID = 279, examType = 2, question = '刘岱、王忠引军五万，打着什么旗号去徐州攻刘备?', trueAnswerId = 1, trueAnswer = '丞相', falseAnswer1 = '汉室', falseAnswer2 = '曹操'}
JuniorQu[280] = {ID = 280, examType = 2, question = '关于刘备来讨救兵抗曹，以下谁对袁绍不采用自己的计谋非常不满?', trueAnswerId = 1, trueAnswer = '沮授', falseAnswer1 = '田丰', falseAnswer2 = '审配'}
JuniorQu[281] = {ID = 281, examType = 2, question = '以下何句正确?', trueAnswerId = 1, trueAnswer = '刘岱、王忠两人都不想出战', falseAnswer1 = '刘岱、王忠都争着想先立功', falseAnswer2 = '刘岱、王忠最后两人以比武决定谁先上阵'}
JuniorQu[282] = {ID = 282, examType = 2, question = '以下何句正确?', trueAnswerId = 1, trueAnswer = '刘备不让张飞先出战，是怕张飞把王忠给杀了', falseAnswer1 = '王忠被张飞所擒', falseAnswer2 = '刘岱被关羽所擒'}
JuniorQu[283] = {ID = 283, examType = 2, question = '以下何人不是袁绍手下的名将?', trueAnswerId = 1, trueAnswer = '敦于琼', falseAnswer1 = '颜良', falseAnswer2 = '高览'}
JuniorQu[284] = {ID = 284, examType = 2, question = '曹操派谁去张绣那里劝降?', trueAnswerId = 1, trueAnswer = '刘晔', falseAnswer1 = '孔融', falseAnswer2 = '程昱'}
JuniorQu[285] = {ID = 285, examType = 2, question = '祢衡是谁推荐给曹操的?', trueAnswerId = 1, trueAnswer = '孔融', falseAnswer1 = '程昱', falseAnswer2 = '刘晔'}
JuniorQu[286] = {ID = 286, examType = 2, question = '祢衡认为以下谁只配“看坟守墓”?', trueAnswerId = 1, trueAnswer = '荀攸', falseAnswer1 = '程昱', falseAnswer2 = '刘晔'}
JuniorQu[287] = {ID = 287, examType = 2, question = '祢衡认为以下谁只配“牧牛放马”?', trueAnswerId = 1, trueAnswer = '许褚', falseAnswer1 = '张辽', falseAnswer2 = '乐进'}
JuniorQu[288] = {ID = 288, examType = 2, question = '祢衡认为以下谁只配“屠猪杀狗”?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '许褚', falseAnswer2 = '乐进'}
JuniorQu[289] = {ID = 289, examType = 2, question = '以下谁第一个建议将祢衡杀了?', trueAnswerId = 1, trueAnswer = '张辽', falseAnswer1 = '荀彧', falseAnswer2 = '程昱'}
JuniorQu[290] = {ID = 290, examType = 2, question = '祢衡最后是被谁所杀?', trueAnswerId = 1, trueAnswer = '黄祖', falseAnswer1 = '曹操', falseAnswer2 = '蒯良'}
JuniorQu[291] = {ID = 291, examType = 2, question = '以下何句不正确?', trueAnswerId = 1, trueAnswer = '秦庆童同吉平侍妾私通', falseAnswer1 = '秦庆童是吉平的家奴', falseAnswer2 = '秦庆童躲在曹操府里'}
JuniorQu[292] = {ID = 292, examType = 2, question = '曹操亲自用刀削掉了吉平几个手指?', trueAnswerId = 1, trueAnswer = '九', falseAnswer1 = '三', falseAnswer2 = '五'}
JuniorQu[293] = {ID = 293, examType = 2, question = '吉平是如何强行给曹操灌毒药的?', trueAnswerId = 1, trueAnswer = '拉着曹操耳朵', falseAnswer1 = '捏住曹操鼻子', falseAnswer2 = '抱住曹操的头'}
JuniorQu[294] = {ID = 294, examType = 2, question = '事发后，曹操将血诏上签名的几个人杀了?', trueAnswerId = 1, trueAnswer = '五', falseAnswer1 = '三', falseAnswer2 = '四'}
JuniorQu[295] = {ID = 295, examType = 2, question = '袁绍因为小儿子生什么病，所以无心论国事?', trueAnswerId = 1, trueAnswer = '疥疮', falseAnswer1 = '瘟疫', falseAnswer2 = '麻疹'}
JuniorQu[296] = {ID = 296, examType = 2, question = '荀彧见狂风吹折了哪两色旗，料定刘备晚上必来劫寨?', trueAnswerId = 1, trueAnswer = '红,青', falseAnswer1 = '红,黄', falseAnswer2 = '红,白'}
JuniorQu[297] = {ID = 297, examType = 2, question = '刘备被曹操杀败后，只身一人来投青州，青州刺史是谁?', trueAnswerId = 1, trueAnswer = '袁谭', falseAnswer1 = '袁熙', falseAnswer2 = '袁尚'}
JuniorQu[298] = {ID = 298, examType = 2, question = '以下谁献计截了关羽后路，然后再进行劝降?', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '张辽', falseAnswer2 = '郭嘉'}
JuniorQu[299] = {ID = 299, examType = 2, question = '张辽告诉关羽的“三便”除外以下哪项?', trueAnswerId = 1, trueAnswer = '便于随时去找刘备', falseAnswer1 = '便于保护刘备夫人', falseAnswer2 = '便于不违桃园之约'}
JuniorQu[300] = {ID = 300, examType = 2, question = '张辽以何人的“众人国士”之论，使曹操接受了关羽提出的三事?', trueAnswerId = 1, trueAnswer = '豫让', falseAnswer1 = '孟尝君', falseAnswer2 = '孙武'}
JuniorQu[301] = {ID = 301, examType = 2, question = '关羽让曹军退后以进城同嫂嫂商议投降事宜，以下谁认为有诈?', trueAnswerId = 1, trueAnswer = '荀彧', falseAnswer1 = '程昱', falseAnswer2 = '郭嘉'}
JuniorQu[302] = {ID = 302, examType = 2, question = '关羽的“美髯公”之称最早是由谁叫起的?', trueAnswerId = 1, trueAnswer = '汉献帝', falseAnswer1 = '曹操', falseAnswer2 = '张辽'}
JuniorQu[303] = {ID = 303, examType = 2, question = '关羽降曹后，甘夫人梦见什么来告诉关羽?', trueAnswerId = 1, trueAnswer = '刘备身陷土坑中', falseAnswer1 = '刘备被袁绍杀了', falseAnswer2 = '刘备责怪关羽为何降曹'}
JuniorQu[304] = {ID = 304, examType = 2, question = '袁绍刚愎自用，将谁关入大牢中?', trueAnswerId = 1, trueAnswer = '田丰', falseAnswer1 = '沮授', falseAnswer2 = '审配'}
JuniorQu[305] = {ID = 305, examType = 2, question = '颜良所杀的曹军第一个大将是何人?', trueAnswerId = 1, trueAnswer = '宋宪', falseAnswer1 = '侯成', falseAnswer2 = '魏续'}
JuniorQu[306] = {ID = 306, examType = 2, question = '曹军中哪员大将不敌颜良后，曹军诸将皆骇然?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '张辽', falseAnswer2 = '许褚'}
JuniorQu[307] = {ID = 307, examType = 2, question = '文丑为何不愿与刘备同行?', trueAnswerId = 1, trueAnswer = '刘备是常败将军，很晦气', falseAnswer1 = '关羽将颜良杀了，迁怒于刘备', falseAnswer2 = '刘备平时一直喜欢逃跑，从心底瞧不起他'}
JuniorQu[308] = {ID = 308, examType = 2, question = '文丑一箭射中何人的头盔?', trueAnswerId = 1, trueAnswer = '张辽', falseAnswer1 = '徐晃', falseAnswer2 = '许褚'}
JuniorQu[309] = {ID = 309, examType = 2, question = '张辽战马被文丑射死，是谁来救的他?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '曹仁', falseAnswer2 = '夏侯渊'}
JuniorQu[310] = {ID = 310, examType = 2, question = '刘备溃败后，孙乾去投谁了?', trueAnswerId = 1, trueAnswer = '刘辟', falseAnswer1 = '袁尚', falseAnswer2 = '刘表'}
JuniorQu[311] = {ID = 311, examType = 2, question = '来给关羽送刘备亲笔信的是谁?', trueAnswerId = 1, trueAnswer = '陈震', falseAnswer1 = '田丰', falseAnswer2 = '审配'}
JuniorQu[312] = {ID = 312, examType = 2, question = '以下除何将外，均对关羽敬服?', trueAnswerId = 1, trueAnswer = '蔡阳', falseAnswer1 = '许褚', falseAnswer2 = '曹仁'}
JuniorQu[313] = {ID = 313, examType = 2, question = '廖化杀了何人，救了刘备二位夫人?', trueAnswerId = 1, trueAnswer = '杜远', falseAnswer1 = '钱昀', falseAnswer2 = '申诩'}
JuniorQu[314] = {ID = 314, examType = 2, question = '在荥阳时，以下何人见关羽灯下看书，失声道“真天人也”?', trueAnswerId = 1, trueAnswer = '胡班', falseAnswer1 = '胡华', falseAnswer2 = '胡植'}
JuniorQu[315] = {ID = 315, examType = 2, question = '关羽过五关时杀的第一将是谁?', trueAnswerId = 1, trueAnswer = '孔秀', falseAnswer1 = '韩福', falseAnswer2 = '秦琪'}
JuniorQu[316] = {ID = 316, examType = 2, question = '关羽过五关时，能够挡住关羽一回合的是何将?', trueAnswerId = 1, trueAnswer = '孟坦', falseAnswer1 = '孔秀', falseAnswer2 = '王植'}
JuniorQu[317] = {ID = 317, examType = 2, question = '关羽过五关时，汜水关镇国寺何僧与关羽是同乡?', trueAnswerId = 1, trueAnswer = '普净', falseAnswer1 = '净虚', falseAnswer2 = '虚空'}
JuniorQu[318] = {ID = 318, examType = 2, question = '关羽过五关时，被何人一箭射中左臂?', trueAnswerId = 1, trueAnswer = '韩福', falseAnswer1 = '孟坦', falseAnswer2 = '王植'}
JuniorQu[319] = {ID = 319, examType = 2, question = '关羽过五关时，何人是洛阳太守?', trueAnswerId = 1, trueAnswer = '韩福', falseAnswer1 = '卞喜', falseAnswer2 = '王植'}
JuniorQu[320] = {ID = 320, examType = 2, question = '蔡阳的外甥是谁?', trueAnswerId = 1, trueAnswer = '秦琪', falseAnswer1 = '卞喜', falseAnswer2 = '孟坦'}
JuniorQu[321] = {ID = 321, examType = 2, question = '以下谁的儿子去偷赤兔马?', trueAnswerId = 1, trueAnswer = '郭常', falseAnswer1 = '裴元绍', falseAnswer2 = '胡华'}
JuniorQu[322] = {ID = 322, examType = 2, question = '裴元绍以前是谁的部下?', trueAnswerId = 1, trueAnswer = '张角', falseAnswer1 = '张宝', falseAnswer2 = '张梁'}
JuniorQu[323] = {ID = 323, examType = 2, question = '周仓以前是谁的部下?', trueAnswerId = 1, trueAnswer = '张宝', falseAnswer1 = '张角', falseAnswer2 = '张梁'}
JuniorQu[324] = {ID = 324, examType = 2, question = '关平至少比关兴大几岁?', trueAnswerId = 1, trueAnswer = '十八', falseAnswer1 = '十', falseAnswer2 = '十四'}
JuniorQu[325] = {ID = 325, examType = 2, question = '刘备在袁绍面前将颜良和文丑比作什么?', trueAnswerId = 1, trueAnswer = '鹿', falseAnswer1 = '老虎', falseAnswer2 = '狼'}
JuniorQu[326] = {ID = 326, examType = 2, question = '孙乾只身到何处见刘备告诉关羽张飞的行踪?', trueAnswerId = 1, trueAnswer = '冀州', falseAnswer1 = '汝南', falseAnswer2 = '青州'}
JuniorQu[327] = {ID = 327, examType = 2, question = '裴元绍被谁所杀?', trueAnswerId = 1, trueAnswer = '赵云', falseAnswer1 = '张飞', falseAnswer2 = '关羽'}
JuniorQu[328] = {ID = 328, examType = 2, question = '赵云在何处正式投入到刘备手下?', trueAnswerId = 1, trueAnswer = '卧牛山', falseAnswer1 = '汝南', falseAnswer2 = '古城'}
JuniorQu[329] = {ID = 329, examType = 2, question = '以下何句正确?', trueAnswerId = 1, trueAnswer = '曹仁的女儿嫁给了孙匡', falseAnswer1 = '曹洪的女儿嫁给了孙策之弟孙匡', falseAnswer2 = '曹洪的女儿嫁给了孙权'}
JuniorQu[330] = {ID = 330, examType = 2, question = '孙策要求册封其为什么官职，被曹操拒绝了?', trueAnswerId = 1, trueAnswer = '司马', falseAnswer1 = '司空', falseAnswer2 = '司徒'}
JuniorQu[331] = {ID = 331, examType = 2, question = '孙策被谁的家客射中面门?', trueAnswerId = 1, trueAnswer = '许贡', falseAnswer1 = '陈震', falseAnswer2 = '胡师'}
JuniorQu[332] = {ID = 332, examType = 2, question = '是谁救下被箭射中的孙策?', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '韩当', falseAnswer2 = '黄盖'}
JuniorQu[333] = {ID = 333, examType = 2, question = '于吉是何方的道士?', trueAnswerId = 1, trueAnswer = '琅琊宫', falseAnswer1 = '三清观', falseAnswer2 = '紫虚观'}
JuniorQu[334] = {ID = 334, examType = 2, question = '孙策要斩于吉，谁最竭力阻止?', trueAnswerId = 1, trueAnswer = '张昭', falseAnswer1 = '张纮', falseAnswer2 = '顾雍'}
JuniorQu[335] = {ID = 335, examType = 2, question = '孙策死时几岁?', trueAnswerId = 1, trueAnswer = '二十六', falseAnswer1 = '二十九', falseAnswer2 = '三十二'}
JuniorQu[336] = {ID = 336, examType = 2, question = '孙权的胡须是什么颜色?', trueAnswerId = 1, trueAnswer = '紫色', falseAnswer1 = '黑色', falseAnswer2 = '白色'}
JuniorQu[337] = {ID = 337, examType = 2, question = '顾雍是谁的徒弟?', trueAnswerId = 1, trueAnswer = '蔡邕', falseAnswer1 = '荀攸', falseAnswer2 = '郭嘉'}
JuniorQu[338] = {ID = 338, examType = 2, question = '官渡之战，曹操命谁守许都?', trueAnswerId = 1, trueAnswer = '荀彧', falseAnswer1 = '荀攸', falseAnswer2 = '郭嘉'}
JuniorQu[339] = {ID = 339, examType = 2, question = '官渡之战，曹操命谁监造“霹雳车”?', trueAnswerId = 1, trueAnswer = '刘晔', falseAnswer1 = '荀攸', falseAnswer2 = '郭嘉'}
JuniorQu[340] = {ID = 340, examType = 2, question = '以下何人不是守乌巢的将领?', trueAnswerId = 1, trueAnswer = '吕威', falseAnswer1 = '淳于琼', falseAnswer2 = '赵睿'}
JuniorQu[341] = {ID = 341, examType = 2, question = '以下谁和曹操少年时就是朋友?', trueAnswerId = 1, trueAnswer = '许攸', falseAnswer1 = '田丰', falseAnswer2 = '郭图'}
JuniorQu[342] = {ID = 342, examType = 2, question = '守乌巢的大将淳于琼被捉后，以下何部位没有给曹操割去?', trueAnswerId = 1, trueAnswer = '头发', falseAnswer1 = '耳朵', falseAnswer2 = '鼻子'}
JuniorQu[343] = {ID = 343, examType = 2, question = '官渡之战，来救乌巢的大将蒋奇被谁所杀?', trueAnswerId = 1, trueAnswer = '张辽', falseAnswer1 = '徐晃', falseAnswer2 = '许褚'}
JuniorQu[344] = {ID = 344, examType = 2, question = '张郃、高览来降曹操，主要是谁在袁绍耳边打“小报告”?', trueAnswerId = 1, trueAnswer = '郭图', falseAnswer1 = '田丰', falseAnswer2 = '沮授'}
JuniorQu[345] = {ID = 345, examType = 2, question = '沮授为何会给曹操杀了?', trueAnswerId = 1, trueAnswer = '准备逃走', falseAnswer1 = '给袁绍通风报信', falseAnswer2 = '对曹操手下搞策反工作'}
JuniorQu[346] = {ID = 346, examType = 2, question = '以下何人打“小报告”，使得袁绍杀了牢中的田丰?', trueAnswerId = 1, trueAnswer = '逢纪', falseAnswer1 = '审配', falseAnswer2 = '辛评'}
JuniorQu[347] = {ID = 347, examType = 2, question = '以下哪两个是站在袁尚一边的?', trueAnswerId = 1, trueAnswer = '辛评,郭图', falseAnswer1 = '审配,逢纪', falseAnswer2 = '审配,辛评'}
JuniorQu[348] = {ID = 348, examType = 2, question = '以下哪两人是站在袁谭一边的?', trueAnswerId = 1, trueAnswer = '审配,逢纪', falseAnswer1 = '辛评,郭图', falseAnswer2 = '审配,辛评'}
JuniorQu[349] = {ID = 349, examType = 2, question = '袁尚射死的史涣是何人的部将?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '张辽', falseAnswer2 = '张郃'}
JuniorQu[350] = {ID = 350, examType = 2, question = '谁献的十面埋伏之计，使得曹军获得仓亭大胜?', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '荀彧', falseAnswer2 = '郭嘉'}
JuniorQu[351] = {ID = 351, examType = 2, question = '刘备被队伍冲散后，遇到曹军何将，准备自杀?', trueAnswerId = 1, trueAnswer = '高览', falseAnswer1 = '张辽', falseAnswer2 = '徐晃'}
JuniorQu[352] = {ID = 352, examType = 2, question = '帮袁绍起草遗嘱的是谁?', trueAnswerId = 1, trueAnswer = '审配', falseAnswer1 = '逢纪', falseAnswer2 = '郭图'}
JuniorQu[353] = {ID = 353, examType = 2, question = '审配和逢纪是通过什么方法决定谁去袁谭那里的?', trueAnswerId = 1, trueAnswer = '拈阄', falseAnswer1 = '赛马', falseAnswer2 = '猜拳'}
JuniorQu[354] = {ID = 354, examType = 2, question = '以下除谁外，均建议曹操不接受袁谭的投降?', trueAnswerId = 1, trueAnswer = '荀攸', falseAnswer1 = '程昱', falseAnswer2 = '吕虔'}
JuniorQu[355] = {ID = 355, examType = 2, question = '审配被谁生擒?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '张辽', falseAnswer2 = '张郃'}
JuniorQu[356] = {ID = 356, examType = 2, question = '许攸献计决何水以淹冀州?', trueAnswerId = 1, trueAnswer = '漳河', falseAnswer1 = '洮河', falseAnswer2 = '沐河'}
JuniorQu[357] = {ID = 357, examType = 2, question = '用枪挑袁尚印绶衣服的是谁?', trueAnswerId = 1, trueAnswer = '辛毗', falseAnswer1 = '于禁', falseAnswer2 = '乐进'}
JuniorQu[358] = {ID = 358, examType = 2, question = '审配临死前向何方而跪?', trueAnswerId = 1, trueAnswer = '北', falseAnswer1 = '东', falseAnswer2 = '南'}
JuniorQu[359] = {ID = 359, examType = 2, question = '曹丕破城后抢得甄氏时，曹几岁?', trueAnswerId = 1, trueAnswer = '十八', falseAnswer1 = '二十', falseAnswer2 = '二十二'}
JuniorQu[360] = {ID = 360, examType = 2, question = '甄氏原是何人的妻妾?', trueAnswerId = 1, trueAnswer = '袁熙', falseAnswer1 = '袁绍', falseAnswer2 = '袁谭'}
JuniorQu[361] = {ID = 361, examType = 2, question = '许攸居功自傲，被谁所杀?', trueAnswerId = 1, trueAnswer = '许褚', falseAnswer1 = '曹操', falseAnswer2 = '徐晃'}
JuniorQu[362] = {ID = 362, examType = 2, question = '辛评是如何而死的?', trueAnswerId = 1, trueAnswer = '气死的', falseAnswer1 = '被袁谭所杀', falseAnswer2 = '被曹操所杀'}
JuniorQu[363] = {ID = 363, examType = 2, question = '袁谭被谁所杀?', trueAnswerId = 1, trueAnswer = '曹洪', falseAnswer1 = '曹仁', falseAnswer2 = '夏侯惇'}
JuniorQu[364] = {ID = 364, examType = 2, question = '郭图被谁一箭射死?', trueAnswerId = 1, trueAnswer = '乐进', falseAnswer1 = '于禁', falseAnswer2 = '李典'}
JuniorQu[365] = {ID = 365, examType = 2, question = '高干被谁所杀?', trueAnswerId = 1, trueAnswer = '王琰', falseAnswer1 = '左贤王', falseAnswer2 = '张燕'}
JuniorQu[366] = {ID = 366, examType = 2, question = '郭嘉死时几岁?', trueAnswerId = 1, trueAnswer = '三十八', falseAnswer1 = '三十六', falseAnswer2 = '四十二'}
JuniorQu[367] = {ID = 367, examType = 2, question = '袁尚、袁熙俩人被谁献计所杀?', trueAnswerId = 1, trueAnswer = '公孙恭', falseAnswer1 = '郭嘉', falseAnswer2 = '公孙度'}
JuniorQu[368] = {ID = 368, examType = 2, question = '铜雀是在何城下掘出的?', trueAnswerId = 1, trueAnswer = '冀州', falseAnswer1 = '青州', falseAnswer2 = '幽州'}
JuniorQu[369] = {ID = 369, examType = 2, question = '挖出铜雀后，曹操问何人是什么征兆?', trueAnswerId = 1, trueAnswer = '荀攸', falseAnswer1 = '荀彧', falseAnswer2 = '程昱'}
JuniorQu[370] = {ID = 370, examType = 2, question = '是谁将张武杀死，为刘备夺来宝马的?', trueAnswerId = 1, trueAnswer = '赵云', falseAnswer1 = '张飞', falseAnswer2 = '关羽'}
JuniorQu[371] = {ID = 371, examType = 2, question = '以下谁劝刘备不要坐“的卢”马?', trueAnswerId = 1, trueAnswer = '伊籍', falseAnswer1 = '蒯越', falseAnswer2 = '孙乾'}
JuniorQu[372] = {ID = 372, examType = 2, question = '甘夫人生刘禅当夜有白鹤飞在屋上，高鸣了多少余声?', trueAnswerId = 1, trueAnswer = '四十', falseAnswer1 = '二十', falseAnswer2 = '六十'}
JuniorQu[373] = {ID = 373, examType = 2, question = '甘夫人怀孕前曾梦见什么?', trueAnswerId = 1, trueAnswer = '北斗', falseAnswer1 = '白鹤', falseAnswer2 = '神仙'}
JuniorQu[374] = {ID = 374, examType = 2, question = '刘备在何情况下见自己髀肉复生，又开始伤感起来了?', trueAnswerId = 1, trueAnswer = '上厕所时', falseAnswer1 = '睡觉前', falseAnswer2 = '洗澡时'}
JuniorQu[375] = {ID = 375, examType = 2, question = '刘备的“的卢”过了檀溪，后人谁写了首七言长诗?', trueAnswerId = 1, trueAnswer = '苏东坡', falseAnswer1 = '白居易', falseAnswer2 = '李白'}
JuniorQu[376] = {ID = 376, examType = 2, question = '来攻打新野的曹军首领何人?', trueAnswerId = 1, trueAnswer = '曹仁', falseAnswer1 = '曹洪', falseAnswer2 = '夏侯惇'}
JuniorQu[377] = {ID = 377, examType = 2, question = '庞统小司马徽几岁?', trueAnswerId = 1, trueAnswer = '五', falseAnswer1 = '一', falseAnswer2 = '三'}
JuniorQu[378] = {ID = 378, examType = 2, question = '水镜先生不愿出山的原因是什么?', trueAnswerId = 1, trueAnswer = '认为自有高人会来辅佐刘备', falseAnswer1 = '喜欢闲云野鹤的生活', falseAnswer2 = '自觉能力有限'}
JuniorQu[379] = {ID = 379, examType = 2, question = '降将吕旷被谁所杀?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '赵云', falseAnswer2 = '关羽'}
JuniorQu[380] = {ID = 380, examType = 2, question = '降将吕翔被谁所杀?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '赵云', falseAnswer2 = '关羽'}
JuniorQu[381] = {ID = 381, examType = 2, question = '单福识得“八门金锁阵”，告诉刘备从何门入则亡?', trueAnswerId = 1, trueAnswer = '杜门', falseAnswer1 = '景门', falseAnswer2 = '惊门'}
JuniorQu[382] = {ID = 382, examType = 2, question = '拜刘备为父的刘封与刘泌什么关系?', trueAnswerId = 1, trueAnswer = '刘封是刘泌的外甥', falseAnswer1 = '刘封是刘泌的弟弟', falseAnswer2 = '刘封是刘泌的侄子'}
JuniorQu[383] = {ID = 383, examType = 2, question = '谁向曹操说明“单福”就是徐庶?', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '荀彧', falseAnswer2 = '满宠'}
JuniorQu[384] = {ID = 384, examType = 2, question = '徐庶之母用什么打曹操?', trueAnswerId = 1, trueAnswer = '砚台', falseAnswer1 = '拐杖', falseAnswer2 = '手掌'}
JuniorQu[385] = {ID = 385, examType = 2, question = '孔明常自比何人?', trueAnswerId = 1, trueAnswer = '乐毅', falseAnswer1 = '姜子牙', falseAnswer2 = '张良'}
JuniorQu[386] = {ID = 386, examType = 2, question = '以下谁估计到徐母一见徐庶回来必自杀?', trueAnswerId = 1, trueAnswer = '司马徽', falseAnswer1 = '刘备', falseAnswer2 = '糜竺'}
JuniorQu[387] = {ID = 387, examType = 2, question = '刘备一顾草庐时，将谁误认为是孔明了?', trueAnswerId = 1, trueAnswer = '崔州平', falseAnswer1 = '石广元', falseAnswer2 = '孟公威'}
JuniorQu[388] = {ID = 388, examType = 2, question = '刘备二顾草庐时，见谁在那里唱“凤翱翔于千仞兮，非梧不栖”?', trueAnswerId = 1, trueAnswer = '诸葛均', falseAnswer1 = '童子', falseAnswer2 = '孟公威'}
JuniorQu[389] = {ID = 389, examType = 2, question = '凌操被甘宁一箭射死时，凌操之子凌统才几岁?', trueAnswerId = 1, trueAnswer = '十五', falseAnswer1 = '十二', falseAnswer2 = '十三'}
JuniorQu[390] = {ID = 390, examType = 2, question = '孙权弟孙翊之妻擅长什么?', trueAnswerId = 1, trueAnswer = '占卜', falseAnswer1 = '跳舞', falseAnswer2 = '作诗'}
JuniorQu[391] = {ID = 391, examType = 2, question = '孙翊被谁所杀?', trueAnswerId = 1, trueAnswer = '边洪', falseAnswer1 = '妫览', falseAnswer2 = '戴员'}
JuniorQu[392] = {ID = 392, examType = 2, question = '孔明给刘备看了西川多少州的地图，认为此地是建基业之处?', trueAnswerId = 1, trueAnswer = '五十四', falseAnswer1 = '二十四', falseAnswer2 = '三十六'}
JuniorQu[393] = {ID = 393, examType = 2, question = '东吴大将潘璋生擒以下何人?', trueAnswerId = 1, trueAnswer = '苏飞', falseAnswer1 = '陈就', falseAnswer2 = '邓龙'}
JuniorQu[394] = {ID = 394, examType = 2, question = '甘宁怕何人抢功，马上将黄祖射落并斩首?', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '凌统', falseAnswer2 = '黄盖'}
JuniorQu[395] = {ID = 395, examType = 2, question = '夏侯惇率兵十万来新野，张飞揶揄孔明是什么?', trueAnswerId = 1, trueAnswer = '水', falseAnswer1 = '鱼', falseAnswer2 = '凤'}
JuniorQu[396] = {ID = 396, examType = 2, question = '夏侯惇率兵十万来新野，火烧博望时正值什么季节?', trueAnswerId = 1, trueAnswer = '秋季', falseAnswer1 = '春季', falseAnswer2 = '夏季'}
JuniorQu[397] = {ID = 397, examType = 2, question = '以下何人最先警觉通往博望的道路狭窄两边有芦苇恐有火攻?', trueAnswerId = 1, trueAnswer = '李典', falseAnswer1 = '于禁', falseAnswer2 = '韩浩'}
JuniorQu[398] = {ID = 398, examType = 2, question = '“破巢之下，安有完卵乎”是以下何人所说?', trueAnswerId = 1, trueAnswer = '孔融儿子', falseAnswer1 = '孔融', falseAnswer2 = '孔融妻子'}
JuniorQu[399] = {ID = 399, examType = 2, question = '刘表死后，蔡夫人和蔡瑁立刘琮为荆州之主时，刘琮几岁?', trueAnswerId = 1, trueAnswer = '十四', falseAnswer1 = '十六', falseAnswer2 = '十八'}
JuniorQu[400] = {ID = 400, examType = 2, question = '来攻打新野的曹军发现刘封和糜芳的青红旗后，何将认为前面必有伏兵?', trueAnswerId = 1, trueAnswer = '许褚', falseAnswer1 = '曹仁', falseAnswer2 = '曹洪'}
JuniorQu[401] = {ID = 401, examType = 2, question = '以下何人负责放水，淹死了许多被火攻而突围出新野城的曹军?', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '张飞', falseAnswer2 = '赵云'}
JuniorQu[402] = {ID = 402, examType = 2, question = '魏延书中一亮相，就砍死了何城守将，准备让刘备进城?', trueAnswerId = 1, trueAnswer = '襄阳', falseAnswer1 = '樊城', falseAnswer2 = '荆州'}
JuniorQu[403] = {ID = 403, examType = 2, question = '蔡瑁在荆州的水兵共有多少人?', trueAnswerId = 1, trueAnswer = '八万', falseAnswer1 = '二万', falseAnswer2 = '四万'}
JuniorQu[404] = {ID = 404, examType = 2, question = '曹操派何人去将蔡夫人和刘琮追杀了?', trueAnswerId = 1, trueAnswer = '于禁', falseAnswer1 = '乐进', falseAnswer2 = '李典'}
JuniorQu[405] = {ID = 405, examType = 2, question = '文聘被谁骂了背主之贼而羞惭逃走了?', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '关羽', falseAnswer2 = '张飞'}
JuniorQu[406] = {ID = 406, examType = 2, question = '赵云救了被何人部将淳于导生擒的糜竺?', trueAnswerId = 1, trueAnswer = '曹仁', falseAnswer1 = '曹洪', falseAnswer2 = '夏侯渊'}
JuniorQu[407] = {ID = 407, examType = 2, question = '曹操自佩倚天剑，将青釭剑指定谁保管?', trueAnswerId = 1, trueAnswer = '夏侯恩', falseAnswer1 = '夏侯兴', falseAnswer2 = '夏侯申'}
JuniorQu[408] = {ID = 408, examType = 2, question = '见赵云在曹军中如入无人之境，以下谁让赵云留下姓名?', trueAnswerId = 1, trueAnswer = '曹洪', falseAnswer1 = '曹仁', falseAnswer2 = '夏侯渊'}
JuniorQu[409] = {ID = 409, examType = 2, question = '为救阿斗，赵云在长板坡杀死了曹营名将多少余员?', trueAnswerId = 1, trueAnswer = '五十', falseAnswer1 = '二十', falseAnswer2 = '三十'}
JuniorQu[410] = {ID = 410, examType = 2, question = '长坂坡张飞一声喝死了曹操手下哪员战将?', trueAnswerId = 1, trueAnswer = '夏侯杰', falseAnswer1 = '夏侯恩', falseAnswer2 = '夏侯兴'}
JuniorQu[411] = {ID = 411, examType = 2, question = '关羽从江夏借得多少军马拦住了曹操的追赶?', trueAnswerId = 1, trueAnswer = '一万', falseAnswer1 = '三千', falseAnswer2 = '五千'}
JuniorQu[412] = {ID = 412, examType = 2, question = '舌战群儒时，谁第一个向诸葛亮发难?', trueAnswerId = 1, trueAnswer = '张昭', falseAnswer1 = '虞翻', falseAnswer2 = '陆绩'}
JuniorQu[413] = {ID = 413, examType = 2, question = '舌战群儒时，谁认为诸葛亮在效仿苏秦、张仪?', trueAnswerId = 1, trueAnswer = '步骘', falseAnswer1 = '严畯', falseAnswer2 = '陆绩'}
JuniorQu[414] = {ID = 414, examType = 2, question = '舌战群儒，诸葛亮一举驳倒几个东吴谋士?', trueAnswerId = 1, trueAnswer = '七', falseAnswer1 = '五', falseAnswer2 = '九'}
JuniorQu[415] = {ID = 415, examType = 2, question = '舌战群儒时，东吴大将何人看不惯，站出来替诸葛亮说话?', trueAnswerId = 1, trueAnswer = '黄盖', falseAnswer1 = '程普', falseAnswer2 = '韩当'}
JuniorQu[416] = {ID = 416, examType = 2, question = '“内事不决问张昭，外事不决问周瑜”孙策的遗言谁搬出来帮孙权解决困难?', trueAnswerId = 1, trueAnswer = '吴国太', falseAnswer1 = '鲁肃', falseAnswer2 = '黄盖'}
JuniorQu[417] = {ID = 417, examType = 2, question = '孔明告诉周瑜《铜雀台赋》是何人所作?', trueAnswerId = 1, trueAnswer = '曹植', falseAnswer1 = '曹操', falseAnswer2 = '曹丕'}
JuniorQu[418] = {ID = 418, examType = 2, question = '以下何将年资比周瑜高，但位居其下，故托病不出?', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '黄盖', falseAnswer2 = '韩当'}
JuniorQu[419] = {ID = 419, examType = 2, question = '周瑜最早是听了何人之言后，动了欲杀诸葛亮之念?', trueAnswerId = 1, trueAnswer = '诸葛瑾', falseAnswer1 = '鲁肃', falseAnswer2 = '张昭'}
JuniorQu[420] = {ID = 420, examType = 2, question = '“群英会”上周瑜令何人执剑作监酒官?', trueAnswerId = 1, trueAnswer = '太史慈', falseAnswer1 = '甘宁', falseAnswer2 = '蒋钦'}
JuniorQu[421] = {ID = 421, examType = 2, question = '诸葛亮见刘备带了何人来东吴，才放下了心?', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '赵云', falseAnswer2 = '张飞'}
JuniorQu[422] = {ID = 422, examType = 2, question = '周瑜请诸葛亮几天内完成造箭十万枝?', trueAnswerId = 1, trueAnswer = '十', falseAnswer1 = '三', falseAnswer2 = '五'}
JuniorQu[423] = {ID = 423, examType = 2, question = '诸葛亮准备“草船借箭”，问鲁肃借了多少只船?', trueAnswerId = 1, trueAnswer = '二十', falseAnswer1 = '四十', falseAnswer2 = '八十'}
JuniorQu[424] = {ID = 424, examType = 2, question = '诸葛亮发动“草船借箭”是在几更?', trueAnswerId = 1, trueAnswer = '五更', falseAnswer1 = '二更', falseAnswer2 = '三更'}
JuniorQu[425] = {ID = 425, examType = 2, question = '在迷雾擂鼓声中，曹操调了多少名弓弩手射箭?', trueAnswerId = 1, trueAnswer = '三千', falseAnswer1 = '五百', falseAnswer2 = '一千'}
JuniorQu[426] = {ID = 426, examType = 2, question = '诸葛亮发动“草船借箭”的成果是每船上约有箭多少余支?', trueAnswerId = 1, trueAnswer = '五千', falseAnswer1 = '二千', falseAnswer2 = '三千'}
JuniorQu[427] = {ID = 427, examType = 2, question = '诸葛亮发动的“草船借箭”使曹操平白损失了多少余万支箭?', trueAnswerId = 1, trueAnswer = '十五', falseAnswer1 = '十', falseAnswer2 = '十二'}
JuniorQu[428] = {ID = 428, examType = 2, question = '是何人献计派蔡中两兄弟来诈降周瑜的?', trueAnswerId = 1, trueAnswer = '荀攸', falseAnswer1 = '刘晔', falseAnswer2 = '毛玠'}
JuniorQu[429] = {ID = 429, examType = 2, question = '为献苦肉计，老黄盖实际被打了多少棍?', trueAnswerId = 1, trueAnswer = '五十', falseAnswer1 = '三十', falseAnswer2 = '四十'}
JuniorQu[430] = {ID = 430, examType = 2, question = '以下何人来看望被打的黄盖，问其是否用的是“苦肉计”?', trueAnswerId = 1, trueAnswer = '阚泽', falseAnswer1 = '张昭', falseAnswer2 = '程普'}
JuniorQu[431] = {ID = 431, examType = 2, question = '阚泽与何人演双簧，让蔡中兄弟这两个糊涂虫又上了一次当?', trueAnswerId = 1, trueAnswer = '甘宁', falseAnswer1 = '凌统', falseAnswer2 = '周泰'}
JuniorQu[432] = {ID = 432, examType = 2, question = '以下何人救了被困于曹营中的徐庶?', trueAnswerId = 1, trueAnswer = '庞统', falseAnswer1 = '阚泽', falseAnswer2 = '蒋干'}
JuniorQu[433] = {ID = 433, examType = 2, question = '赤壁之战时曹操几岁?', trueAnswerId = 1, trueAnswer = '五十四', falseAnswer1 = '五十', falseAnswer2 = '五十二'}
JuniorQu[434] = {ID = 434, examType = 2, question = '宴长江曹操赋诗的诗名是什么?', trueAnswerId = 1, trueAnswer = '短歌行', falseAnswer1 = '观沧海', falseAnswer2 = '龟虽寿'}
JuniorQu[435] = {ID = 435, examType = 2, question = '宴长江曹操赋诗时，曹操因酒醉用什么杀了进良言的刘馥?', trueAnswerId = 1, trueAnswer = '槊', falseAnswer1 = '剑', falseAnswer2 = '戟'}
JuniorQu[436] = {ID = 436, examType = 2, question = '对庞统的连环计，哪个谋士还是率先向曹操提出其危险性?', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '荀攸', falseAnswer2 = '刘晔'}
JuniorQu[437] = {ID = 437, examType = 2, question = '为了求东南风，周瑜还是派了多少精壮军士去给孔明筑七星坛?', trueAnswerId = 1, trueAnswer = '五百', falseAnswer1 = '八百', falseAnswer2 = '一千'}
JuniorQu[438] = {ID = 438, examType = 2, question = '周瑜见东南风起，立即叫以下何人去把孔明杀了?', trueAnswerId = 1, trueAnswer = '丁奉', falseAnswer1 = '甘宁', falseAnswer2 = '周泰'}
JuniorQu[439] = {ID = 439, examType = 2, question = '关羽带了关平周仓及多少校刀手去守华容道?', trueAnswerId = 1, trueAnswer = '五百', falseAnswer1 = '一百', falseAnswer2 = '三百'}
JuniorQu[440] = {ID = 440, examType = 2, question = '何人去准备阻截黄盖的船只，被箭射中?', trueAnswerId = 1, trueAnswer = '文聘', falseAnswer1 = '于禁', falseAnswer2 = '毛玠'}
JuniorQu[441] = {ID = 441, examType = 2, question = '在离曹寨多远处，黄盖命令点上火船向对方冲去?', trueAnswerId = 1, trueAnswer = '二里', falseAnswer1 = '半里', falseAnswer2 = '一里'}
JuniorQu[442] = {ID = 442, examType = 2, question = '黄盖发起“火烧赤壁”是在几更天?', trueAnswerId = 1, trueAnswer = '三更', falseAnswer1 = '一更', falseAnswer2 = '二更'}
JuniorQu[443] = {ID = 443, examType = 2, question = '黄盖率领多少只火船向曹寨冲去?', trueAnswerId = 1, trueAnswer = '二十', falseAnswer1 = '十', falseAnswer2 = '四十'}
JuniorQu[444] = {ID = 444, examType = 2, question = '赤壁之战中救得曹操，将黄盖一箭射下水的是谁?', trueAnswerId = 1, trueAnswer = '张辽', falseAnswer1 = '于禁', falseAnswer2 = '张郃'}
JuniorQu[445] = {ID = 445, examType = 2, question = '赤壁之战中谁将中箭的黄盖身上的箭杆咬出?', trueAnswerId = 1, trueAnswer = '韩当', falseAnswer1 = '程普', falseAnswer2 = '甘宁'}
JuniorQu[446] = {ID = 446, examType = 2, question = '赤壁之战中曹军溃败后又遇赵云，以下哪两将力敌赵云，使曹操脱身?', trueAnswerId = 1, trueAnswer = '徐晃,张郃', falseAnswer1 = '张辽,许褚', falseAnswer2 = '于禁,李典'}
JuniorQu[447] = {ID = 447, examType = 2, question = '在华容道，曹操用何书上的故事来打动关羽?', trueAnswerId = 1, trueAnswer = '《春秋》', falseAnswer1 = '《左传》', falseAnswer2 = '《史记》'}
JuniorQu[448] = {ID = 448, examType = 2, question = '曹操脱离华容道时，只剩下多少骑?', trueAnswerId = 1, trueAnswer = '二十七', falseAnswer1 = '十六', falseAnswer2 = '二十一'}
JuniorQu[449] = {ID = 449, examType = 2, question = '以下何人请缨做先锋去夺曹仁把守的南郡?', trueAnswerId = 1, trueAnswer = '蒋钦', falseAnswer1 = '韩当', falseAnswer2 = '周泰'}
JuniorQu[450] = {ID = 450, examType = 2, question = '以下何将被困彝陵城?', trueAnswerId = 1, trueAnswer = '甘宁', falseAnswer1 = '韩当', falseAnswer2 = '蒋钦'}
JuniorQu[451] = {ID = 451, examType = 2, question = '周瑜亲自去解彝陵城被围之困，让谁暂代其职?', trueAnswerId = 1, trueAnswer = '凌统', falseAnswer1 = '韩当', falseAnswer2 = '甘宁'}
JuniorQu[452] = {ID = 452, examType = 2, question = '周瑜进南郡时被一箭射中何处?', trueAnswerId = 1, trueAnswer = '左肋', falseAnswer1 = '左臂', falseAnswer2 = '左肩'}
JuniorQu[453] = {ID = 453, examType = 2, question = '趁着周瑜部与曹仁部混乱之际，何人率部抢下了南郡?', trueAnswerId = 1, trueAnswer = '赵云', falseAnswer1 = '张飞', falseAnswer2 = '关羽'}
JuniorQu[454] = {ID = 454, examType = 2, question = '白眉马良建议刘备先取何处?', trueAnswerId = 1, trueAnswer = '零陵', falseAnswer1 = '桂阳', falseAnswer2 = '长沙'}
JuniorQu[455] = {ID = 455, examType = 2, question = '邢道荣料道不敌何人遂马上投降?', trueAnswerId = 1, trueAnswer = '赵云', falseAnswer1 = '关羽', falseAnswer2 = '张飞'}
JuniorQu[456] = {ID = 456, examType = 2, question = '刘度之子刘贤被谁生擒?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '关羽', falseAnswer2 = '赵云'}
JuniorQu[457] = {ID = 457, examType = 2, question = '除外哪项外，赵范与赵云“三同”?', trueAnswerId = 1, trueAnswer = '同单身', falseAnswer1 = '同姓', falseAnswer2 = '同乡'}
JuniorQu[458] = {ID = 458, examType = 2, question = '赵范倾国倾城的穿着缟服来见赵云的嫂嫂已经守寡几年了?', trueAnswerId = 1, trueAnswer = '三', falseAnswer1 = '半', falseAnswer2 = '一'}
JuniorQu[459] = {ID = 459, examType = 2, question = '赵范倾国倾城的嫂嫂姓什么?', trueAnswerId = 1, trueAnswer = '樊', falseAnswer1 = '贾', falseAnswer2 = '胡'}
JuniorQu[460] = {ID = 460, examType = 2, question = '赵范倾国倾城的嫂嫂再嫁要求三个条件，以下何者不是?', trueAnswerId = 1, trueAnswer = '要有官职', falseAnswer1 = '要文武双全', falseAnswer2 = '要相貌堂堂'}
JuniorQu[461] = {ID = 461, examType = 2, question = '以下何人率先劝赵云娶了赵范倾国倾城的嫂嫂?', trueAnswerId = 1, trueAnswer = '孔明', falseAnswer1 = '刘备', falseAnswer2 = '关羽'}
JuniorQu[462] = {ID = 462, examType = 2, question = '以下谁用箭射中金旋面门，献了武陵城?', trueAnswerId = 1, trueAnswer = '巩志', falseAnswer1 = '单勇', falseAnswer2 = '田钧'}
JuniorQu[463] = {ID = 463, examType = 2, question = '将韩玄杀了，献了长沙城的是谁?', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '黄忠', falseAnswer2 = '巩志'}
JuniorQu[464] = {ID = 464, examType = 2, question = '以下何人对乐进说只要杀了对面金盔的孙权就足可报八十三万大军之仇?', trueAnswerId = 1, trueAnswer = '李典', falseAnswer1 = '张辽', falseAnswer2 = '张郃'}
JuniorQu[465] = {ID = 465, examType = 2, question = '太史慈中计被乱箭射死时几岁?', trueAnswerId = 1, trueAnswer = '四十一', falseAnswer1 = '三十三', falseAnswer2 = '三十七'}
JuniorQu[466] = {ID = 466, examType = 2, question = '刘琦死后，鲁肃来兑现讨荆州，孔明说孙权是何地的小吏之子，现有六郡八十一州还不满足?', trueAnswerId = 1, trueAnswer = '钱塘', falseAnswer1 = '淮安', falseAnswer2 = '吴郡'}
JuniorQu[467] = {ID = 467, examType = 2, question = '甘夫人亡后，孙权依周瑜之计，派何人去刘备处提亲?', trueAnswerId = 1, trueAnswer = '吕范', falseAnswer1 = '鲁肃', falseAnswer2 = '张昭'}
JuniorQu[468] = {ID = 468, examType = 2, question = '得知东吴来提亲，孔明让谁去东吴确定亲事?', trueAnswerId = 1, trueAnswer = '孙乾', falseAnswer1 = '马良', falseAnswer2 = '伊籍'}
JuniorQu[469] = {ID = 469, examType = 2, question = '在甘露寺前，刘备用剑砍断的石头，现称作什么?', trueAnswerId = 1, trueAnswer = '恨石', falseAnswer1 = '断石', falseAnswer2 = '裂石'}
JuniorQu[470] = {ID = 470, examType = 2, question = '现甘露寺牌上的“天下第一江山”是何人所言?', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '吴国太', falseAnswer2 = '乔国老'}
JuniorQu[471] = {ID = 471, examType = 2, question = '“驻马坡”处是何人怕刘备说其不会骑马而到的地方?', trueAnswerId = 1, trueAnswer = '孙权', falseAnswer1 = '鲁肃', falseAnswer2 = '周瑜'}
JuniorQu[472] = {ID = 472, examType = 2, question = '成亲后的孙夫人是如何称呼刘备的?', trueAnswerId = 1, trueAnswer = '丈夫', falseAnswer1 = '主公', falseAnswer2 = '夫君'}
JuniorQu[473] = {ID = 473, examType = 2, question = '孙权派以下哪两将去将刘备及孙夫人杀了?', trueAnswerId = 1, trueAnswer = '蒋钦,周泰', falseAnswer1 = '徐盛,丁奉', falseAnswer2 = '陈武,潘璋'}
JuniorQu[474] = {ID = 474, examType = 2, question = '孙夫人先将阻拦的哪两将臭骂了一顿?', trueAnswerId = 1, trueAnswer = '徐盛,丁奉', falseAnswer1 = '陈武,潘璋', falseAnswer2 = '蒋钦,周泰'}
JuniorQu[475] = {ID = 475, examType = 2, question = '导致周瑜疮口迸裂的主要原因是什么?', trueAnswerId = 1, trueAnswer = '想到自己又一次败在孔明手下，无面目去见孙权', falseAnswer1 = '刘备和孙尚香居然能安然逃走', falseAnswer2 = '被关羽黄忠队伍冲杀折了许多将士'}
JuniorQu[476] = {ID = 476, examType = 2, question = '曹操大宴铜雀台时，令众将射箭娱乐，以下何人被曹操称为“此吾家千里驹也”?', trueAnswerId = 1, trueAnswer = '曹休', falseAnswer1 = '曹仁', falseAnswer2 = '曹洪'}
JuniorQu[477] = {ID = 477, examType = 2, question = '曹操大宴铜雀台时，以下哪两将为锦袍大打出手?', trueAnswerId = 1, trueAnswer = '徐晃,许褚', falseAnswer1 = '夏侯渊,乐进', falseAnswer2 = '张辽,曹仁'}
JuniorQu[478] = {ID = 478, examType = 2, question = '周瑜派华歆至曹操处使反间计，被何人最早识破?', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '荀攸', falseAnswer2 = '刘晔'}
JuniorQu[479] = {ID = 479, examType = 2, question = '周瑜派华歆至曹操处欲使反间计，曹操表奏后封了谁做江夏太守?', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '黄盖', falseAnswer2 = '韩当'}
JuniorQu[480] = {ID = 480, examType = 2, question = '周瑜被孔明气死时几岁?', trueAnswerId = 1, trueAnswer = '三十六', falseAnswer1 = '三十二', falseAnswer2 = '四十'}
JuniorQu[481] = {ID = 481, examType = 2, question = '周瑜死后，其灵柩葬于何处?', trueAnswerId = 1, trueAnswer = '芜湖', falseAnswer1 = '柴桑', falseAnswer2 = '南郡'}
JuniorQu[482] = {ID = 482, examType = 2, question = '马超梦见何凶兆，果断应验了其父被害?', trueAnswerId = 1, trueAnswer = '雪地遇虎', falseAnswer1 = '北星殒落', falseAnswer2 = '火烧营盘'}
JuniorQu[483] = {ID = 483, examType = 2, question = '马超为报父仇，大举进攻，失了潼关主要的责任在谁?', trueAnswerId = 1, trueAnswer = '曹洪', falseAnswer1 = '曹仁', falseAnswer2 = '徐晃'}
JuniorQu[484] = {ID = 484, examType = 2, question = '曹操被马超逼得脱袍割髯，主要是以下何人救得曹操?', trueAnswerId = 1, trueAnswer = '许褚', falseAnswer1 = '曹洪', falseAnswer2 = '徐晃'}
JuniorQu[485] = {ID = 485, examType = 2, question = '丁斐用了何计，救了曹操?', trueAnswerId = 1, trueAnswer = '调虎离山', falseAnswer1 = '声东击西', falseAnswer2 = '围魏救赵'}
JuniorQu[486] = {ID = 486, examType = 2, question = '告诉马超许褚绰号叫“虎痴”的是谁?', trueAnswerId = 1, trueAnswer = '韩遂', falseAnswer1 = '马岱', falseAnswer2 = '庞德'}
JuniorQu[487] = {ID = 487, examType = 2, question = '来给曹操献计筑土城的娄子伯隐居在何处?', trueAnswerId = 1, trueAnswer = '终南山', falseAnswer1 = '华山', falseAnswer2 = '五台山'}
JuniorQu[488] = {ID = 488, examType = 2, question = '许褚在曹营中被称为“虎侯”是由谁传播的?', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '马超', falseAnswer2 = '曹洪'}
JuniorQu[489] = {ID = 489, examType = 2, question = '许褚与马超恶斗到多少余回合，许褚将马超的枪杆拗断?', trueAnswerId = 1, trueAnswer = '二百三十', falseAnswer1 = '二百', falseAnswer2 = '三百'}
JuniorQu[490] = {ID = 490, examType = 2, question = '以下何人献上“反间计”，使马超和韩遂发生了内讧?', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '程昱', falseAnswer2 = '刘晔'}
JuniorQu[491] = {ID = 491, examType = 2, question = '以下何人被称为“米贼”?', trueAnswerId = 1, trueAnswer = '张衡', falseAnswer1 = '张陵', falseAnswer2 = '张鲁'}
JuniorQu[492] = {ID = 492, examType = 2, question = '张松最突出的地方在于何处?', trueAnswerId = 1, trueAnswer = '记性好', falseAnswer1 = '诗文好', falseAnswer2 = '有谋略'}
JuniorQu[493] = {ID = 493, examType = 2, question = '杨修让张松看的《孟德新书》共有多少篇?', trueAnswerId = 1, trueAnswer = '十三', falseAnswer1 = '九', falseAnswer2 = '十一'}
JuniorQu[494] = {ID = 494, examType = 2, question = '刘璋当时管辖多少州郡?', trueAnswerId = 1, trueAnswer = '四十一', falseAnswer1 = '二十一', falseAnswer2 = '三十一'}
JuniorQu[495] = {ID = 495, examType = 2, question = '以下何人进谏刘璋被扯落门牙两只?', trueAnswerId = 1, trueAnswer = '黄权', falseAnswer1 = '王累', falseAnswer2 = '李恢'}
JuniorQu[496] = {ID = 496, examType = 2, question = '以下何人用强索倒吊城门之上，进谏刘璋不成断索撞死于地?', trueAnswerId = 1, trueAnswer = '王累', falseAnswer1 = '李恢', falseAnswer2 = '黄权'}
JuniorQu[497] = {ID = 497, examType = 2, question = '众人不顾刘备反对，让何人登堂舞剑，伺机杀了刘璋?', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '刘封', falseAnswer2 = '廖化'}
JuniorQu[498] = {ID = 498, examType = 2, question = '来接孙夫人和阿斗的周善被谁所杀?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '赵云', falseAnswer2 = '周仓'}
JuniorQu[499] = {ID = 499, examType = 2, question = '孙夫人接到母病危消息后，马上动身带了几岁的阿斗一起回东吴?', trueAnswerId = 1, trueAnswer = '七', falseAnswer1 = '三', falseAnswer2 = '五'}
JuniorQu[500] = {ID = 500, examType = 2, question = '以下何人进言曹操应受魏公之位加九锡之尊?', trueAnswerId = 1, trueAnswer = '董昭', falseAnswer1 = '程昱', falseAnswer2 = '荀攸'}
JuniorQu[501] = {ID = 501, examType = 2, question = '荀彧不同意曹操为魏公加九锡，被赠服毒，享年几岁?', trueAnswerId = 1, trueAnswer = '五十', falseAnswer1 = '五十四', falseAnswer2 = '五十八'}
JuniorQu[502] = {ID = 502, examType = 2, question = '张松满门被斩是谁告的密?', trueAnswerId = 1, trueAnswer = '张肃', falseAnswer1 = '黄权', falseAnswer2 = '杨怀'}
JuniorQu[503] = {ID = 503, examType = 2, question = '最早预测出庞统会早死的是谁?', trueAnswerId = 1, trueAnswer = '以上均错', falseAnswer1 = '孔明', falseAnswer2 = '黄权'}
JuniorQu[504] = {ID = 504, examType = 2, question = '魏延贪功反中埋伏，是黄忠射杀何将救了魏延?', trueAnswerId = 1, trueAnswer = '邓贤', falseAnswer1 = '刘璝', falseAnswer2 = '冷苞'}
JuniorQu[505] = {ID = 505, examType = 2, question = '被黄忠救下的魏延为了将功赎罪，活捉了何将?', trueAnswerId = 1, trueAnswer = '冷苞', falseAnswer1 = '刘璝', falseAnswer2 = '张任'}
JuniorQu[506] = {ID = 506, examType = 2, question = '刘备梦到何事不祥，庞统却毫不在意?', trueAnswerId = 1, trueAnswer = '铁棒击臂', falseAnswer1 = '六月飞霜', falseAnswer2 = '猛虎驱赶'}
JuniorQu[507] = {ID = 507, examType = 2, question = '庞统在落凤坡被何部射死?', trueAnswerId = 1, trueAnswer = '张任', falseAnswer1 = '吴懿', falseAnswer2 = '吴兰'}
JuniorQu[508] = {ID = 508, examType = 2, question = '庞统死时几岁?', trueAnswerId = 1, trueAnswer = '三十六', falseAnswer1 = '二十八', falseAnswer2 = '三十二'}
JuniorQu[509] = {ID = 509, examType = 2, question = '庞统在落凤坡被射死时是几日?', trueAnswerId = 1, trueAnswer = '七月初七', falseAnswer1 = '五月初五', falseAnswer2 = '六月初六'}
JuniorQu[510] = {ID = 510, examType = 2, question = '张飞义释严颜后，在严颜的带领下顺利地通过了关隘多少处?', trueAnswerId = 1, trueAnswer = '四十五', falseAnswer1 = '十五', falseAnswer2 = '二十五'}
JuniorQu[511] = {ID = 511, examType = 2, question = '以下何人将张任活捉，为庞统报了仇?', trueAnswerId = 1, trueAnswer = '张飞', falseAnswer1 = '赵云', falseAnswer2 = '黄忠'}
JuniorQu[512] = {ID = 512, examType = 2, question = '马超反而将降将何人杀了?', trueAnswerId = 1, trueAnswer = '韦康', falseAnswer1 = '杨阜', falseAnswer2 = '梁宽'}
JuniorQu[513] = {ID = 513, examType = 2, question = '以下何人的妻子王氏十分刚烈，宁可牺牲儿子性命，也要丈夫去报仇?', trueAnswerId = 1, trueAnswer = '赵昂', falseAnswer1 = '杨阜', falseAnswer2 = '姜叙'}
JuniorQu[514] = {ID = 514, examType = 2, question = '以下何部将马超妻子杨氏从城上砍下，并将其三个幼子在城上剁死?', trueAnswerId = 1, trueAnswer = '梁宽', falseAnswer1 = '杨阜', falseAnswer2 = '姜叙'}
JuniorQu[515] = {ID = 515, examType = 2, question = '刘璋派黄权向张鲁求救，答应若肯相助，以多少州相谢?', trueAnswerId = 1, trueAnswer = '二十', falseAnswer1 = '五', falseAnswer2 = '十'}
JuniorQu[516] = {ID = 516, examType = 2, question = '以下何人的兄弟七人，皆被马超杀死?', trueAnswerId = 1, trueAnswer = '杨阜', falseAnswer1 = '赵昂', falseAnswer2 = '姜叙'}
JuniorQu[517] = {ID = 517, examType = 2, question = '以下何人凭口才说动马超投降刘备?', trueAnswerId = 1, trueAnswer = '李恢', falseAnswer1 = '李严', falseAnswer2 = '谯周'}
JuniorQu[518] = {ID = 518, examType = 2, question = '孔明使反间计，让谁散播马超欲自立为王的消息?', trueAnswerId = 1, trueAnswer = '杨松', falseAnswer1 = '费袆', falseAnswer2 = '蒋琬'}
JuniorQu[519] = {ID = 519, examType = 2, question = '魏延贪功，被何人射中左臂?', trueAnswerId = 1, trueAnswer = '马岱', falseAnswer1 = '马超', falseAnswer2 = '李严'}
JuniorQu[520] = {ID = 520, examType = 2, question = '西川平定后，刘备将刘璋送到何处定居?', trueAnswerId = 1, trueAnswer = '荆州', falseAnswer1 = '零陵', falseAnswer2 = '桂阳'}
JuniorQu[521] = {ID = 521, examType = 2, question = '益州既定，何人建议刘备将田宅分给百姓?', trueAnswerId = 1, trueAnswer = '赵云', falseAnswer1 = '蒋琬', falseAnswer2 = '孔明'}
JuniorQu[522] = {ID = 522, examType = 2, question = '关羽佯醉，挟持着谁安全脱离东吴?', trueAnswerId = 1, trueAnswer = '鲁肃', falseAnswer1 = '张昭', falseAnswer2 = '阚泽'}
JuniorQu[523] = {ID = 523, examType = 2, question = '以下何人反对曹操称“魏王”被曹操斥责后很快病死?', trueAnswerId = 1, trueAnswer = '荀攸', falseAnswer1 = '王粲', falseAnswer2 = '杜袭'}
JuniorQu[524] = {ID = 524, examType = 2, question = '穆顺将伏完的书信藏于何处，还是被曹操发现了?', trueAnswerId = 1, trueAnswer = '头发里', falseAnswer1 = '帽子里', falseAnswer2 = '锦袍里'}
JuniorQu[525] = {ID = 525, examType = 2, question = '以下谁将伏皇后的头发拖着去见曹操?', trueAnswerId = 1, trueAnswer = '华歆', falseAnswer1 = '许褚', falseAnswer2 = '和洽'}
JuniorQu[526] = {ID = 526, examType = 2, question = '许褚“坚持原则”，为保证曹操休息，即使以下谁来见曹操也不让进?', trueAnswerId = 1, trueAnswer = '曹仁', falseAnswer1 = '曹洪', falseAnswer2 = '曹休'}
JuniorQu[527] = {ID = 527, examType = 2, question = '曹军西征，被杨昂杨任两将劫寨后先锋部大败，哪两将受到曹操训斥?', trueAnswerId = 1, trueAnswer = '夏侯渊,张郃', falseAnswer1 = '夏侯惇,曹洪', falseAnswer2 = '曹仁,徐晃'}
JuniorQu[528] = {ID = 528, examType = 2, question = '孙权亲征，在何城下被再军射中麾盖?', trueAnswerId = 1, trueAnswer = '皖城', falseAnswer1 = '合淝', falseAnswer2 = '和州'}
JuniorQu[529] = {ID = 529, examType = 2, question = '为防甘宁和凌统两人在宴会上真打起来，谁出来调停?', trueAnswerId = 1, trueAnswer = '吕蒙', falseAnswer1 = '韩当', falseAnswer2 = '徐盛'}
JuniorQu[530] = {ID = 530, examType = 2, question = '曹操送来的木匣妙计中，指示让谁守合淝?', trueAnswerId = 1, trueAnswer = '乐进', falseAnswer1 = '张辽', falseAnswer2 = '李典'}
JuniorQu[531] = {ID = 531, examType = 2, question = '甘宁百骑劫曹营时，各人在盔上插了根什么翎为号?', trueAnswerId = 1, trueAnswer = '鹅翎', falseAnswer1 = '雁翎', falseAnswer2 = '鹊翎'}
JuniorQu[532] = {ID = 532, examType = 2, question = '凌统与甘宁和好，是因为甘宁射中何人救了凌统一命?', trueAnswerId = 1, trueAnswer = '乐进', falseAnswer1 = '李典', falseAnswer2 = '于禁'}
JuniorQu[533] = {ID = 533, examType = 2, question = '何人三番冲杀，才使得孙权脱出重围?', trueAnswerId = 1, trueAnswer = '周泰', falseAnswer1 = '甘宁', falseAnswer2 = '凌统'}
JuniorQu[534] = {ID = 534, examType = 2, question = '陈武因袍袖被树株所缠，故而为谁所杀?', trueAnswerId = 1, trueAnswer = '庞德', falseAnswer1 = '许褚', falseAnswer2 = '张辽'}
JuniorQu[535] = {ID = 535, examType = 2, question = '崔琰反对曹操为“魏王”，被曹操用何方法害死?', trueAnswerId = 1, trueAnswer = '杖杀', falseAnswer1 = '鸠杀', falseAnswer2 = '吊杀'}
JuniorQu[536] = {ID = 536, examType = 2, question = '曹操被册立“魏王”是在建安哪年?', trueAnswerId = 1, trueAnswer = '二十一', falseAnswer1 = '十五', falseAnswer2 = '十七'}
JuniorQu[537] = {ID = 537, examType = 2, question = '曹操的魏王宫建好后，令人到何处取柑子?', trueAnswerId = 1, trueAnswer = '温州', falseAnswer1 = '黄岩', falseAnswer2 = '湖州'}
JuniorQu[538] = {ID = 538, examType = 2, question = '左慈告诉曹操其在何处学道三十年，得天书三卷?', trueAnswerId = 1, trueAnswer = '峨嵋山', falseAnswer1 = '终南山', falseAnswer2 = '三清山'}
JuniorQu[539] = {ID = 539, examType = 2, question = '左慈告诉曹操惟有何处的鲈鱼有四腮?', trueAnswerId = 1, trueAnswer = '松江', falseAnswer1 = '汉江', falseAnswer2 = '怒江'}
JuniorQu[540] = {ID = 540, examType = 2, question = '左慈掷杯于空中，化成什么绕殿而飞?', trueAnswerId = 1, trueAnswer = '白鸠', falseAnswer1 = '白鹤', falseAnswer2 = '白天鹅'}
JuniorQu[541] = {ID = 541, examType = 2, question = '向曹操推荐管辂的是何人?', trueAnswerId = 1, trueAnswer = '许芝', falseAnswer1 = '贾诩', falseAnswer2 = '程昱'}
JuniorQu[542] = {ID = 542, examType = 2, question = '诸葛原将三物分置三盒，皆被管辂言中，除外以下何物?', trueAnswerId = 1, trueAnswer = '蝎子', falseAnswer1 = '燕卵', falseAnswer2 = '蜘蛛'}
JuniorQu[543] = {ID = 543, examType = 2, question = '管辂断言赵颜只能活几天?', trueAnswerId = 1, trueAnswer = '三', falseAnswer1 = '五', falseAnswer2 = '七'}
JuniorQu[544] = {ID = 544, examType = 2, question = '在管辂的帮助下，赵颜多活了几年?', trueAnswerId = 1, trueAnswer = '八十', falseAnswer1 = '二十', falseAnswer2 = '四十'}
JuniorQu[545] = {ID = 545, examType = 2, question = '管辂在曹操面前预言东吴有大将而亡，果然传来东吴何人的死讯?', trueAnswerId = 1, trueAnswer = '鲁肃', falseAnswer1 = '张昭', falseAnswer2 = '步骘'}
JuniorQu[546] = {ID = 546, examType = 2, question = '是以下何人之妻无意中走漏了“起义”的消息?', trueAnswerId = 1, trueAnswer = '金袆', falseAnswer1 = '耿纪', falseAnswer2 = '韦晃'}
JuniorQu[547] = {ID = 547, examType = 2, question = '以下何将放出话来“人皆怕张飞，吾视之如小儿耳”?', trueAnswerId = 1, trueAnswer = '张郃', falseAnswer1 = '庞德', falseAnswer2 = '许褚'}
JuniorQu[548] = {ID = 548, examType = 2, question = '以下何人镇守天荡山?', trueAnswerId = 1, trueAnswer = '夏侯德', falseAnswer1 = '夏侯惇', falseAnswer2 = '夏侯渊'}
JuniorQu[549] = {ID = 549, examType = 2, question = '夏侯德被谁所杀?', trueAnswerId = 1, trueAnswer = '严颜', falseAnswer1 = '黄忠', falseAnswer2 = '张飞'}
JuniorQu[550] = {ID = 550, examType = 2, question = '孔明对曹营中何将颇为赞赏?', trueAnswerId = 1, trueAnswer = '夏侯渊', falseAnswer1 = '徐晃', falseAnswer2 = '张辽'}
JuniorQu[551] = {ID = 551, examType = 2, question = '生擒庞德的是何人?', trueAnswerId = 1, trueAnswer = '周仓', falseAnswer1 = '关羽', falseAnswer2 = '关平'}
JuniorQu[552] = {ID = 552, examType = 2, question = '关羽所中的毒箭的毒药成份华陀判断是什么?', trueAnswerId = 1, trueAnswer = '乌头', falseAnswer1 = '砒霜', falseAnswer2 = '细辛'}
JuniorQu[553] = {ID = 553, examType = 2, question = '华陀为关羽刮骨疗伤时，关羽谈笑风生同谁下棋?', trueAnswerId = 1, trueAnswer = '马良', falseAnswer1 = '蒋琬', falseAnswer2 = '伊籍'}
JuniorQu[554] = {ID = 554, examType = 2, question = '东吴何人遂降了把守公安的傅士仁?', trueAnswerId = 1, trueAnswer = '虞翻', falseAnswer1 = '陆绩', falseAnswer2 = '薛琮'}
JuniorQu[555] = {ID = 555, examType = 2, question = '关羽后悔没听何人之言，导致傅士仁投降东吴?', trueAnswerId = 1, trueAnswer = '王甫', falseAnswer1 = '马良', falseAnswer2 = '伊籍'}
JuniorQu[556] = {ID = 556, examType = 2, question = '曹操称谁有“周亚夫之风”?', trueAnswerId = 1, trueAnswer = '徐晃', falseAnswer1 = '张辽', falseAnswer2 = '张郃'}
JuniorQu[557] = {ID = 557, examType = 2, question = '关羽被谁所获?', trueAnswerId = 1, trueAnswer = '马忠', falseAnswer1 = '潘璋', falseAnswer2 = '朱然'}
JuniorQu[558] = {ID = 558, examType = 2, question = '关羽被杀时几岁?', trueAnswerId = 1, trueAnswer = '五十八', falseAnswer1 = '五十六', falseAnswer2 = '六十一'}
JuniorQu[559] = {ID = 559, examType = 2, question = '是谁立刻识破东吴献关羽首级是为了嫁祸曹操?', trueAnswerId = 1, trueAnswer = '司马懿', falseAnswer1 = '贾诩', falseAnswer2 = '程昱'}
JuniorQu[560] = {ID = 560, examType = 2, question = '曹操用什么材质为关羽的首级配了躯体?', trueAnswerId = 1, trueAnswer = '沉香木', falseAnswer1 = '花梨木', falseAnswer2 = '杉木'}
JuniorQu[561] = {ID = 561, examType = 2, question = '良工苏越建议曹操用跃龙祠旁的何树作为建殿的材质?', trueAnswerId = 1, trueAnswer = '梨树', falseAnswer1 = '檀树', falseAnswer2 = '柏树'}
JuniorQu[562] = {ID = 562, examType = 2, question = '何人妻子将华陀的《青囊书》烧了?', trueAnswerId = 1, trueAnswer = '吴押狱', falseAnswer1 = '周押狱', falseAnswer2 = '郑押狱'}
JuniorQu[563] = {ID = 563, examType = 2, question = '曹操所梦的“三马同槽”中除马腾父子外，还有“一马”是指谁?', trueAnswerId = 1, trueAnswer = '司马师', falseAnswer1 = '马超', falseAnswer2 = '司马懿'}
JuniorQu[564] = {ID = 564, examType = 2, question = '曹操死时享年几岁?', trueAnswerId = 1, trueAnswer = '六十六', falseAnswer1 = '六十四', falseAnswer2 = '六十八'}
JuniorQu[565] = {ID = 565, examType = 2, question = '以下何人让于禁看画，将其活活气病而死?', trueAnswerId = 1, trueAnswer = '曹丕', falseAnswer1 = '曹操', falseAnswer2 = '司马懿'}
JuniorQu[566] = {ID = 566, examType = 2, question = '以下何人畏罪自杀?', trueAnswerId = 1, trueAnswer = '曹熊', falseAnswer1 = '曹彰', falseAnswer2 = '曹休'}
JuniorQu[567] = {ID = 567, examType = 2, question = '以下何人厉声告诉献帝已将其帝位废除，曹丕封其为“山阳公”?', trueAnswerId = 1, trueAnswer = '华歆', falseAnswer1 = '贾诩', falseAnswer2 = '王朗'}
JuniorQu[568] = {ID = 568, examType = 2, question = '刘备称帝后封刘永为何王?', trueAnswerId = 1, trueAnswer = '鲁王', falseAnswer1 = '川王', falseAnswer2 = '梁王'}
JuniorQu[569] = {ID = 569, examType = 2, question = '范疆、张达反客为主，先将张飞杀了，张飞死时几岁?', trueAnswerId = 1, trueAnswer = '五十五', falseAnswer1 = '五十三', falseAnswer2 = '五十七'}
JuniorQu[570] = {ID = 570, examType = 2, question = '以下何人给刘备写下谶语“白”字?', trueAnswerId = 1, trueAnswer = '李意', falseAnswer1 = '陈震', falseAnswer2 = '秦宓'}
JuniorQu[571] = {ID = 571, examType = 2, question = '关兴指名要射行雁中的第几只，果然一箭射中?', trueAnswerId = 1, trueAnswer = '三', falseAnswer1 = '一', falseAnswer2 = '五'}
JuniorQu[572] = {ID = 572, examType = 2, question = '吴将何人率先反对孙权为魏王受封，加九锡?', trueAnswerId = 1, trueAnswer = '徐盛', falseAnswer1 = '甘宁', falseAnswer2 = '凌统'}
JuniorQu[573] = {ID = 573, examType = 2, question = '张苞战马被谁射中翻下落地，是关兴及时赶到救了张?', trueAnswerId = 1, trueAnswer = '谭雄', falseAnswer1 = '李异', falseAnswer2 = '谢旌'}
JuniorQu[574] = {ID = 574, examType = 2, question = '老将黄忠被东吴乱箭射中后不治身亡，享年几岁?', trueAnswerId = 1, trueAnswer = '七十五', falseAnswer1 = '七十一', falseAnswer2 = '七十三'}
JuniorQu[575] = {ID = 575, examType = 2, question = '东吴何将见番王沙摩柯势大，不敢交锋，反被其射死?', trueAnswerId = 1, trueAnswer = '甘宁', falseAnswer1 = '史迹', falseAnswer2 = '潘璋'}
JuniorQu[576] = {ID = 576, examType = 2, question = '为了给关羽报仇，以下何人不是由蜀将领所杀的?', trueAnswerId = 1, trueAnswer = '马忠', falseAnswer1 = '潘璋', falseAnswer2 = '糜芳'}
JuniorQu[577] = {ID = 577, examType = 2, question = '东吴以下何人力挺陆逊，余均表示反对?', trueAnswerId = 1, trueAnswer = '阚泽', falseAnswer1 = '张昭', falseAnswer2 = '顾雍'}
JuniorQu[578] = {ID = 578, examType = 2, question = '蜀中何人认为陆逊才能不在周瑜之下?', trueAnswerId = 1, trueAnswer = '马良', falseAnswer1 = '伊籍', falseAnswer2 = '蒋琬'}
JuniorQu[579] = {ID = 579, examType = 2, question = '火烧连营七百里时，何将愿以死断后，力保刘备脱身?', trueAnswerId = 1, trueAnswer = '傅彤', falseAnswer1 = '冯习', falseAnswer2 = '吴班'}
JuniorQu[580] = {ID = 580, examType = 2, question = '番王沙摩柯在火烧连营时死于何人之手?', trueAnswerId = 1, trueAnswer = '周泰', falseAnswer1 = '凌统', falseAnswer2 = '徐盛'}
JuniorQu[581] = {ID = 581, examType = 2, question = '将陆逊领出孔明布下的“八阵图”的是谁?', trueAnswerId = 1, trueAnswer = '黄承彦', falseAnswer1 = '李意', falseAnswer2 = '诸葛瑾'}
JuniorQu[582] = {ID = 582, examType = 2, question = '刘备驾崩时几岁?', trueAnswerId = 1, trueAnswer = '六十三', falseAnswer1 = '六十一', falseAnswer2 = '六十五'}
JuniorQu[583] = {ID = 583, examType = 2, question = '曹丕分兵五路攻蜀，刘禅至丞相府见孔明正在干什么?', trueAnswerId = 1, trueAnswer = '观鱼', falseAnswer1 = '卧床', falseAnswer2 = '下棋'}
JuniorQu[584] = {ID = 584, examType = 2, question = '以下何人对张温的提问对答如流?', trueAnswerId = 1, trueAnswer = '秦宓', falseAnswer1 = '邓芝', falseAnswer2 = '马良'}
JuniorQu[585] = {ID = 585, examType = 2, question = '张辽被何人一箭射中腰部?', trueAnswerId = 1, trueAnswer = '丁奉', falseAnswer1 = '凌统', falseAnswer2 = '朱桓'}
JuniorQu[586] = {ID = 586, examType = 2, question = '孟获第一次是被谁生擒的?', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '赵云', falseAnswer2 = '王平'}
JuniorQu[587] = {ID = 587, examType = 2, question = '南蛮之地，溪中沐浴，男女自配，父母不禁，称作什么?', trueAnswerId = 1, trueAnswer = '学艺', falseAnswer1 = '学生', falseAnswer2 = '学而'}
JuniorQu[588] = {ID = 588, examType = 2, question = '祝融夫人飞刀甚是厉害，将谁击伤而擒之?', trueAnswerId = 1, trueAnswer = '张嶷', falseAnswer1 = '王平', falseAnswer2 = '马忠'}
JuniorQu[589] = {ID = 589, examType = 2, question = '孟获第七次是被谁生擒的?', trueAnswerId = 1, trueAnswer = '马岱', falseAnswer1 = '赵云', falseAnswer2 = '魏延'}
JuniorQu[590] = {ID = 590, examType = 2, question = '以下何人设计将甄氏害死，其父尝道“吾女乃女中之王也”?', trueAnswerId = 1, trueAnswer = '郭贵妃', falseAnswer1 = '潘贵妃', falseAnswer2 = '田贵妃'}
JuniorQu[591] = {ID = 591, examType = 2, question = '曹丕在位几年，于四十岁时驾崩?', trueAnswerId = 1, trueAnswer = '七', falseAnswer1 = '五', falseAnswer2 = '九'}
JuniorQu[592] = {ID = 592, examType = 2, question = '曹叡听从了何人的话，将司马懿削职回乡?', trueAnswerId = 1, trueAnswer = '华歆', falseAnswer1 = '王朗', falseAnswer2 = '曹休'}
JuniorQu[593] = {ID = 593, examType = 2, question = '孔明上《出师表》时出山已有几年了?', trueAnswerId = 1, trueAnswer = '二十一', falseAnswer1 = '十七', falseAnswer2 = '十九'}
JuniorQu[594] = {ID = 594, examType = 2, question = '孔明上完《出师表》后，老将赵云请缨出战，以下何人愿辅助赵?', trueAnswerId = 1, trueAnswer = '邓芝', falseAnswer1 = '秦宓', falseAnswer2 = '马良'}
JuniorQu[595] = {ID = 595, examType = 2, question = '以下何将被赵云生擒，余三将皆被赵所杀?', trueAnswerId = 1, trueAnswer = '韩瑶', falseAnswer1 = '韩瑛', falseAnswer2 = '韩琼'}
JuniorQu[596] = {ID = 596, examType = 2, question = '夏侯楙被何人生擒?', trueAnswerId = 1, trueAnswer = '王平', falseAnswer1 = '赵云', falseAnswer2 = '魏延'}
JuniorQu[597] = {ID = 597, examType = 2, question = '以下何人没有降孔明?', trueAnswerId = 1, trueAnswer = '马遵', falseAnswer1 = '姜维', falseAnswer2 = '梁绪'}
JuniorQu[598] = {ID = 598, examType = 2, question = '王朗在阵前被孔明活活气死时几岁?', trueAnswerId = 1, trueAnswer = '七十六', falseAnswer1 = '六十四', falseAnswer2 = '六十八'}
JuniorQu[599] = {ID = 599, examType = 2, question = '以下何人被魏延所杀?', trueAnswerId = 1, trueAnswer = '曹遵', falseAnswer1 = '越吉元帅', falseAnswer2 = '雅丹丞相'}
JuniorQu[600] = {ID = 600, examType = 2, question = '徐晃被孟达射中额头当晚即死，享年多少岁?', trueAnswerId = 1, trueAnswer = '五十九', falseAnswer1 = '五十三', falseAnswer2 = '五十五'}
JuniorQu[601] = {ID = 601, examType = 2, question = '空城计吓退了司马懿多少大军?', trueAnswerId = 1, trueAnswer = '十五万', falseAnswer1 = '五万', falseAnswer2 = '十万'}
JuniorQu[602] = {ID = 602, examType = 2, question = '空城计时，城中孔明军队只有多少人?', trueAnswerId = 1, trueAnswer = '二千五百', falseAnswer1 = '五百', falseAnswer2 = '一千五百'}
JuniorQu[603] = {ID = 603, examType = 2, question = '失了街亭的马谡被斩时几岁?', trueAnswerId = 1, trueAnswer = '三十九', falseAnswer1 = '三十三', falseAnswer2 = '三十五'}
JuniorQu[604] = {ID = 604, examType = 2, question = '魏将王双所使得大刀多重?', trueAnswerId = 1, trueAnswer = '六十斤', falseAnswer1 = '四十斤', falseAnswer2 = '五十斤'}
JuniorQu[605] = {ID = 605, examType = 2, question = '王双将蜀将何人打得口吐鲜血?', trueAnswerId = 1, trueAnswer = '张嶷', falseAnswer1 = '高翔', falseAnswer2 = '王平'}
JuniorQu[606] = {ID = 606, examType = 2, question = '大将王双被谁所杀?', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '赵云', falseAnswer2 = '关兴'}
JuniorQu[607] = {ID = 607, examType = 2, question = '知道何人死后，孔明从此卧病不愈?', trueAnswerId = 1, trueAnswer = '张苞', falseAnswer1 = '赵云', falseAnswer2 = '邓芝'}
JuniorQu[608] = {ID = 608, examType = 2, question = '以下何将不听劝阻，自行引兵致祁山下寨而受伏击?', trueAnswerId = 1, trueAnswer = '陈式', falseAnswer1 = '魏延', falseAnswer2 = '张嶷'}
JuniorQu[609] = {ID = 609, examType = 2, question = '魏将秦良被以下何人所杀?', trueAnswerId = 1, trueAnswer = '廖化', falseAnswer1 = '魏延', falseAnswer2 = '王平'}
JuniorQu[610] = {ID = 610, examType = 2, question = '将张郃一路引至埋伏处射死的是何将?', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '关兴', falseAnswer2 = '张翼'}
JuniorQu[611] = {ID = 611, examType = 2, question = '司马懿仿造孔明半月内也造了多少余只“木牛流马”?', trueAnswerId = 1, trueAnswer = '二千', falseAnswer1 = '五百', falseAnswer2 = '一千'}
JuniorQu[612] = {ID = 612, examType = 2, question = '孔明是在大约哪个节左右过世的?', trueAnswerId = 1, trueAnswer = '中秋', falseAnswer1 = '清明', falseAnswer2 = '端午'}
JuniorQu[613] = {ID = 613, examType = 2, question = '听到孔明过世的噩耗后，以下何人也大哭病死?', trueAnswerId = 1, trueAnswer = '李严', falseAnswer1 = '关兴', falseAnswer2 = '费祎'}
JuniorQu[614] = {ID = 614, examType = 2, question = '魏延被马岱偷袭所杀前，在阵前与谁对骂?', trueAnswerId = 1, trueAnswer = '姜维', falseAnswer1 = '杨仪', falseAnswer2 = '何平'}
JuniorQu[615] = {ID = 615, examType = 2, question = '曹叡托孤曹芳给司马懿时，曹芳几岁?', trueAnswerId = 1, trueAnswer = '八', falseAnswer1 = '四', falseAnswer2 = '六'}
JuniorQu[616] = {ID = 616, examType = 2, question = '司马懿将何人捉住，招出另有五人同谋篡逆?', trueAnswerId = 1, trueAnswer = '张当', falseAnswer1 = '何晏', falseAnswer2 = '李胜'}
JuniorQu[617] = {ID = 617, examType = 2, question = '左目下生黑瘤的是何人?', trueAnswerId = 1, trueAnswer = '司马师', falseAnswer1 = '司马懿', falseAnswer2 = '司马昭'}
JuniorQu[618] = {ID = 618, examType = 2, question = '孙权七十一岁亡，在位几年?', trueAnswerId = 1, trueAnswer = '二十四', falseAnswer1 = '十六', falseAnswer2 = '十八'}
JuniorQu[619] = {ID = 619, examType = 2, question = '司马师是如何而死的?', trueAnswerId = 1, trueAnswer = '眼睛迸出而死', falseAnswer1 = '中毒七窍流血而死', falseAnswer2 = '口吐鲜血而死'}
JuniorQu[620] = {ID = 620, examType = 2, question = '吴主孙亮看见谁无可奈何?', trueAnswerId = 1, trueAnswer = '孙綝', falseAnswer1 = '孙峻', falseAnswer2 = '孙楷'}
JuniorQu[621] = {ID = 621, examType = 2, question = '以下何人的坟墓被掘开，戮其尸首?', trueAnswerId = 1, trueAnswer = '孙峻', falseAnswer1 = '孙綝', falseAnswer2 = '孙楷'}
JuniorQu[622] = {ID = 622, examType = 2, question = '能识姜维的“长蛇卷地阵”将邓艾救出的是谁?', trueAnswerId = 1, trueAnswer = '司马望', falseAnswer1 = '钟会', falseAnswer2 = '郑伦'}
JuniorQu[623] = {ID = 623, examType = 2, question = '魏主曹髦被谁所杀?', trueAnswerId = 1, trueAnswer = '成济', falseAnswer1 = '司马昭', falseAnswer2 = '王含'}
JuniorQu[624] = {ID = 624, examType = 2, question = '夏侯霸死于何人之部?', trueAnswerId = 1, trueAnswer = '司马望', falseAnswer1 = '邓艾', falseAnswer2 = '钟会'}
JuniorQu[625] = {ID = 625, examType = 2, question = '“一日抒忠愤，千秋仰义名”是颂谁的诗?', trueAnswerId = 1, trueAnswer = '魏佥', falseAnswer1 = '蒋舒', falseAnswer2 = '张翼'}
JuniorQu[626] = {ID = 626, examType = 2, question = '“可怜巴蜀多名将，不及江油李氏贤”是赞何人的?', trueAnswerId = 1, trueAnswer = '马邈夫人', falseAnswer1 = '张翼夫人', falseAnswer2 = '蒋显夫人'}
JuniorQu[627] = {ID = 627, examType = 2, question = '刘禅七个儿子中谁反对投降?', trueAnswerId = 1, trueAnswer = '刘谌', falseAnswer1 = '刘瑶', falseAnswer2 = '刘琮'}
JuniorQu[628] = {ID = 628, examType = 2, question = '胆大如鸡卵的姜维自刎时几岁?', trueAnswerId = 1, trueAnswer = '五十九', falseAnswer1 = '五十三', falseAnswer2 = '五十五'}
JuniorQu[629] = {ID = 629, examType = 2, question = '“天下不如意事，十常八九”是何人常叹的话?', trueAnswerId = 1, trueAnswer = '羊祜', falseAnswer1 = '陆抗', falseAnswer2 = '司马炎'}
return JuniorQu