local PubLimit = {} 
PubLimit[1] = {}
PubLimit[2] = {}
PubLimit[3] = {}
PubLimit[4] = {}
PubLimit[5] = {}
PubLimit[6] = {}
PubLimit[7] = {}
PubLimit[8] = {}
PubLimit[9] = {}
PubLimit[10] = {}
PubLimit[11] = {}
PubLimit[12] = {}
PubLimit[13] = {}
PubLimit[14] = {}
PubLimit[15] = {}
PubLimit[16] = {}
PubLimit[17] = {}
PubLimit[18] = {}
PubLimit[19] = {}
PubLimit[20] = {}
PubLimit[21] = {}
PubLimit[22] = {}
PubLimit[23] = {}
PubLimit[24] = {}
PubLimit[25] = {}
PubLimit[26] = {}
return PubLimit