local Resource = {} 
Resource[512] = {ID = 512, name = '顶级单抽打折', icon = 1, transtype = 0, showControl = 0, info = '顶级单抽打折', quality = 1, attributeType = 0}
Resource[1] = {ID = 1, name = '血量', icon = 6, transtype = 0, showControl = 0, info = '兵种生命值上限', quality = 1, attributeType = 0}
Resource[2] = {ID = 2, name = '血量', icon = 6, transtype = 0, showControl = 0, info = '兵种生命值', quality = 1, attributeType = 0}
Resource[3] = {ID = 3, name = '攻击', icon = 5, transtype = 0, showControl = 0, info = '兵种攻击力', quality = 1, attributeType = 0}
Resource[4] = {ID = 4, name = '命中', icon = 8, transtype = 0, showControl = 0, info = '兵种命中率', quality = 1, attributeType = 2}
Resource[5] = {ID = 5, name = '闪避', icon = 9, transtype = 0, showControl = 0, info = '兵种闪避', quality = 1, attributeType = 2}
Resource[6] = {ID = 6, name = '暴击', icon = 10, transtype = 0, showControl = 0, info = '兵种暴击', quality = 1, attributeType = 2}
Resource[7] = {ID = 7, name = '抗暴', icon = 11, transtype = 0, showControl = 0, info = '兵种抗暴', quality = 1, attributeType = 2}
Resource[8] = {ID = 8, name = '穿刺', icon = 12, transtype = 0, showControl = 0, info = '兵种穿刺', quality = 1, attributeType = 1}
Resource[9] = {ID = 9, name = '防护', icon = 13, transtype = 0, showControl = 0, info = '兵种防护', quality = 1, attributeType = 1}
Resource[10] = {ID = 10, name = '先手值', icon = 14, transtype = 0, showControl = 0, info = '兵种先手值', quality = 1, attributeType = 0}
Resource[11] = {ID = 11, name = '血量', icon = 6, transtype = 0, showControl = 0, info = '兵种血量', quality = 1, attributeType = 0}
Resource[12] = {ID = 12, name = '攻击', icon = 5, transtype = 0, showControl = 0, info = '兵种攻击', quality = 1, attributeType = 0}
Resource[13] = {ID = 13, name = '刀兵血量上限百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种刀兵血量上限百分比', quality = 1, attributeType = 0}
Resource[14] = {ID = 14, name = '刀兵攻击百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种刀兵攻击百分比', quality = 1, attributeType = 0}
Resource[15] = {ID = 15, name = '骑兵血量上限百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种骑兵血量上限百分比', quality = 1, attributeType = 0}
Resource[16] = {ID = 16, name = '骑兵攻击百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种骑兵攻击百分比', quality = 1, attributeType = 0}
Resource[17] = {ID = 17, name = '枪兵血量上限百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种枪兵血量上限百分比', quality = 1, attributeType = 0}
Resource[18] = {ID = 18, name = '枪兵攻击百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种枪兵攻击百分比', quality = 1, attributeType = 0}
Resource[19] = {ID = 19, name = '弓兵血量上限百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种弓兵血量上限百分比', quality = 1, attributeType = 0}
Resource[20] = {ID = 20, name = '弓兵攻击百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种弓兵攻击百分比', quality = 1, attributeType = 0}
Resource[21] = {ID = 21, name = '辎重', icon = 7, transtype = 1, showControl = 0, info = '兵种辎重', quality = 1, attributeType = 0}
Resource[22] = {ID = 22, name = '辎重百分比', icon = 7, transtype = 0, showControl = 0, info = '兵种辎重百分比', quality = 1, attributeType = 0}
Resource[23] = {ID = 23, name = '行军速度加成比', icon = 1, transtype = 0, showControl = 0, info = '兵种行军速度加成比', quality = 1, attributeType = 0}
Resource[24] = {ID = 24, name = 'PVE伤害加成', icon = 1, transtype = 0, showControl = 0, info = '兵种PVE伤害加成', quality = 1, attributeType = 0}
Resource[25] = {ID = 25, name = 'PVE伤害减免', icon = 1, transtype = 0, showControl = 0, info = '兵种PVE伤害减免', quality = 1, attributeType = 0}
Resource[26] = {ID = 26, name = 'PVP伤害加成', icon = 1, transtype = 0, showControl = 0, info = '兵种PVP伤害加成', quality = 1, attributeType = 0}
Resource[27] = {ID = 27, name = 'PVP伤害减免', icon = 1, transtype = 0, showControl = 0, info = '兵种PVP伤害减免', quality = 1, attributeType = 0}
Resource[28] = {ID = 28, name = '伤害加成', icon = 1, transtype = 0, showControl = 0, info = '兵种伤害加成', quality = 1, attributeType = 0}
Resource[29] = {ID = 29, name = '伤害减免', icon = 1, transtype = 0, showControl = 0, info = '兵种伤害减免', quality = 1, attributeType = 0}
Resource[30] = {ID = 30, name = '最大战力', icon = 1, transtype = 1, showControl = 0, info = '队伍最大战力', quality = 1, attributeType = 0}
Resource[31] = {ID = 31, name = '世界战斗伤害加成', icon = 1, transtype = 0, showControl = 0, info = '世界战斗伤害加成', quality = 1, attributeType = 0}
Resource[32] = {ID = 32, name = '世界战斗伤害减免', icon = 1, transtype = 0, showControl = 0, info = '世界战斗伤害减免', quality = 1, attributeType = 0}
Resource[33] = {ID = 33, name = '爆伤', icon = 33, transtype = 0, showControl = 0, info = '兵种爆伤', quality = 1, attributeType = 1}
Resource[34] = {ID = 34, name = '韧性', icon = 34, transtype = 0, showControl = 0, info = '兵种韧性', quality = 1, attributeType = 1}
Resource[35] = {ID = 35, name = '先手百分比', icon = 1, transtype = 0, showControl = 0, info = '兵种先手百分比', quality = 1, attributeType = 0}
Resource[36] = {ID = 36, name = '血量', icon = 6, transtype = 0, showControl = 0, info = '兵种血量', quality = 1, attributeType = 0}
Resource[37] = {ID = 37, name = '攻击', icon = 5, transtype = 0, showControl = 0, info = '兵种攻击', quality = 1, attributeType = 0}
Resource[38] = {ID = 38, name = '回血触发概率', icon = 1, transtype = 0, showControl = 0, info = '回血触发概率', quality = 1, attributeType = 0}
Resource[39] = {ID = 39, name = '眩晕触发概率', icon = 1, transtype = 0, showControl = 0, info = '眩晕触发概率', quality = 1, attributeType = 0}
Resource[40] = {ID = 40, name = '反弹触发概率', icon = 1, transtype = 0, showControl = 0, info = '反弹触发概率', quality = 1, attributeType = 0}
Resource[41] = {ID = 41, name = '驱散触发概率', icon = 1, transtype = 0, showControl = 0, info = '驱散触发概率', quality = 1, attributeType = 0}
Resource[42] = {ID = 42, name = '燃烧触发概率', icon = 1, transtype = 0, showControl = 0, info = '燃烧触发概率', quality = 1, attributeType = 0}
Resource[43] = {ID = 43, name = '减免触发概率', icon = 1, transtype = 0, showControl = 0, info = '减免触发概率', quality = 1, attributeType = 0}
Resource[44] = {ID = 44, name = '伤害', icon = 44, transtype = 0, showControl = 0, info = '每次攻击额外增加的伤害值，不受到百分比影响', quality = 1, attributeType = 0}
Resource[45] = {ID = 45, name = '护甲', icon = 45, transtype = 0, showControl = 0, info = '每次受击额外减少的伤害值，不受到百分比影响', quality = 1, attributeType = 0}
Resource[46] = {ID = 46, name = '后制', icon = 1, transtype = 0, showControl = 0, info = '敌方先手值于我方先手值之差大于我方后制值，敌方先手值效果才会生效', quality = 1, attributeType = 0}
Resource[605] = {ID = 605, name = '粮食额外产量', icon = 1, transtype = 1, showControl = 0, info = '粮食额外产量', quality = 1, attributeType = 0}
Resource[515] = {ID = 515, name = '招募将领花费宝石优惠', icon = 1, transtype = 0, showControl = 0, info = '招募将领花费宝石优惠', quality = 1, attributeType = 0}
Resource[51] = {ID = 51, name = '银币容量', icon = 1, transtype = 1, showControl = 0, info = '银币容量', quality = 1, attributeType = 0}
Resource[52] = {ID = 52, name = '铁锭矿容量', icon = 1, transtype = 1, showControl = 0, info = '铁锭矿容量', quality = 1, attributeType = 0}
Resource[53] = {ID = 53, name = '木材容量', icon = 1, transtype = 1, showControl = 0, info = '木材容量', quality = 1, attributeType = 0}
Resource[54] = {ID = 54, name = '石料容量', icon = 1, transtype = 1, showControl = 0, info = '石料容量', quality = 1, attributeType = 0}
Resource[55] = {ID = 55, name = '粮食容量', icon = 1, transtype = 1, showControl = 0, info = '粮食容量', quality = 1, attributeType = 0}
Resource[56] = {ID = 56, name = '仓库容量', icon = 1, transtype = 0, showControl = 0, info = '仓库容量', quality = 1, attributeType = 0}
Resource[57] = {ID = 57, name = '银币产量', icon = 1, transtype = 1, showControl = 0, info = '银币产量', quality = 1, attributeType = 0}
Resource[58] = {ID = 58, name = '铁锭矿产量', icon = 1, transtype = 1, showControl = 0, info = '铁锭矿产量', quality = 1, attributeType = 0}
Resource[59] = {ID = 59, name = '木材产量', icon = 1, transtype = 1, showControl = 0, info = '木材产量', quality = 1, attributeType = 0}
Resource[60] = {ID = 60, name = '石料产量', icon = 1, transtype = 1, showControl = 0, info = '石料产量', quality = 1, attributeType = 0}
Resource[61] = {ID = 61, name = '粮食产量', icon = 1, transtype = 1, showControl = 0, info = '粮食产量', quality = 1, attributeType = 0}
Resource[62] = {ID = 62, name = '仓库保护量', icon = 1, transtype = 0, showControl = 0, info = '仓库保护量', quality = 1, attributeType = 0}
Resource[63] = {ID = 63, name = '银币容量百分比', icon = 1, transtype = 0, showControl = 0, info = '银币容量百分比', quality = 1, attributeType = 0}
Resource[64] = {ID = 64, name = '铁锭矿容量百分比', icon = 1, transtype = 0, showControl = 0, info = '铁锭矿容量百分比', quality = 1, attributeType = 0}
Resource[65] = {ID = 65, name = '木材容量百分比', icon = 1, transtype = 0, showControl = 0, info = '木材容量百分比', quality = 1, attributeType = 0}
Resource[66] = {ID = 66, name = '石料容量百分比', icon = 1, transtype = 0, showControl = 0, info = '石料容量百分比', quality = 1, attributeType = 0}
Resource[67] = {ID = 67, name = '粮食容量百分比', icon = 1, transtype = 0, showControl = 0, info = '粮食容量百分比', quality = 1, attributeType = 0}
Resource[68] = {ID = 68, name = '仓库容量百分比', icon = 1, transtype = 0, showControl = 0, info = '仓库容量百分比', quality = 1, attributeType = 0}
Resource[69] = {ID = 69, name = '银币产量百分比', icon = 1, transtype = 0, showControl = 0, info = '银币产量百分比', quality = 1, attributeType = 0}
Resource[70] = {ID = 70, name = '铁锭矿产量百分比', icon = 1, transtype = 0, showControl = 0, info = '铁锭矿产量百分比', quality = 1, attributeType = 0}
Resource[71] = {ID = 71, name = '木材产量百分比', icon = 1, transtype = 0, showControl = 0, info = '木材产量百分比', quality = 1, attributeType = 0}
Resource[72] = {ID = 72, name = '石料产量百分比', icon = 1, transtype = 0, showControl = 0, info = '石料产量百分比', quality = 1, attributeType = 0}
Resource[73] = {ID = 73, name = '粮食产量百分比', icon = 1, transtype = 0, showControl = 0, info = '粮食产量百分比', quality = 1, attributeType = 0}
Resource[74] = {ID = 74, name = '仓库保护量百分比', icon = 1, transtype = 0, showControl = 0, info = '仓库保护量百分比', quality = 1, attributeType = 0}
Resource[75] = {ID = 75, name = '战斗经验加成比', icon = 1, transtype = 0, showControl = 0, info = '战斗经验加成比', quality = 1, attributeType = 0}
Resource[76] = {ID = 76, name = '建筑速度加成比', icon = 1, transtype = 0, showControl = 0, info = '建筑速度加成比', quality = 1, attributeType = 0}
Resource[77] = {ID = 77, name = '科技研发速度加成比', icon = 1, transtype = 0, showControl = 0, info = '科技研发速度加成比', quality = 1, attributeType = 0}
Resource[78] = {ID = 78, name = '全资源产量', icon = 1, transtype = 0, showControl = 0, info = '全资源产量', quality = 1, attributeType = 0}
Resource[79] = {ID = 79, name = '全资源产量百分比', icon = 1, transtype = 0, showControl = 0, info = '全资源产量百分比', quality = 1, attributeType = 0}
Resource[80] = {ID = 80, name = '建筑时间减免', icon = 1, transtype = 0, showControl = 0, info = '建筑时间减免', quality = 1, attributeType = 0}
Resource[81] = {ID = 81, name = '繁荣度损失加成', icon = 1, transtype = 0, showControl = 0, info = '繁荣度损失加成', quality = 1, attributeType = 0}
Resource[82] = {ID = 82, name = '兵种生成速度加成比', icon = 1, transtype = 0, showControl = 0, info = '兵种生成速度加成比', quality = 1, attributeType = 0}
Resource[83] = {ID = 83, name = '兵种改造速度加成比', icon = 1, transtype = 0, showControl = 0, info = '兵种改造速度加成比', quality = 1, attributeType = 0}
Resource[84] = {ID = 84, name = '统帅升级成功率加成', icon = 1, transtype = 0, showControl = 0, info = '统帅升级成功率加成', quality = 1, attributeType = 0}
Resource[85] = {ID = 85, name = '关卡经验加成比', icon = 1, transtype = 0, showControl = 0, info = '关卡经验加成比', quality = 1, attributeType = 0}
Resource[86] = {ID = 86, name = '野外资源经验加成比', icon = 1, transtype = 0, showControl = 0, info = '野外资源经验加成比', quality = 1, attributeType = 0}
Resource[87] = {ID = 87, name = '繁荣度损失固定值', icon = 1, transtype = 0, showControl = 0, info = '繁荣度损失固定值', quality = 1, attributeType = 0}
Resource[88] = {ID = 88, name = '野外资源采集速度加成', icon = 1, transtype = 0, showControl = 0, info = '野外资源采集速度加成', quality = 1, attributeType = 0}
Resource[89] = {ID = 89, name = '外观临时建筑位', icon = 1, transtype = 0, showControl = 0, info = '可用来升级建筑的临时队列并改\n变城池外观', quality = 1, attributeType = 0}
Resource[90] = {ID = 90, name = '城池外观', icon = 1, transtype = 0, showControl = 0, info = '改变城池外观', quality = 1, attributeType = 0}
Resource[91] = {ID = 91, name = '不被攻击和侦查', icon = 1, transtype = 0, showControl = 0, info = '不被攻击和侦查', quality = 1, attributeType = 0}
Resource[604] = {ID = 604, name = '石料额外产量', icon = 1, transtype = 1, showControl = 0, info = '石料额外产量', quality = 1, attributeType = 0}
Resource[93] = {ID = 93, name = '临时建筑位', icon = 1, transtype = 0, showControl = 0, info = '可用来升级建筑的临时队列', quality = 1, attributeType = 0}
Resource[94] = {ID = 94, name = '战功经验加成', icon = 1, transtype = 0, showControl = 0, info = '战功任务获得的经验加成', quality = 1, attributeType = 0}
Resource[95] = {ID = 95, name = '矿点保护', icon = 1, transtype = 0, showControl = 0, info = '保护玩家的矿点', quality = 1, attributeType = 0}
Resource[96] = {ID = 96, name = '矿点民忠值加成', icon = 1, transtype = 0, showControl = 0, info = '增加玩家的矿点民忠值', quality = 1, attributeType = 0}
Resource[97] = {ID = 97, name = '禁止迁城', icon = 1, transtype = 0, showControl = 0, info = '主城无法迁城', quality = 1, attributeType = 0}
Resource[98] = {ID = 98, name = '禁止派遣部队', icon = 1, transtype = 0, showControl = 0, info = '世界无法派遣部队', quality = 1, attributeType = 0}
Resource[101] = {ID = 101, name = '经验', icon = 101, transtype = 2, showControl = 1, info = '增加主公经验，提升主公等级', quality = 1, attributeType = 0}
Resource[102] = {ID = 102, name = '军令', icon = 102, transtype = 0, showControl = 1, info = '军令，用于部队出征和战役消耗', quality = 1, attributeType = 0}
Resource[103] = {ID = 103, name = 'vip经验', icon = 103, transtype = 0, showControl = 1, info = '增加vip经验，提升vip等级', quality = 1, attributeType = 0}
Resource[104] = {ID = 104, name = '声望', icon = 104, transtype = 0, showControl = 1, info = '增加声望经验，提升主公的声望\n等级', quality = 1, attributeType = 0}
Resource[105] = {ID = 105, name = '荣誉', icon = 105, transtype = 0, showControl = 0, info = '增加荣誉经验，提升主公的荣誉\n等级', quality = 1, attributeType = 0}
Resource[106] = {ID = 106, name = '带兵量', icon = 106, transtype = 0, showControl = 0, info = '增加主公的队伍带兵数量', quality = 1, attributeType = 0}
Resource[107] = {ID = 107, name = '繁荣度', icon = 107, transtype = 0, showControl = 0, info = '增加繁荣经验，提升主公繁荣等\n级', quality = 1, attributeType = 0}
Resource[108] = {ID = 108, name = '竞技场积分', icon = 108, transtype = 0, showControl = 1, info = '增加主公的演武场积分，可用于\n演武场商店兑换', quality = 1, attributeType = 0}
Resource[109] = {ID = 109, name = '服务器ID', icon = 109, transtype = 0, showControl = 0, info = '服务器ID', quality = 1, attributeType = 0}
Resource[110] = {ID = 110, name = '等级', icon = 110, transtype = 0, showControl = 0, info = '主公等级', quality = 1, attributeType = 0}
Resource[111] = {ID = 111, name = '性别', icon = 111, transtype = 0, showControl = 0, info = '主公性别', quality = 1, attributeType = 0}
Resource[112] = {ID = 112, name = '头像', icon = 112, transtype = 0, showControl = 0, info = '主公头像', quality = 1, attributeType = 0}
Resource[113] = {ID = 113, name = '军衔', icon = 113, transtype = 0, showControl = 0, info = '主公军械等级', quality = 1, attributeType = 0}
Resource[114] = {ID = 114, name = 'vip等级', icon = 114, transtype = 0, showControl = 0, info = '主公vip等级', quality = 1, attributeType = 0}
Resource[115] = {ID = 115, name = '繁荣等级', icon = 115, transtype = 0, showControl = 0, info = '主公繁荣等级', quality = 1, attributeType = 0}
Resource[116] = {ID = 116, name = '繁荣度上限', icon = 116, transtype = 0, showControl = 0, info = '主公繁荣度上限', quality = 1, attributeType = 0}
Resource[117] = {ID = 117, name = '统率等级', icon = 117, transtype = 0, showControl = 0, info = '主公统率等级', quality = 1, attributeType = 0}
Resource[118] = {ID = 118, name = '声望等级', icon = 118, transtype = 0, showControl = 0, info = '主公声望等级', quality = 1, attributeType = 0}
Resource[119] = {ID = 119, name = '装备仓库容量', icon = 119, transtype = 0, showControl = 0, info = '装备的仓库容量', quality = 1, attributeType = 0}
Resource[120] = {ID = 120, name = '建筑位', icon = 120, transtype = 0, showControl = 0, info = '可用来升级建筑的队列', quality = 1, attributeType = 0}
Resource[121] = {ID = 121, name = '讨伐令', icon = 121, transtype = 0, showControl = 1, info = '世界用来攻打矿点敌人\n参与剿匪副本的资源', quality = 1, attributeType = 0}
Resource[601] = {ID = 601, name = '银两额外产量', icon = 1, transtype = 1, showControl = 0, info = '银两额外产量', quality = 1, attributeType = 0}
Resource[516] = {ID = 516, name = '升级建筑资源消只需x%', icon = 1, transtype = 0, showControl = 0, info = '升级建筑资源消只需x%', quality = 1, attributeType = 0}
Resource[602] = {ID = 602, name = '铁锭额外产量', icon = 1, transtype = 1, showControl = 0, info = '铁锭额外产量', quality = 1, attributeType = 0}
Resource[517] = {ID = 517, name = '攻打世界资源点道具掉落概率增加x%', icon = 1, transtype = 0, showControl = 0, info = '攻打世界资源点道具掉落概率增加x%', quality = 1, attributeType = 0}
Resource[701] = {ID = 701, name = '损兵额外率值', icon = 1, transtype = 0, showControl = 0, info = '损兵额外率值', quality = 1, attributeType = 0}
Resource[702] = {ID = 702, name = '损伤兵额外率值', icon = 1, transtype = 0, showControl = 0, info = '损伤兵额外率值', quality = 1, attributeType = 0}
Resource[603] = {ID = 603, name = '木材额外产量', icon = 1, transtype = 1, showControl = 0, info = '木材额外产量', quality = 1, attributeType = 0}
Resource[201] = {ID = 201, name = '银币', icon = 201, transtype = 1, showControl = 1, info = '用于研发科技，治疗兵种，提升\n军衔等', quality = 1, attributeType = 0}
Resource[202] = {ID = 202, name = '铁锭', icon = 202, transtype = 1, showControl = 1, info = '用于升级建筑，培养兵种，研发\n科技', quality = 1, attributeType = 0}
Resource[203] = {ID = 203, name = '木材', icon = 203, transtype = 1, showControl = 1, info = '用于升级建筑，培养兵种，研发\n科技', quality = 1, attributeType = 0}
Resource[204] = {ID = 204, name = '石料', icon = 204, transtype = 1, showControl = 1, info = '用于升级建筑，培养兵种，研发\n科技', quality = 1, attributeType = 0}
Resource[205] = {ID = 205, name = '粮食', icon = 205, transtype = 1, showControl = 1, info = '用于培养兵种，研发科技', quality = 1, attributeType = 0}
Resource[206] = {ID = 206, name = '元宝', icon = 206, transtype = 0, showControl = 1, info = '购买道具需要的游戏币；通过充\n值获取', quality = 5, attributeType = 0}
Resource[207] = {ID = 207, name = '礼券', icon = 207, transtype = 0, showControl = 0, info = '礼券', quality = 1, attributeType = 0}
Resource[208] = {ID = 208, name = '活跃', icon = 208, transtype = 0, showControl = 0, info = '游戏活跃度，达到条件可以领取\n奖励', quality = 1, attributeType = 0}
Resource[213] = {ID = 213, name = '自动升级', icon = 213, transtype = 0, showControl = 0, info = '自动升级建筑', quality = 1, attributeType = 0}
Resource[214] = {ID = 214, name = '同盟等级', icon = 214, transtype = 0, showControl = 0, info = '同盟等级', quality = 1, attributeType = 0}
Resource[215] = {ID = 215, name = '每日消耗元宝', icon = 215, transtype = 0, showControl = 0, info = '每日消耗元宝', quality = 1, attributeType = 0}
Resource[216] = {ID = 216, name = '同盟ID', icon = 1, transtype = 0, showControl = 0, info = '同盟ID', quality = 1, attributeType = 0}
Resource[217] = {ID = 217, name = '每日充值', icon = 1, transtype = 0, showControl = 0, info = '每日充值', quality = 1, attributeType = 0}
Resource[218] = {ID = 218, name = '民心', icon = 218, transtype = 0, showControl = 1, info = '领取奖励消耗的资源', quality = 1, attributeType = 0}
Resource[219] = {ID = 219, name = '民心上限', icon = 1, transtype = 0, showControl = 0, info = '民心的最大值', quality = 1, attributeType = 0}
Resource[220] = {ID = 220, name = '战功', icon = 1, transtype = 0, showControl = 0, info = '战功任务完成获得', quality = 1, attributeType = 0}
Resource[222] = {ID = 222, name = '名师值', icon = 1, transtype = 0, showControl = 0, info = '师门任务完成获得', quality = 1, attributeType = 0}
Resource[223] = {ID = 223, name = '酒令', icon = 223, transtype = 0, showControl = 1, info = '酒馆行酒获得', quality = 4, attributeType = 0}
Resource[224] = {ID = 224, name = '矿点等级', icon = 1, transtype = 0, showControl = 0, info = '矿点等级', quality = 1, attributeType = 0}
Resource[519] = {ID = 519, name = '资源类科技研发只需x%资源', icon = 1, transtype = 0, showControl = 0, info = '资源类科技研发只需x%资源', quality = 1, attributeType = 0}
Resource[513] = {ID = 513, name = '顶级9连抽打折', icon = 1, transtype = 0, showControl = 0, info = '顶级9连抽打折', quality = 1, attributeType = 0}
Resource[520] = {ID = 520, name = '副本活动期间额外掉落', icon = 1, transtype = 0, showControl = 0, info = '副本活动期间额外掉落', quality = 1, attributeType = 0}
Resource[606] = {ID = 606, name = '乱军行军速度加成', icon = 1, transtype = 0, showControl = 0, info = '乱军行军速度加成', quality = 1, attributeType = 0}
Resource[801] = {ID = 801, name = '禁言-世界频道', icon = 1, transtype = 0, showControl = 0, info = '禁言-世界频道', quality = 1, attributeType = 0}
Resource[802] = {ID = 802, name = '禁言-私聊', icon = 1, transtype = 0, showControl = 0, info = '禁言-私聊', quality = 1, attributeType = 0}
Resource[803] = {ID = 803, name = '禁言-喇叭', icon = 1, transtype = 0, showControl = 0, info = '禁言-喇叭', quality = 1, attributeType = 0}
Resource[521] = {ID = 521, name = '大厅捐献获得建设度与贡献加成x%', icon = 1, transtype = 0, showControl = 0, info = '大厅捐献获得建设度与贡献加成x%', quality = 1, attributeType = 0}
Resource[301] = {ID = 301, name = '同盟建设度', icon = 301, transtype = 0, showControl = 1, info = '同盟建设度，可提升同盟等级', quality = 1, attributeType = 0}
Resource[302] = {ID = 302, name = '同盟贡献值', icon = 302, transtype = 0, showControl = 0, info = '同盟贡献值，在同盟商店兑换物品', quality = 1, attributeType = 0}
Resource[303] = {ID = 303, name = '同盟科技郡城谋略', icon = 304, transtype = 0, showControl = 0, info = '同盟科技，可增加盟战每日宣战次数', quality = 1, attributeType = 0}
Resource[304] = {ID = 304, name = '同盟科技固若金汤', icon = 304, transtype = 0, showControl = 0, info = '同盟科技，可增加郡城保护时间', quality = 1, attributeType = 0}
Resource[305] = {ID = 305, name = '同盟俸禄', icon = 305, transtype = 0, showControl = 0, info = '同盟俸禄，可用于兑换珍品', quality = 1, attributeType = 0}
Resource[607] = {ID = 607, name = '商店资源价格折扣', icon = 1, transtype = 0, showControl = 0, info = '商店资源价格折扣', quality = 1, attributeType = 0}
Resource[522] = {ID = 522, name = '同盟科技捐献获得科技经验与贡献加成x%', icon = 1, transtype = 0, showControl = 0, info = '同盟科技捐献获得科技经验与贡献加成x%', quality = 1, attributeType = 0}
Resource[523] = {ID = 523, name = '探险额外掉落奖励（匈奴+鲜卑）', icon = 1, transtype = 0, showControl = 0, info = '探险额外掉落奖励（匈奴+鲜卑）', quality = 1, attributeType = 0}
Resource[524] = {ID = 524, name = '野外攻打额外掉落奖励（打人、打矿、打剿匪）', icon = 1, transtype = 0, showControl = 0, info = '野外攻打额外掉落奖励（打人、打矿、打剿匪）', quality = 1, attributeType = 0}
Resource[90004] = {ID = 90004, name = '禁用道具-免战', icon = 1, transtype = 0, showControl = 0, info = '禁用道具-免战', quality = 1, attributeType = 0}
Resource[514] = {ID = 514, name = '招募将领花费金币优惠', icon = 1, transtype = 0, showControl = 0, info = '招募将领花费金币优惠', quality = 1, attributeType = 0}
Resource[518] = {ID = 518, name = '资源类科技研发速度提升x%', icon = 1, transtype = 0, showControl = 0, info = '资源类科技研发速度提升x%', quality = 1, attributeType = 0}
Resource[501] = {ID = 501, name = '同盟大厅采用金币贡献，消耗是原来的x%(返还1-x%金币)', icon = 1, transtype = 0, showControl = 0, info = '同盟大厅采用金币贡献，消耗是原来的x%(返还1-x%金币)', quality = 1, attributeType = 0}
Resource[502] = {ID = 502, name = '同盟科技采用金币贡献，消耗是原来的x%(返还1-x%金币)', icon = 1, transtype = 0, showControl = 0, info = '同盟科技采用金币贡献，消耗是原来的x%(返还1-x%金币)', quality = 1, attributeType = 0}
Resource[503] = {ID = 503, name = '每日增加x次装备探险次数', icon = 1, transtype = 0, showControl = 0, info = '每日增加x次装备探险次数', quality = 1, attributeType = 0}
Resource[504] = {ID = 504, name = '每日增加x次配件探险次数', icon = 1, transtype = 0, showControl = 0, info = '每日增加x次配件探险次数', quality = 1, attributeType = 0}
Resource[505] = {ID = 505, name = '配件关卡额外次数购买，消耗是原来的x%(返还1-x%金币)', icon = 1, transtype = 0, showControl = 0, info = '配件关卡额外次数购买，消耗是原来的x%(返还1-x%金币)', quality = 1, attributeType = 0}
Resource[506] = {ID = 506, name = '配件关卡伤害加成x%', icon = 1, transtype = 0, showControl = 0, info = '配件关卡伤害加成x%', quality = 1, attributeType = 0}
Resource[507] = {ID = 507, name = '装备关卡额外次数购买，消耗是原来的x%(返还1-x%金币)', icon = 1, transtype = 0, showControl = 0, info = '装备关卡额外次数购买，消耗是原来的x%(返还1-x%金币)', quality = 1, attributeType = 0}
Resource[508] = {ID = 508, name = '装备关卡伤害加成x%', icon = 1, transtype = 0, showControl = 0, info = '装备关卡伤害加成x%', quality = 1, attributeType = 0}
Resource[509] = {ID = 509, name = '配件强化失败，仅扣除x%宝石', icon = 1, transtype = 0, showControl = 0, info = '配件强化失败，仅扣除x%宝石', quality = 1, attributeType = 0}
Resource[510] = {ID = 510, name = '改造不降低强化等级', icon = 1, transtype = 0, showControl = 0, info = '改造不降低强化等级', quality = 1, attributeType = 0}
Resource[511] = {ID = 511, name = '升级装备时装备卡提供的经验增加x%', icon = 1, transtype = 0, showControl = 0, info = '升级装备时装备卡提供的经验增加x%', quality = 1, attributeType = 0}
return Resource