local SeniorQu = {} 
SeniorQu[1] = {ID = 1, examType = 1, question = '一天可免费领取军令的总数是', trueAnswerId = 1, trueAnswer = 30, falseAnswer1 = 10, falseAnswer2 = 20}
SeniorQu[2] = {ID = 2, examType = 1, question = '军令多长时候恢复一点', trueAnswerId = 1, trueAnswer = '30分钟', falseAnswer1 = '20分钟', falseAnswer2 = '15分钟'}
SeniorQu[3] = {ID = 3, examType = 1, question = '重置西域远征需要消耗的是', trueAnswerId = 1, trueAnswer = '军令', falseAnswer1 = '讨伐令', falseAnswer2 = '元宝'}
SeniorQu[4] = {ID = 4, examType = 1, question = '重置西域远征消耗的军令数量是', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 0}
SeniorQu[5] = {ID = 5, examType = 1, question = '西域远征初始单关的挑战次数是', trueAnswerId = 1, trueAnswer = 3, falseAnswer1 = 1, falseAnswer2 = 5}
SeniorQu[6] = {ID = 6, examType = 1, question = '声望等级影响', trueAnswerId = 1, trueAnswer = '科技等级', falseAnswer1 = '战法等级', falseAnswer2 = '统率等级'}
SeniorQu[7] = {ID = 7, examType = 1, question = '统率等级影响', trueAnswerId = 1, trueAnswer = '带兵量', falseAnswer1 = '先手值', falseAnswer2 = '科技等级'}
SeniorQu[8] = {ID = 8, examType = 1, question = '铸币所建筑可建造多少个', trueAnswerId = 1, trueAnswer = 1, falseAnswer1 = 3, falseAnswer2 = 5}
SeniorQu[9] = {ID = 9, examType = 1, question = '校场建筑的作用是', trueAnswerId = 1, trueAnswer = '升级兵种', falseAnswer1 = '升级武将', falseAnswer2 = '升级军械'}
SeniorQu[10] = {ID = 10, examType = 1, question = '战法等级不能超过', trueAnswerId = 1, trueAnswer = '主公等级', falseAnswer1 = '官邸等级', falseAnswer2 = '声望等级'}
SeniorQu[11] = {ID = 11, examType = 1, question = '重置一次战法等级需要消耗多少元宝', trueAnswerId = 1, trueAnswer = 58, falseAnswer1 = 48, falseAnswer2 = 68}
SeniorQu[12] = {ID = 12, examType = 1, question = '主城最多拥有多少个仓库建筑', trueAnswerId = 1, trueAnswer = 2, falseAnswer1 = 1, falseAnswer2 = 3}
SeniorQu[13] = {ID = 13, examType = 1, question = 'vip0玩家升级建筑的免费建造时间是', trueAnswerId = 1, trueAnswer = '5分钟', falseAnswer1 = '4分钟', falseAnswer2 = '3分钟'}
SeniorQu[14] = {ID = 14, examType = 1, question = 'vip0玩家每日可购买军令次数为', trueAnswerId = 1, trueAnswer = '1次', falseAnswer1 = '0次', falseAnswer2 = '2次'}
SeniorQu[15] = {ID = 15, examType = 1, question = '哪类品质的军师不能任命内政', trueAnswerId = 1, trueAnswer = '橙色军师', falseAnswer1 = '紫色军师', falseAnswer2 = '白色军师'}
SeniorQu[16] = {ID = 16, examType = 1, question = '每日中午免费领取军令的时候从12:00到', trueAnswerId = 1, trueAnswer = '14点', falseAnswer1 = '13点', falseAnswer2 = '13点30分'}
SeniorQu[17] = {ID = 17, examType = 1, question = '每日晚上免费领取军令的时候从18:00到', trueAnswerId = 1, trueAnswer = '20点', falseAnswer1 = '19点', falseAnswer2 = '19点30分'}
SeniorQu[18] = {ID = 18, examType = 1, question = '单次免费领取军令的个数是', trueAnswerId = 1, trueAnswer = 10, falseAnswer1 = 5, falseAnswer2 = 20}
SeniorQu[19] = {ID = 19, examType = 1, question = '西域远征每日可重置的次数是', trueAnswerId = 1, trueAnswer = 1, falseAnswer1 = 2, falseAnswer2 = 3}
SeniorQu[20] = {ID = 20, examType = 1, question = '匈奴远征不会产出', trueAnswerId = 1, trueAnswer = '军械', falseAnswer1 = '兵法册', falseAnswer2 = '经验书'}
SeniorQu[21] = {ID = 21, examType = 1, question = '匈奴远征每日免费挑战次数', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 0}
SeniorQu[22] = {ID = 22, examType = 1, question = '鲜卑远征不会产出', trueAnswerId = 1, trueAnswer = '突破丹', falseAnswer1 = '改造金属', falseAnswer2 = '改造精华'}
SeniorQu[23] = {ID = 23, examType = 1, question = '鲜卑远征每日免费挑战次数', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 0}
SeniorQu[24] = {ID = 24, examType = 1, question = '中原战役副本挑战损失兵种百分比', trueAnswerId = 1, trueAnswer = '百分之0', falseAnswer1 = '百分之1', falseAnswer2 = '百分之2'}
SeniorQu[25] = {ID = 25, examType = 1, question = '祝福好友获得经验值只限前几次祝福', trueAnswerId = 1, trueAnswer = 10, falseAnswer1 = 15, falseAnswer2 = 20}
SeniorQu[26] = {ID = 26, examType = 1, question = '目前添加好友的数量上限是', trueAnswerId = 1, trueAnswer = 20, falseAnswer1 = 15, falseAnswer2 = 30}
SeniorQu[27] = {ID = 27, examType = 1, question = '每日可领取好友祝福获得军令的上限是', trueAnswerId = 1, trueAnswer = 10, falseAnswer1 = 15, falseAnswer2 = 20}
SeniorQu[28] = {ID = 28, examType = 1, question = '军械单个兵种类型可穿戴的军械个数是', trueAnswerId = 1, trueAnswer = 8, falseAnswer1 = 6, falseAnswer2 = 7}
SeniorQu[29] = {ID = 29, examType = 1, question = '军械碎片不足时可通过什么合成', trueAnswerId = 1, trueAnswer = '万年寒铁', falseAnswer1 = '千年寒铁', falseAnswer2 = '百年寒铁'}
SeniorQu[30] = {ID = 30, examType = 1, question = '军械提升包括强化、改造和', trueAnswerId = 1, trueAnswer = '进阶', falseAnswer1 = '锻造', falseAnswer2 = '吞噬'}
SeniorQu[31] = {ID = 31, examType = 1, question = '什么品质的军械可进行进阶', trueAnswerId = 1, trueAnswer = '紫色', falseAnswer1 = '蓝色', falseAnswer2 = '绿色'}
SeniorQu[32] = {ID = 32, examType = 1, question = '军械强化消耗', trueAnswerId = 1, trueAnswer = '银币', falseAnswer1 = '元宝', falseAnswer2 = '木材'}
SeniorQu[33] = {ID = 33, examType = 1, question = '军械改造会降低当前军械多少强化等级', trueAnswerId = 1, trueAnswer = 3, falseAnswer1 = 5, falseAnswer2 = 1}
SeniorQu[34] = {ID = 34, examType = 1, question = '发送聊天信息的间隔时间是', trueAnswerId = 1, trueAnswer = '5秒', falseAnswer1 = '10秒', falseAnswer2 = '1秒'}
SeniorQu[35] = {ID = 35, examType = 1, question = '武将可上阵', trueAnswerId = 1, trueAnswer = '6个', falseAnswer1 = '5个', falseAnswer2 = '8个'}
SeniorQu[36] = {ID = 36, examType = 1, question = '演武场每日免费挑战次数', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 8}
SeniorQu[37] = {ID = 37, examType = 1, question = '演武场挑战失败后的冷却时间为', trueAnswerId = 1, trueAnswer = '10分钟', falseAnswer1 = '5分钟', falseAnswer2 = '15分钟'}
SeniorQu[38] = {ID = 38, examType = 1, question = '先手值一样时，演武场谁先手', trueAnswerId = 1, trueAnswer = '攻方', falseAnswer1 = '守方', falseAnswer2 = '双方随机'}
SeniorQu[39] = {ID = 39, examType = 1, question = '同盟作战所每日免费挑战次数为', trueAnswerId = 1, trueAnswer = 5, falseAnswer1 = 10, falseAnswer2 = 15}
SeniorQu[40] = {ID = 40, examType = 2, question = '阿会喃:试问《孟德新书》共有多少篇？', trueAnswerId = 1, trueAnswer = '十三篇', falseAnswer1 = '十二篇', falseAnswer2 = '十五篇'}
SeniorQu[41] = {ID = 41, examType = 2, question = '步骘:博望坡之战是谁第一次指挥作战？', trueAnswerId = 1, trueAnswer = '诸葛亮', falseAnswer1 = '庞统', falseAnswer2 = '徐庶'}
SeniorQu[42] = {ID = 42, examType = 2, question = '昌豨:耿纪谋反时，谁引千余人在许都城内抗击反军？', trueAnswerId = 1, trueAnswer = '曹休', falseAnswer1 = '曹彰', falseAnswer2 = '曹植'}
SeniorQu[43] = {ID = 43, examType = 2, question = '蔡瑁:刘备自幼家贫以何种活计为生问题答案是什么', trueAnswerId = 1, trueAnswer = '贩履织席', falseAnswer1 = '卖猪肉', falseAnswer2 = '卖枣'}
SeniorQu[44] = {ID = 44, examType = 2, question = '蔡瑁:因此孟德与士族私交甚好。孟德的祖父进达名士中有一位是我的姑丈，主公认为是谁？', trueAnswerId = 1, trueAnswer = '南阳张温', falseAnswer1 = '襄阳庞德公', falseAnswer2 = '颍川司马徽'}
SeniorQu[45] = {ID = 45, examType = 2, question = '蔡瑁:主公若是想争霸天下，就要好好发挥每个人的力量。那么我蔡瑁的长处是什么呢？', trueAnswerId = 1, trueAnswer = '水战', falseAnswer1 = '步战', falseAnswer2 = '骑战'}
SeniorQu[46] = {ID = 46, examType = 2, question = '蔡和:三国时代，谁的记忆力超群，看过《孟德新书》即可倒背如流？', trueAnswerId = 1, trueAnswer = '张松', falseAnswer1 = '法正', falseAnswer2 = '李儒'}
SeniorQu[47] = {ID = 47, examType = 2, question = '蔡和:定军山一战，蜀魏曾有交换俘虏的行为，请问两位俘虏的名字是？', trueAnswerId = 1, trueAnswer = '陈式、夏侯尚', falseAnswer1 = '雷铜、夏侯恩', falseAnswer2 = '糜芳、曹休'}
SeniorQu[48] = {ID = 48, examType = 2, question = '蔡琰:试问下列这些字体中，哪一种是我父亲原创？', trueAnswerId = 1, trueAnswer = '八分体', falseAnswer1 = '六分体', falseAnswer2 = '四分体'}
SeniorQu[49] = {ID = 49, examType = 2, question = '蔡琰:楚辞中以九为名的篇章极多，以九为名并非只有九篇，其中非九篇的集称，还请主公指出。', trueAnswerId = 1, trueAnswer = '九歌', falseAnswer1 = '九章', falseAnswer2 = '九怀'}
SeniorQu[50] = {ID = 50, examType = 2, question = '蔡琰:关羽的武器青龙偃月刀重多少斤？', trueAnswerId = 1, trueAnswer = '八十二斤', falseAnswer1 = '九十八斤', falseAnswer2 = '七十二斤'}
SeniorQu[51] = {ID = 51, examType = 2, question = '曹操:主公有无兴趣猜测一下，犬子子恒、子文、子建、子脩中，哪一个不是内人卞夫人所生？', trueAnswerId = 1, trueAnswer = '子脩', falseAnswer1 = '子文', falseAnswer2 = '子健'}
SeniorQu[52] = {ID = 52, examType = 2, question = '曹操:下列哪部作品不是岀自某之手？', trueAnswerId = 1, trueAnswer = '典论', falseAnswer1 = '短歌行', falseAnswer2 = '龟虽寿'}
SeniorQu[53] = {ID = 53, examType = 2, question = '曹操:昭陵是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '荆州', falseAnswer1 = '扬州', falseAnswer2 = '青州'}
SeniorQu[54] = {ID = 54, examType = 2, question = '曹操:早年我散尽家财，号召天下英雄讨伐董卓，我在何处起兵？', trueAnswerId = 1, trueAnswer = '陈留', falseAnswer1 = '南阳', falseAnswer2 = '颍川'}
SeniorQu[55] = {ID = 55, examType = 2, question = '曹纯:除掉袁谭之后，我军继续征伐乌丸三郡，主公可知乌丸三郡之首是何地？', trueAnswerId = 1, trueAnswer = '辽西郡', falseAnswer1 = '辽东郡', falseAnswer2 = '渔阳郡'}
SeniorQu[56] = {ID = 56, examType = 2, question = '曹纯:下列诸位中，哪一位是以舌毒骂战著称？', trueAnswerId = 1, trueAnswer = '祢衡', falseAnswer1 = '杨修', falseAnswer2 = '许攸'}
SeniorQu[57] = {ID = 57, examType = 2, question = '曹洪:当年威震逍遥津，半夜能止小儿夜啼的是我哪位同袍啊？', trueAnswerId = 1, trueAnswer = '张辽', falseAnswer1 = '张郃', falseAnswer2 = '典韦'}
SeniorQu[58] = {ID = 58, examType = 2, question = '曹洪:马超与曹操在潼关激战时，哪个部落前来增援？', trueAnswerId = 1, trueAnswer = '羌', falseAnswer1 = '蛮', falseAnswer2 = '狄'}
SeniorQu[59] = {ID = 59, examType = 2, question = '曹洪:孟德的子嗣也很多，在众夫人中，哪一位是为孟德生下儿子最多的夫人呢？', trueAnswerId = 1, trueAnswer = '卞夫人', falseAnswer1 = '丁夫人', falseAnswer2 = '环夫人'}
SeniorQu[60] = {ID = 60, examType = 2, question = '曹彰:剡县是哪个州属治下呢？', trueAnswerId = 1, trueAnswer = '扬州', falseAnswer1 = '荆州', falseAnswer2 = '青州'}
SeniorQu[61] = {ID = 61, examType = 2, question = '曹彰:主公你看，这“厌厌良人，轶轶德音”之句，不知出自《诗经·秦风》中的哪一篇？', trueAnswerId = 1, trueAnswer = '小戎', falseAnswer1 = '蒹葭', falseAnswer2 = '无衣'}
SeniorQu[62] = {ID = 62, examType = 2, question = '曹彰:我曹家权势地位日渐壮大，但能活着封王的兄弟，也没几个了。我是什么王', trueAnswerId = 1, trueAnswer = '任城王', falseAnswer1 = '中山王', falseAnswer2 = '陈思王'}
SeniorQu[63] = {ID = 63, examType = 2, question = '曹彰:我平素最是佩服汉代的霍去病，你知道以下这些成语中，哪一个和霍去病有关吗？', trueAnswerId = 1, trueAnswer = '封狼居胥', falseAnswer1 = '投笔从戎', falseAnswer2 = '闻鸡起舞'}
SeniorQu[64] = {ID = 64, examType = 2, question = '曹丕:我是在哪一年建立的太学，制五经课试之法呢？', trueAnswerId = 1, trueAnswer = '黄初五年', falseAnswer1 = '黄初六年', falseAnswer2 = '黄初七年'}
SeniorQu[65] = {ID = 65, examType = 2, question = '曹丕:话说昔日，家父与玄德公煮酒论英雄，主公可知，家父如何评价淮南袁术？', trueAnswerId = 1, trueAnswer = '冢中枯骨', falseAnswer1 = '好谋无断', falseAnswer2 = '守户之犬'}
SeniorQu[66] = {ID = 66, examType = 2, question = '曹丕:我正想将我这些年的辞赋编纂成册，但混进了一篇别人的同名赋，还烦请主公帮我找出。', trueAnswerId = 1, trueAnswer = '登台赋', falseAnswer1 = '燕歌行', falseAnswer2 = '典论'}
SeniorQu[67] = {ID = 67, examType = 2, question = '曹丕:南城是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '扬州', falseAnswer1 = '益州', falseAnswer2 = '荆州'}
SeniorQu[68] = {ID = 68, examType = 2, question = '曹仁:朐忍是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '益州', falseAnswer1 = '荆州', falseAnswer2 = '扬州'}
SeniorQu[69] = {ID = 69, examType = 2, question = '曹仁:却不想，刘备手下有个神人，看破了我的八门金锁阵。主公可知此人是谁？', trueAnswerId = 1, trueAnswer = '徐庶', falseAnswer1 = '庞统', falseAnswer2 = '诸葛亮'}
SeniorQu[70] = {ID = 70, examType = 2, question = '曹仁:其中有不少都是泛泛之辈，但与我战斗过的人，无论强弱我都能记得他的姓名。', trueAnswerId = 1, trueAnswer = '侯音', falseAnswer1 = '邓艾', falseAnswer2 = '姜维'}
SeniorQu[71] = {ID = 71, examType = 2, question = '曹仁:赤壁之战之后为我军重整旗鼓，主公命我我镇守江陵与谁对峙？', trueAnswerId = 1, trueAnswer = '周瑜', falseAnswer1 = '陆逊', falseAnswer2 = '鲁肃'}
SeniorQu[72] = {ID = 72, examType = 2, question = '曹性:蜀汉最后一个年号是什么？', trueAnswerId = 1, trueAnswer = '炎兴', falseAnswer1 = '建兴', falseAnswer2 = '延熙'}
SeniorQu[73] = {ID = 73, examType = 2, question = '曹安民:决定曹操和袁绍胜败的关键战役是？', trueAnswerId = 1, trueAnswer = '官渡攻城战', falseAnswer1 = '邺城之战', falseAnswer2 = '白马渡之战'}
SeniorQu[74] = {ID = 74, examType = 2, question = '曹昂:赤壁之战时，黄盖担任什么官职？', trueAnswerId = 1, trueAnswer = '丹阳都尉', falseAnswer1 = '桂阳都尉', falseAnswer2 = '赤壁都尉'}
SeniorQu[75] = {ID = 75, examType = 2, question = '陈到:陛下可是明君，古蜀国曾有个开明朝，也是明君在世，根据史料，古蜀国开明帝又是谁的子孙呢？', trueAnswerId = 1, trueAnswer = '鳖灵', falseAnswer1 = '望帝', falseAnswer2 = '鱼凫'}
SeniorQu[76] = {ID = 76, examType = 2, question = '陈到:诸侯半年，大夫一季，庶民一月，请问天子是多久？', trueAnswerId = 1, trueAnswer = '一年', falseAnswer1 = '两年', falseAnswer2 = '三年'}
SeniorQu[77] = {ID = 77, examType = 2, question = '陈登:诸葛亮最后一次北伐病死在哪？', trueAnswerId = 1, trueAnswer = '五丈原', falseAnswer1 = '定军山', falseAnswer2 = '成都'}
SeniorQu[78] = {ID = 78, examType = 2, question = '陈登:以下诸人中，属于子建的智囊的是哪一位？', trueAnswerId = 1, trueAnswer = '杨修', falseAnswer1 = '贾诩', falseAnswer2 = '陈群'}
SeniorQu[79] = {ID = 79, examType = 2, question = '陈登:曾有一郡子民因我迁任，执意追随于我，好在被我劝服，主公听说是哪一郡吗？', trueAnswerId = 1, trueAnswer = '广陵郡', falseAnswer1 = '桂阳郡', falseAnswer2 = '南阳郡'}
SeniorQu[80] = {ID = 80, examType = 2, question = '陈珪:司马师废了曹芳后立谁为皇帝？', trueAnswerId = 1, trueAnswer = '曹髦', falseAnswer1 = '曹睿', falseAnswer2 = '曹休'}
SeniorQu[81] = {ID = 81, examType = 2, question = '陈珪:刘备三顾茅庐之时，听路途有人醉酒高歌，请问此人是谁？', trueAnswerId = 1, trueAnswer = '石广元', falseAnswer1 = '崔州平', falseAnswer2 = '孟公威'}
SeniorQu[82] = {ID = 82, examType = 2, question = '程普:这数人中，与一人交往“若饮醇醪，不觉自醉。”，你可知是谁？', trueAnswerId = 1, trueAnswer = '周瑜', falseAnswer1 = '鲁肃', falseAnswer2 = '黄盖'}
SeniorQu[83] = {ID = 83, examType = 2, question = '程普:于吉在山中采药时得到的神书是哪一部？', trueAnswerId = 1, trueAnswer = '太平清领道', falseAnswer1 = '文始真经', falseAnswer2 = '南华真经'}
SeniorQu[84] = {ID = 84, examType = 2, question = '程普:我被封为荡寇将军之前曾就任三郡太守，非我任职过得郡是哪一个？', trueAnswerId = 1, trueAnswer = '吴郡太守', falseAnswer1 = '江夏太守', falseAnswer2 = '南郡太守'}
SeniorQu[85] = {ID = 85, examType = 2, question = '程普:吕布辕门射戟时，他离辕门的距离是多少？', trueAnswerId = 1, trueAnswer = '一百五十步', falseAnswer1 = '一百二十步', falseAnswer2 = '一百步'}
SeniorQu[86] = {ID = 86, examType = 2, question = '淳于琼:我是右校尉，袁本初是中军校尉，主公可知他原来的官职是什么？', trueAnswerId = 1, trueAnswer = '虎贲中郎将', falseAnswer1 = '骠骑将军', falseAnswer2 = '发丘中郎将'}
SeniorQu[87] = {ID = 87, examType = 2, question = '淳于琼:你知道西园八校尉的指挥是谁吗？', trueAnswerId = 1, trueAnswer = '蹇硕', falseAnswer1 = '曹操', falseAnswer2 = '袁绍'}
SeniorQu[88] = {ID = 88, examType = 2, question = '淳于琼:定下“白衣渡江”之计，使关羽大意失荆州的是谁？', trueAnswerId = 1, trueAnswer = '吕蒙', falseAnswer1 = '陆逊', falseAnswer2 = '鲁肃'}
SeniorQu[89] = {ID = 89, examType = 2, question = '丁奉:主公了解这几个人中哪个不是降吴之将吗？', trueAnswerId = 1, trueAnswer = '母丘俭', falseAnswer1 = '范疆', falseAnswer2 = '张达'}
SeniorQu[90] = {ID = 90, examType = 2, question = '丁奉:凌统与甘宁，你可知他两因何结仇么？', trueAnswerId = 1, trueAnswer = '父仇', falseAnswer1 = '争功', falseAnswer2 = '夺妻'}
SeniorQu[91] = {ID = 91, examType = 2, question = '丁奉:民间智力游戏“华容道”中没有下列哪个人物？', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '关羽', falseAnswer2 = '曹操'}
SeniorQu[92] = {ID = 92, examType = 2, question = '大乔:主公可知孝感动天，涌泉跃二鲤是何人之妻？', trueAnswerId = 1, trueAnswer = '姜诗', falseAnswer1 = '姜维', falseAnswer2 = '张昭'}
SeniorQu[93] = {ID = 93, examType = 2, question = '大乔:张纮张昭的籍贯各是何地？', trueAnswerId = 1, trueAnswer = '广陵与彭城', falseAnswer1 = '广陵与零陵', falseAnswer2 = '零陵与桂阳'}
SeniorQu[94] = {ID = 94, examType = 2, question = '大乔:下列这些地方中，哪一个不属于江东六郡？', trueAnswerId = 1, trueAnswer = '零陵郡', falseAnswer1 = '会稽郡', falseAnswer2 = '丹阳郡'}
SeniorQu[95] = {ID = 95, examType = 2, question = '邓贤:以下何人不是黄巾军余党？', trueAnswerId = 1, trueAnswer = '许韶', falseAnswer1 = '张曼城', falseAnswer2 = '波才'}
SeniorQu[96] = {ID = 96, examType = 2, question = '邓芝:韦昭注解《尚书禹贡》时对三江有过说明，主公认为哪条不在三江之中？', trueAnswerId = 1, trueAnswer = '扬子江', falseAnswer1 = '长江', falseAnswer2 = '黄河'}
SeniorQu[97] = {ID = 97, examType = 2, question = '邓芝:下面哪部不是杜预将军的著作？', trueAnswerId = 1, trueAnswer = '《养生论》', falseAnswer1 = '《春秋释例》', falseAnswer2 = '《律本》'}
SeniorQu[98] = {ID = 98, examType = 2, question = '邓艾:曹爽曾派谁刺探司马懿虚实？', trueAnswerId = 1, trueAnswer = '李胜', falseAnswer1 = '邓飏', falseAnswer2 = '夏侯玄'}
SeniorQu[99] = {ID = 99, examType = 2, question = '邓艾:以下几人中，哪一位最后没有做皇帝？', trueAnswerId = 1, trueAnswer = '刘表', falseAnswer1 = '刘备', falseAnswer2 = '孙权'}
SeniorQu[100] = {ID = 100, examType = 2, question = '典韦:我的同僚许褚经常被人称为“虎痴”，那么主公可知道人们经常把我比作古代哪位英雄吗？', trueAnswerId = 1, trueAnswer = '恶来', falseAnswer1 = '专诸', falseAnswer2 = '豫让'}
SeniorQu[101] = {ID = 101, examType = 2, question = '典韦:宜春是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '扬州', falseAnswer1 = '益州', falseAnswer2 = '荆州'}
SeniorQu[102] = {ID = 102, examType = 2, question = '典韦:各地诸侯举义兵，我也投入其中，前后侍奉了几任主公，那么这几人中，哪一位不是我的主公？', trueAnswerId = 1, trueAnswer = '满宠', falseAnswer1 = '张邈', falseAnswer2 = '曹操'}
SeniorQu[103] = {ID = 103, examType = 2, question = '董允:如今丞相北伐，临行前还给陛下献策，你知道丞相交给陛下的是什么东西吗？', trueAnswerId = 1, trueAnswer = '出师表', falseAnswer1 = '隆中对', falseAnswer2 = '诫子书'}
SeniorQu[104] = {ID = 104, examType = 2, question = '董允:以下这些诗文中，哪一篇是相传曹植为甄宓写就？', trueAnswerId = 1, trueAnswer = '洛神赋', falseAnswer1 = '短歌行', falseAnswer2 = '铜雀赋'}
SeniorQu[105] = {ID = 105, examType = 2, question = '董允:古时天子的后妃品德高尚，应让世人多加注目，主公可知这些人中不是黄帝四妃的人是谁？', trueAnswerId = 1, trueAnswer = '有邰氏女', falseAnswer1 = '嫘祖', falseAnswer2 = '方雷氏'}
SeniorQu[106] = {ID = 106, examType = 2, question = '董卓:说道六郡，非我大汉置的郡是哪一个？', trueAnswerId = 1, trueAnswer = '陇西', falseAnswer1 = '天水', falseAnswer2 = '平凉'}
SeniorQu[107] = {ID = 107, examType = 2, question = '董卓:为曹操随身背青釭大剑的人是谁？', trueAnswerId = 1, trueAnswer = '夏侯恩', falseAnswer1 = '夏侯渊', falseAnswer2 = '夏侯惇'}
SeniorQu[108] = {ID = 108, examType = 2, question = '董卓:我小时候耕田，得到一把刀，后来我拿给别人看，你猜别人告诉我，这是谁的刀？', trueAnswerId = 1, trueAnswer = '项羽', falseAnswer1 = '白起', falseAnswer2 = '蒙恬'}
SeniorQu[109] = {ID = 109, examType = 2, question = '董卓:成都攻略战中最先到达成都并成功占领的是魏国哪位武将？', trueAnswerId = 1, trueAnswer = '邓艾', falseAnswer1 = '钟会', falseAnswer2 = '曹休'}
SeniorQu[110] = {ID = 110, examType = 2, question = '貂蝉:黄帝与炎帝的母亲分别是哪两位？', trueAnswerId = 1, trueAnswer = '附宝与任姒', falseAnswer1 = '有邰氏女与任姒', falseAnswer2 = '附宝与有邰氏女'}
SeniorQu[111] = {ID = 111, examType = 2, question = '貂蝉:刘备的妻子甘夫人于何年生了刘阿斗？', trueAnswerId = 1, trueAnswer = '建安十二年', falseAnswer1 = '建安十三年', falseAnswer2 = '建安十四年'}
SeniorQu[112] = {ID = 112, examType = 2, question = '貂蝉:司徒妙算托红裙，不用干戈不用兵。三战虎牢徒费力，凯歌却奏凤仪亭。”这首诗说的是谁？', trueAnswerId = 1, trueAnswer = '貂蝉', falseAnswer1 = '大乔', falseAnswer2 = '甄宓'}
SeniorQu[113] = {ID = 113, examType = 2, question = '樊稠:灵帝时期，把持朝政的宦官被称作什么？', trueAnswerId = 1, trueAnswer = '十常侍', falseAnswer1 = '九常侍', falseAnswer2 = '八常侍'}
SeniorQu[114] = {ID = 114, examType = 2, question = '樊稠:谁赐关羽“美髯公”的名号?', trueAnswerId = 1, trueAnswer = '汉献帝', falseAnswer1 = '汉少帝', falseAnswer2 = '汉灵帝'}
SeniorQu[115] = {ID = 115, examType = 2, question = '樊能:甘宁是死在谁手里？', trueAnswerId = 1, trueAnswer = '沙摩柯', falseAnswer1 = '凌统', falseAnswer2 = '张辽'}
SeniorQu[116] = {ID = 116, examType = 2, question = '樊能:诸葛亮号“卧龙”，庞统号“凤雏”，那么号水镜先生的是哪位高人呢？', trueAnswerId = 1, trueAnswer = '司马徽', falseAnswer1 = '庞德公', falseAnswer2 = '黄承彦'}
SeniorQu[117] = {ID = 117, examType = 2, question = '樊能:不过扬州刺史之位更迭换任很快，光我认识的就有好几人，主公知道其中谁是袁术委任的扬州刺史吗？', trueAnswerId = 1, trueAnswer = '惠衢', falseAnswer1 = '纪灵', falseAnswer2 = '陈纪'}
SeniorQu[118] = {ID = 118, examType = 2, question = '樊能:黄忠最初效忠的主公是哪一位？', trueAnswerId = 1, trueAnswer = '刘表', falseAnswer1 = '孙坚', falseAnswer2 = '黄祖'}
SeniorQu[119] = {ID = 119, examType = 2, question = '费玮:当年诸葛丞相和羌族首领越吉交手，用了什么办法克制了对方的铁车部队？', trueAnswerId = 1, trueAnswer = '落穴', falseAnswer1 = '火攻', falseAnswer2 = '八阵图'}
SeniorQu[120] = {ID = 120, examType = 2, question = '费玮:“士别三日当刮目相待”指的是谁？', trueAnswerId = 1, trueAnswer = '吕蒙', falseAnswer1 = '陆逊', falseAnswer2 = '鲁肃'}
SeniorQu[121] = {ID = 121, examType = 2, question = '费玮:说到太子，我们常以太子字“文衡”称呼，主公可知太子名讳为何？', trueAnswerId = 1, trueAnswer = '刘璿', falseAnswer1 = '刘虞', falseAnswer2 = '刘协'}
SeniorQu[122] = {ID = 122, examType = 2, question = '傅士仁:刘备观看的反黄巾军招募的告示是由谁发布的？', trueAnswerId = 1, trueAnswer = '刘焉', falseAnswer1 = '刘表', falseAnswer2 = '皇甫嵩'}
SeniorQu[123] = {ID = 123, examType = 2, question = '傅士仁:因为勇猛过人而被称为“小霸王”的是谁？', trueAnswerId = 1, trueAnswer = '孙策', falseAnswer1 = '孙坚', falseAnswer2 = '典韦'}
SeniorQu[124] = {ID = 124, examType = 2, question = '甘宁:不过吴国能人居多，以我早年的功绩，够不上拜将的资格，我是因何功初拜将军？', trueAnswerId = 1, trueAnswer = '攻皖破朱光', falseAnswer1 = '杀黄祖', falseAnswer2 = '击败张辽'}
SeniorQu[125] = {ID = 125, examType = 2, question = '甘宁:高顺带兵攻打小沛时，刘备守的是小沛的哪个城门？', trueAnswerId = 1, trueAnswer = '南门', falseAnswer1 = '北门', falseAnswer2 = '东门'}
SeniorQu[126] = {ID = 126, examType = 2, question = '甘宁:曹操手下何人有樊哙之名？', trueAnswerId = 1, trueAnswer = '许褚', falseAnswer1 = '典韦', falseAnswer2 = '徐晃'}
SeniorQu[127] = {ID = 127, examType = 2, question = '甘宁:当时乡里人还送我了一个外号，你可知晓吗？', trueAnswerId = 1, trueAnswer = '锦帆贼', falseAnswer1 = '绿林贼', falseAnswer2 = '水见愁'}
SeniorQu[128] = {ID = 128, examType = 2, question = '高柔:怀橘遗母，是指谁的事迹？', trueAnswerId = 1, trueAnswer = '陆绩', falseAnswer1 = '陆抗', falseAnswer2 = '陆逊'}
SeniorQu[129] = {ID = 129, examType = 2, question = '高顺:你可知这位“阳明黄帝”的真实身份吗？', trueAnswerId = 1, trueAnswer = '许昌', falseAnswer1 = '许韶', falseAnswer2 = '许生'}
SeniorQu[130] = {ID = 130, examType = 2, question = '高顺:的卢马最初是谁骑乘？', trueAnswerId = 1, trueAnswer = '张武', falseAnswer1 = '黄祖', falseAnswer2 = '蔡瑁'}
SeniorQu[131] = {ID = 131, examType = 2, question = '高览:凌统和乐进单挑时被谁射冷箭？', trueAnswerId = 1, trueAnswer = '曹休', falseAnswer1 = '曹真', falseAnswer2 = '曹彰'}
SeniorQu[132] = {ID = 132, examType = 2, question = '高干:西晋名将羊祜的妻子是谁的女儿？', trueAnswerId = 1, trueAnswer = '夏侯霸', falseAnswer1 = '夏侯恩', falseAnswer2 = '钟会'}
SeniorQu[133] = {ID = 133, examType = 2, question = '高干:刘备派了谁作为说客去说降马超？', trueAnswerId = 1, trueAnswer = '李恢', falseAnswer1 = '法正', falseAnswer2 = '李严'}
SeniorQu[134] = {ID = 134, examType = 2, question = '顾雍:是谁在潼关攻城战中为曹操献上离间计，挑拨马超跟韩遂关系？', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '荀攸', falseAnswer2 = '郭嘉'}
SeniorQu[135] = {ID = 135, examType = 2, question = '顾雍:我不及伯喈才能的万分之一，不知主公对音律是否了解，主公知道十三万九千九百六十八是哪一律？', trueAnswerId = 1, trueAnswer = '姑洗', falseAnswer1 = '黄钟', falseAnswer2 = '应钟'}
SeniorQu[136] = {ID = 136, examType = 2, question = '顾雍:那我问你，对我大汉影响最深的思想，是哪一家的？', trueAnswerId = 1, trueAnswer = '儒家', falseAnswer1 = '法家', falseAnswer2 = '道家'}
SeniorQu[137] = {ID = 137, examType = 2, question = '顾雍:五虎上将中最晚归顺刘备的是？', trueAnswerId = 1, trueAnswer = '马超', falseAnswer1 = '黄忠', falseAnswer2 = '赵云'}
SeniorQu[138] = {ID = 138, examType = 2, question = '关靖:因暗杀未遂被曹操断九指，割舌，分肢体而死的是谁 ？', trueAnswerId = 1, trueAnswer = '吉平', falseAnswer1 = '张绣', falseAnswer2 = '杨修'}
SeniorQu[139] = {ID = 139, examType = 2, question = '关羽:赤兔最早是属于谁的？', trueAnswerId = 1, trueAnswer = '董卓', falseAnswer1 = '吕布', falseAnswer2 = '丁原'}
SeniorQu[140] = {ID = 140, examType = 2, question = '关羽:当时士仁屯兵公安，公安之名为玄德所改，原地为哪一处入江口？', trueAnswerId = 1, trueAnswer = '油江口', falseAnswer1 = '白马津', falseAnswer2 = '长江口'}
SeniorQu[141] = {ID = 141, examType = 2, question = '关羽:主公可知下列哪件事情，与关某无关？', trueAnswerId = 1, trueAnswer = '白衣渡江', falseAnswer1 = '过五关斩六将', falseAnswer2 = '温酒斩华雄'}
SeniorQu[142] = {ID = 142, examType = 2, question = '关平:孙坚第四子孙匡字是什么？', trueAnswerId = 1, trueAnswer = '季佐', falseAnswer1 = '季安', falseAnswer2 = '季武'}
SeniorQu[143] = {ID = 143, examType = 2, question = '关平:记得当时是家父斩杀颜良解白马围后就被封为汉寿亭侯，主公可知具体的年份？', trueAnswerId = 1, trueAnswer = '建安五年', falseAnswer1 = '建安六年', falseAnswer2 = '建安七年'}
SeniorQu[144] = {ID = 144, examType = 2, question = '关平:儒家讲究的忠孝节义，关平牢记在心，下列这些著作中，哪一部是儒家经典？', trueAnswerId = 1, trueAnswer = '尚书', falseAnswer1 = '道德经', falseAnswer2 = '韩非子'}
SeniorQu[145] = {ID = 145, examType = 2, question = '关凤:曹操挟帝至许都后封谁为东平相？', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '荀彧', falseAnswer2 = '郭嘉'}
SeniorQu[146] = {ID = 146, examType = 2, question = '关凤:华雄也是员勇将，当时华雄已经斩杀了孙坚帐下哪位将领？', trueAnswerId = 1, trueAnswer = '祖茂', falseAnswer1 = '潘璋', falseAnswer2 = '凌操'}
SeniorQu[147] = {ID = 147, examType = 2, question = '管亥:你知不知道灵帝死后，和何太后争权，被何进毒杀的人是谁？', trueAnswerId = 1, trueAnswer = '董太后', falseAnswer1 = '何太后', falseAnswer2 = '王美人'}
SeniorQu[148] = {ID = 148, examType = 2, question = '管亥:铜雀台大宴上，曹操以西川红锦战袍为赏赐由各将比试武艺所得，最后战袍被谁毁坏？', trueAnswerId = 1, trueAnswer = '许褚、徐晃', falseAnswer1 = '典韦、徐晃', falseAnswer2 = '许褚、典韦'}
SeniorQu[149] = {ID = 149, examType = 2, question = '郭嘉:长社是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '豫州', falseAnswer1 = '并州', falseAnswer2 = '凉州'}
SeniorQu[150] = {ID = 150, examType = 2, question = '郭嘉:我曾向曹公献策，主公可记得是哪一策？', trueAnswerId = 1, trueAnswer = '十胜十败之策', falseAnswer1 = '八胜八败之策', falseAnswer2 = '五胜五败之策'}
SeniorQu[151] = {ID = 151, examType = 2, question = '郭图:是谁下命令杀死嵇康？', trueAnswerId = 1, trueAnswer = '司马昭', falseAnswer1 = '司马师', falseAnswer2 = '司马炎'}
SeniorQu[152] = {ID = 152, examType = 2, question = '郭汜:赤壁大战前，曹操借酒赋诗，是谁进言说曹操出言不吉，被曹操刺死', trueAnswerId = 1, trueAnswer = '刘馥', falseAnswer1 = '刘虞', falseAnswer2 = '杨修'}
SeniorQu[153] = {ID = 153, examType = 2, question = '韩当:我并非解烦兵唯一统帅，不过我偷偷告诉主公您，有一任是遭到仲谋忌恨的，你觉得是谁？', trueAnswerId = 1, trueAnswer = '张温', falseAnswer1 = '太史慈', falseAnswer2 = '胡综'}
SeniorQu[154] = {ID = 154, examType = 2, question = '韩当:赤壁大战时候，两人在军帐中定计，各自在手心中写了一个什么字？', trueAnswerId = 1, trueAnswer = '火', falseAnswer1 = '水', falseAnswer2 = '风'}
SeniorQu[155] = {ID = 155, examType = 2, question = '韩当:周瑜训练东吴水军的地点？', trueAnswerId = 1, trueAnswer = '鄱阳湖', falseAnswer1 = '洪泽湖', falseAnswer2 = '太湖'}
SeniorQu[156] = {ID = 156, examType = 2, question = '韩浩:我随曹公征讨张鲁，张鲁是个劲敌，五斗米道也是个神秘的组织，主公你知道哪一点不是五斗米道的特色？', trueAnswerId = 1, trueAnswer = '符祝持九节杖', falseAnswer1 = '三官手书', falseAnswer2 = '静室思过'}
SeniorQu[157] = {ID = 157, examType = 2, question = '韩浩:孙权守宣城时被山贼攻破城池，当时是谁拼命救出孙权？', trueAnswerId = 1, trueAnswer = '周泰', falseAnswer1 = '黄盖', falseAnswer2 = '凌统'}
SeniorQu[158] = {ID = 158, examType = 2, question = '韩浩:所以我和枣祗建议曹公采取什么方式应对呢？', trueAnswerId = 1, trueAnswer = '屯田制', falseAnswer1 = '府兵制', falseAnswer2 = '募兵制'}
SeniorQu[159] = {ID = 159, examType = 2, question = '韩遂:是谁识破了姜维的长蛇卷地阵，救出了邓艾？', trueAnswerId = 1, trueAnswer = '司马望', falseAnswer1 = '钟会', falseAnswer2 = '夏侯霸'}
SeniorQu[160] = {ID = 160, examType = 2, question = '韩遂:以下几人中，父亲没有担任过三公的是哪位？', trueAnswerId = 1, trueAnswer = '崔琰', falseAnswer1 = '袁绍', falseAnswer2 = '杨修'}
SeniorQu[161] = {ID = 161, examType = 2, question = '韩遂:凉州羌人颇多，羌人内部族落也多，主公可知哪个羌人种在凉州境内？', trueAnswerId = 1, trueAnswer = '参狼种', falseAnswer1 = '黑水种', falseAnswer2 = '白马种'}
SeniorQu[162] = {ID = 162, examType = 2, question = '韩玄:关羽以哪位古人为例，以示自己一定要赴鲁肃在陆口所设之宴？', trueAnswerId = 1, trueAnswer = '蔺相如', falseAnswer1 = '苏秦', falseAnswer2 = '张仪'}
SeniorQu[163] = {ID = 163, examType = 2, question = '郝昭:当时是谁向曹操进言，袁绍便是因未立长子而导致最终失败？', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '荀彧', falseAnswer2 = '程昱'}
SeniorQu[164] = {ID = 164, examType = 2, question = '郝昭:不过只要有我郝伯道在，他就休想从陈仓城突破。这都已经是第几次出祁山进攻我们魏国了？', trueAnswerId = 1, trueAnswer = '第二次', falseAnswer1 = '第三次', falseAnswer2 = '第四次'}
SeniorQu[165] = {ID = 165, examType = 2, question = '郝萌:曹操见衣带诏,欲废掉汉献帝,是手下的谁劝阻了曹操', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '荀彧', falseAnswer2 = '郭嘉'}
SeniorQu[166] = {ID = 166, examType = 2, question = '侯成:你可知吕布的女儿原本是许了谁家的儿子', trueAnswerId = 1, trueAnswer = '袁术', falseAnswer1 = '孙坚', falseAnswer2 = '袁绍'}
SeniorQu[167] = {ID = 167, examType = 2, question = '侯成:听说南阳郭芝有一种九酝酒法，酿出来的酒可是极品，我找到一些秘方，麻烦主公帮我挑出错误的来。', trueAnswerId = 1, trueAnswer = '流水十石', falseAnswer1 = '曲三十斤', falseAnswer2 = '三日一酿'}
SeniorQu[168] = {ID = 168, examType = 2, question = '侯成:连环计中，是谁假传圣旨，把董卓从郿邬传至京城？', trueAnswerId = 1, trueAnswer = '李肃', falseAnswer1 = '王允', falseAnswer2 = '杨彪'}
SeniorQu[169] = {ID = 169, examType = 2, question = '侯成:姜维是在诸葛亮第几次北伐的时候投降的诸葛亮？', trueAnswerId = 1, trueAnswer = '第一次', falseAnswer1 = '第二次', falseAnswer2 = '第三次'}
SeniorQu[170] = {ID = 170, examType = 2, question = '胡车儿:你可知我主突袭曹操，斩杀其手下典韦，是用了谁的妙计吗？', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '李儒', falseAnswer2 = '陈宫'}
SeniorQu[171] = {ID = 171, examType = 2, question = '胡车儿:最近听说北方的夫余国很出名，地图上已经标了它的位置，主公看看有没有错误的地方？', trueAnswerId = 1, trueAnswer = '南接玄菟', falseAnswer1 = '东与挹娄', falseAnswer2 = '北有弱水'}
SeniorQu[172] = {ID = 172, examType = 2, question = '胡车儿:官渡攻城战中，献“发石车”图纸的是曹操手下哪位谋士？', trueAnswerId = 1, trueAnswer = '刘晔', falseAnswer1 = '郭嘉', falseAnswer2 = '满宠'}
SeniorQu[173] = {ID = 173, examType = 2, question = '胡车儿:建议孙权从吴迁都至秣陵的是谁？', trueAnswerId = 1, trueAnswer = '张纮', falseAnswer1 = '张昭', falseAnswer2 = '虞翻'}
SeniorQu[174] = {ID = 174, examType = 2, question = '华歆:我们三人关系甚好，被旁人称作“一龙”，主公您听说过这两位吗，这边有他们的名字吗？', trueAnswerId = 1, trueAnswer = '管宁', falseAnswer1 = '卢植', falseAnswer2 = '郑玄'}
SeniorQu[175] = {ID = 175, examType = 2, question = '华歆:三国猛将吕布的武器是什么？', trueAnswerId = 1, trueAnswer = '方天画戟', falseAnswer1 = '项羽刀', falseAnswer2 = '龙胆枪'}
SeniorQu[176] = {ID = 176, examType = 2, question = '华歆:下面这些事情，哪一件和我有关？', trueAnswerId = 1, trueAnswer = '割席分坐', falseAnswer1 = '舌战群儒', falseAnswer2 = '单刀赴会'}
SeniorQu[177] = {ID = 177, examType = 2, question = '华雄:迁都时董太师差使吕奉先发掘帝陵，吕奉先不曾挖了何人之陵墓？', trueAnswerId = 1, trueAnswer = '孝献皇帝', falseAnswer1 = '孝恒皇帝', falseAnswer2 = '孝灵皇帝'}
SeniorQu[178] = {ID = 178, examType = 2, question = '华雄:“千里草，何青青。十日卜，不得生。”这童谣究竟是指向谁呢？', trueAnswerId = 1, trueAnswer = '董卓', falseAnswer1 = '曹操', falseAnswer2 = '袁术'}
SeniorQu[179] = {ID = 179, examType = 2, question = '华雄:下列哪一部著作是邓艾撰写过的关于水利灌溉的书籍？', trueAnswerId = 1, trueAnswer = '《济河论》', falseAnswer1 = '《治江论》', falseAnswer2 = '《平河论》'}
SeniorQu[180] = {ID = 180, examType = 2, question = '华佗:我倒是传授了一些医术给别人，主公要寻医问药，可别找错人了。', trueAnswerId = 1, trueAnswer = '樊阿', falseAnswer1 = '张仲景', falseAnswer2 = '董奉'}
SeniorQu[181] = {ID = 181, examType = 2, question = '华佗:“金木水火土” 相生相克 请问金克制那一行？', trueAnswerId = 1, trueAnswer = '木', falseAnswer1 = '水', falseAnswer2 = '土'}
SeniorQu[182] = {ID = 182, examType = 2, question = '华佗:谁是白马将军?', trueAnswerId = 1, trueAnswer = '公孙瓒', falseAnswer1 = '公孙越', falseAnswer2 = '赵云'}
SeniorQu[183] = {ID = 183, examType = 2, question = '黄忠:古人就没我这么好运，主公知否，有哪位名将，因年老而不得君王重用？', trueAnswerId = 1, trueAnswer = '廉颇', falseAnswer1 = '李广', falseAnswer2 = '白起'}
SeniorQu[184] = {ID = 184, examType = 2, question = '黄忠:赵云见袁绍无忠君救民之心而出走投奔了何人？', trueAnswerId = 1, trueAnswer = '公孙瓒', falseAnswer1 = '袁术', falseAnswer2 = '公孙越'}
SeniorQu[185] = {ID = 185, examType = 2, question = '黄忠:古往今来，箭术名家也是层出不穷。“百步穿杨”这个成语，说的是下列哪位箭术大家呢？', trueAnswerId = 1, trueAnswer = '养由基', falseAnswer1 = '李广', falseAnswer2 = '吕布'}
SeniorQu[186] = {ID = 186, examType = 2, question = '黄盖:当时情况危急，我出任太守入平城平乱，平定武陵蛮夷时，郡兵人数又有多少？', trueAnswerId = 1, trueAnswer = '五百', falseAnswer1 = '六百', falseAnswer2 = '七百'}
SeniorQu[187] = {ID = 187, examType = 2, question = '黄盖:你看下列四对组合中，哪一组是我都效命过的主公？', trueAnswerId = 1, trueAnswer = '孙策、孙权', falseAnswer1 = '袁绍、孙权', falseAnswer2 = '曹操、孙坚'}
SeniorQu[188] = {ID = 188, examType = 2, question = '黄盖:泰山四寇中谁没有归顺曹操？', trueAnswerId = 1, trueAnswer = '昌豨', falseAnswer1 = '孙观', falseAnswer2 = '尹礼'}
SeniorQu[189] = {ID = 189, examType = 2, question = '黄盖:找到传国玉玺的是何人？', trueAnswerId = 1, trueAnswer = '孙坚', falseAnswer1 = '袁术', falseAnswer2 = '曹操'}
SeniorQu[190] = {ID = 190, examType = 2, question = '黄祖:煮酒论英雄时，曹操认为天下能称作是英雄的除了自己，还有谁？', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '袁绍', falseAnswer2 = '刘表'}
SeniorQu[191] = {ID = 191, examType = 2, question = '黄祖:跟张飞对战的是谁？', trueAnswerId = 1, trueAnswer = '马超', falseAnswer1 = '马岱', falseAnswer2 = '庞德'}
SeniorQu[192] = {ID = 192, examType = 2, question = '黄月英:听闻上古轩辕氏创立卧机阵，后为八卦阵。八卦本一，非物象。八阵名称为旗号、幡号、队伍之别。幡号为何？', trueAnswerId = 1, trueAnswer = '风、云', falseAnswer1 = '风、火', falseAnswer2 = '云、火'}
SeniorQu[193] = {ID = 193, examType = 2, question = '黄月英:主公可知下列东西中，哪一件不是我夫君的杰作呢？', trueAnswerId = 1, trueAnswer = '梨花枪', falseAnswer1 = '木流牛马', falseAnswer2 = '诸葛连弩'}
SeniorQu[194] = {ID = 194, examType = 2, question = '黄月英:”上不飞天汉,下不见于田“是谁所写', trueAnswerId = 1, trueAnswer = '曹髦', falseAnswer1 = '曹休', falseAnswer2 = '曹芳'}
SeniorQu[195] = {ID = 195, examType = 2, question = '黄月英:汉献帝认刘备为皇叔时，封予他什么官职？', trueAnswerId = 1, trueAnswer = '左将军', falseAnswer1 = '右将军', falseAnswer2 = '中郎将'}
SeniorQu[196] = {ID = 196, examType = 2, question = '纪灵:主子当皇帝，我们属下也能获得高迁，没什么不好。我也该学习一下礼制，主公了解诸侯可用的礼制吗？', trueAnswerId = 1, trueAnswer = '七鼎六簋', falseAnswer1 = '五鼎四簋', falseAnswer2 = '三鼎一簋'}
SeniorQu[197] = {ID = 197, examType = 2, question = '纪灵:荀彧和荀攸是曹操的两位重要谋士，请问他们是什么关系？', trueAnswerId = 1, trueAnswer = '叔侄', falseAnswer1 = '父子', falseAnswer2 = '兄弟'}
SeniorQu[198] = {ID = 198, examType = 2, question = '纪灵:刘备被蔡瑁追杀，还能得贵人收留。那贵人是谁，你知道吗？', trueAnswerId = 1, trueAnswer = '司马徽', falseAnswer1 = '黄承彦', falseAnswer2 = '庞德公'}
SeniorQu[199] = {ID = 199, examType = 2, question = '姜维:孔融是孔子的第几世孙？', trueAnswerId = 1, trueAnswer = '二十世', falseAnswer1 = '十九世', falseAnswer2 = '十八世'}
SeniorQu[200] = {ID = 200, examType = 2, question = '姜维:我好郑氏学，古往今来学识郑康成无所不通。主公知否，郑康成不曾从京兆第五元先处学到的学问？', trueAnswerId = 1, trueAnswer = '左氏春秋', falseAnswer1 = '京氏易', falseAnswer2 = '公羊春秋'}
SeniorQu[201] = {ID = 201, examType = 2, question = '蒋琬:三国中，被称为凤雏的人是谁？', trueAnswerId = 1, trueAnswer = '庞统', falseAnswer1 = '徐庶', falseAnswer2 = '诸葛亮'}
SeniorQu[202] = {ID = 202, examType = 2, question = '蒋琬:丞相和先帝隆中对策，定下三分天下之计，你可知丞相劝先帝图谋哪个地方？', trueAnswerId = 1, trueAnswer = '蜀', falseAnswer1 = '魏', falseAnswer2 = '吴'}
SeniorQu[203] = {ID = 203, examType = 2, question = '蒋干:诸葛亮所造的木牛流马机关在哪个位置？', trueAnswerId = 1, trueAnswer = '舌头', falseAnswer1 = '耳朵', falseAnswer2 = '尾巴'}
SeniorQu[204] = {ID = 204, examType = 2, question = '沮授:我们顺利劝服他将州牧之位出让给袁本初，我们也能在袁本初手下做事，主公可知我在韩馥手下的官职？', trueAnswerId = 1, trueAnswer = '骑督尉', falseAnswer1 = '从事', falseAnswer2 = '奋威将'}
SeniorQu[205] = {ID = 205, examType = 2, question = '沮授:最早预言曹操“将来能安天下”的是谁？', trueAnswerId = 1, trueAnswer = '何颙', falseAnswer1 = '孔融', falseAnswer2 = '荀爽'}
SeniorQu[206] = {ID = 206, examType = 2, question = '简雍:刘封在成为刘备义子前，他姓什么？', trueAnswerId = 1, trueAnswer = '寇', falseAnswer1 = '孙', falseAnswer2 = '杨'}
SeniorQu[207] = {ID = 207, examType = 2, question = '贾诩:下列诸人中，哪一位不在“曹魏五谋臣”的行列之中？', trueAnswerId = 1, trueAnswer = '杨修', falseAnswer1 = '贾诩', falseAnswer2 = '郭嘉'}
SeniorQu[208] = {ID = 208, examType = 2, question = '贾诩:我后人论及家世，当不至于低人一等。而三公之位，绝非所有的名门望族都可担任。下面谁家族是四世三公？', trueAnswerId = 1, trueAnswer = '袁绍', falseAnswer1 = '曹操', falseAnswer2 = '孙坚'}
SeniorQu[209] = {ID = 209, examType = 2, question = '贾诩:李傕为了获得军事上的援助，拜谁为左将军，假节？', trueAnswerId = 1, trueAnswer = '袁术', falseAnswer1 = '孙坚', falseAnswer2 = '张绣'}
SeniorQu[210] = {ID = 210, examType = 2, question = '金旋:关羽曾经想从荆州入川与谁比试武艺', trueAnswerId = 1, trueAnswer = '马超', falseAnswer1 = '黄忠', falseAnswer2 = '严颜'}
SeniorQu[211] = {ID = 211, examType = 2, question = '阚泽:与二十八宿合称“三垣二十八宿”的“三垣”不包括下面哪个？', trueAnswerId = 1, trueAnswer = '庚垣', falseAnswer1 = '紫微垣', falseAnswer2 = '太微垣'}
SeniorQu[212] = {ID = 212, examType = 2, question = '阚泽:九品官人法的创始者是谁？', trueAnswerId = 1, trueAnswer = '陈群', falseAnswer1 = '陈登', falseAnswer2 = '荀攸'}
SeniorQu[213] = {ID = 213, examType = 2, question = '蒯良:下列诸人中，谁的生卒年和诸葛亮重合？', trueAnswerId = 1, trueAnswer = '汉献帝', falseAnswer1 = '曹丕', falseAnswer2 = '曹植'}
SeniorQu[214] = {ID = 214, examType = 2, question = '蒯良:你知道刘备之前的徐州牧是谁么？', trueAnswerId = 1, trueAnswer = '陶谦', falseAnswer1 = '吕布', falseAnswer2 = '刘虞'}
SeniorQu[215] = {ID = 215, examType = 2, question = '蒯越:典韦在侍奉曹操之前，为谁效力？', trueAnswerId = 1, trueAnswer = '张邈', falseAnswer1 = '袁绍', falseAnswer2 = '袁术'}
SeniorQu[216] = {ID = 216, examType = 2, question = '蒯越:藤甲兵的统帅是谁？', trueAnswerId = 1, trueAnswer = '兀突骨', falseAnswer1 = '孟获', falseAnswer2 = '孟优'}
SeniorQu[217] = {ID = 217, examType = 2, question = '孔融:我幼年时得到过天才的名号，几十年来也见过不少的神童，早夭的也有不少，主公听说过吗？', trueAnswerId = 1, trueAnswer = '曹仓舒', falseAnswer1 = '郭奉孝', falseAnswer2 = '杨修'}
SeniorQu[218] = {ID = 218, examType = 2, question = '孔融:十八路诸侯讨伐董卓，盟主是', trueAnswerId = 1, trueAnswer = '袁绍', falseAnswer1 = '孙坚', falseAnswer2 = '曹操'}
SeniorQu[219] = {ID = 219, examType = 2, question = '乐进:八门金锁阵为谁所破？', trueAnswerId = 1, trueAnswer = '徐庶', falseAnswer1 = '诸葛亮', falseAnswer2 = '庞统'}
SeniorQu[220] = {ID = 220, examType = 2, question = '乐进:下列哪一本不属于兵家著作？', trueAnswerId = 1, trueAnswer = '《随巢子》', falseAnswer1 = '《孙子兵法》', falseAnswer2 = '《孟德新书》'}
SeniorQu[221] = {ID = 221, examType = 2, question = '泠苞:当日我主刘璋谴法正请刘备入蜀，是谁倒悬于州门以谏，刘璋却坚持不肯听从谏言？', trueAnswerId = 1, trueAnswer = '王累', falseAnswer1 = '张松', falseAnswer2 = '黄权'}
SeniorQu[222] = {ID = 222, examType = 2, question = '泠苞:汉灵帝的母亲是谁？', trueAnswerId = 1, trueAnswer = '董太后', falseAnswer1 = '何太后', falseAnswer2 = '王美人'}
SeniorQu[223] = {ID = 223, examType = 2, question = '泠苞:不过也难说曹操这人不好，他的封赏很丰厚，主公您清楚曹操封了刘季玉什么将军吗？', trueAnswerId = 1, trueAnswer = '振威将军', falseAnswer1 = '奋威将军', falseAnswer2 = '平寇将军'}
SeniorQu[224] = {ID = 224, examType = 2, question = '泠苞:潼关之战，曹操手下的谁提出离间马超和韩遂之间关系的计谋？', trueAnswerId = 1, trueAnswer = '贾诩', falseAnswer1 = '郭嘉', falseAnswer2 = '荀彧'}
SeniorQu[225] = {ID = 225, examType = 2, question = '李典:成德是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '扬州', falseAnswer1 = '荆州', falseAnswer2 = '并州'}
SeniorQu[226] = {ID = 226, examType = 2, question = '李典:哪一部著作不属于春秋三传？', trueAnswerId = 1, trueAnswer = '尔雅', falseAnswer1 = '公羊传', falseAnswer2 = '谷梁传'}
SeniorQu[227] = {ID = 227, examType = 2, question = '李傕:下列这些军队中，哪一支是听从董大人调遣的？', trueAnswerId = 1, trueAnswer = '飞熊军', falseAnswer1 = '解烦军', falseAnswer2 = '白毦兵'}
SeniorQu[228] = {ID = 228, examType = 2, question = '李傕:诸葛亮南征时赵云杀死了以下哪一位南蛮武将？', trueAnswerId = 1, trueAnswer = '金环三结', falseAnswer1 = '董荼那', falseAnswer2 = '阿会喃'}
SeniorQu[229] = {ID = 229, examType = 2, question = '李儒:譬如你要去游说杜预，你知道他喜好什么吗？', trueAnswerId = 1, trueAnswer = '左传', falseAnswer1 = '诗经', falseAnswer2 = '韩非子'}
SeniorQu[230] = {ID = 230, examType = 2, question = '李严:汉献帝几岁登基？', trueAnswerId = 1, trueAnswer = '六岁', falseAnswer1 = '七岁', falseAnswer2 = '八岁'}
SeniorQu[231] = {ID = 231, examType = 2, question = '李严:那么其中的御指的是什么呢？', trueAnswerId = 1, trueAnswer = '驾车', falseAnswer1 = '骑马', falseAnswer2 = '抬轿'}
SeniorQu[232] = {ID = 232, examType = 2, question = '凌统:我父亲凌操先登进入夏口，斩杀黄祖的先锋。轻舟独进，中箭矢而死。你可知杀害我父的仇人是谁？', trueAnswerId = 1, trueAnswer = '甘宁', falseAnswer1 = '关羽', falseAnswer2 = '黄祖'}
SeniorQu[233] = {ID = 233, examType = 2, question = '凌统:公孙瓒与袁绍一战中，建了什么楼抵抗袁绍进攻？', trueAnswerId = 1, trueAnswer = '易京楼', falseAnswer1 = '铜雀楼', falseAnswer2 = '岳阳楼'}
SeniorQu[234] = {ID = 234, examType = 2, question = '凌统:后来我得二子，皆承我当年神勇，犬子烈得以封侯，最终他被封为哪等侯位？', trueAnswerId = 1, trueAnswer = '亭侯', falseAnswer1 = '乡侯', falseAnswer2 = '县侯'}
SeniorQu[235] = {ID = 235, examType = 2, question = '凌统:关羽和张飞分别义释过谁？', trueAnswerId = 1, trueAnswer = '黄忠及严颜', falseAnswer1 = '李严及严颜', falseAnswer2 = '黄忠及李严'}
SeniorQu[236] = {ID = 236, examType = 2, question = '梁习:你可知道曹操在讨伐黄巾军的时候，担任的是什么官职吗？', trueAnswerId = 1, trueAnswer = '骑都尉', falseAnswer1 = '典军校尉', falseAnswer2 = '监军'}
SeniorQu[237] = {ID = 237, examType = 2, question = '梁习:是谁向曹操建议把周瑜封为南郡太守？', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '荀彧', falseAnswer2 = '郭嘉'}
SeniorQu[238] = {ID = 238, examType = 2, question = '刘备:汉献帝之子刘协的生母是谁？', trueAnswerId = 1, trueAnswer = '王美人', falseAnswer1 = '何太后', falseAnswer2 = '东太后'}
SeniorQu[239] = {ID = 239, examType = 2, question = '刘备:主公可知道，我租上中山靖王刘胜，是哪位皇帝的儿子？', trueAnswerId = 1, trueAnswer = '孝景皇帝', falseAnswer1 = '孝献皇帝', falseAnswer2 = '孝灵皇帝'}
SeniorQu[240] = {ID = 240, examType = 2, question = '刘封:以下三人中，过世最早的人是谁？', trueAnswerId = 1, trueAnswer = '周瑜', falseAnswer1 = '鲁肃', falseAnswer2 = '关羽'}
SeniorQu[241] = {ID = 241, examType = 2, question = '刘封:樊城之战中，命令弓箭手使用涂毒的箭矢射击关羽的武将是谁？', trueAnswerId = 1, trueAnswer = '曹仁', falseAnswer1 = '曹洪', falseAnswer2 = '夏侯惇'}
SeniorQu[242] = {ID = 242, examType = 2, question = '刘晔:我听闻终南山上有一个叫“梦梅居士”的道士，本事很高，你知道他的名字吗？', trueAnswerId = 1, trueAnswer = '娄子伯', falseAnswer1 = '左慈', falseAnswer2 = '于吉'}
SeniorQu[243] = {ID = 243, examType = 2, question = '刘晔:下列诸人中，哪二人曾为祢衡所称道？', trueAnswerId = 1, trueAnswer = '杨修、孔融', falseAnswer1 = '杨修、许攸', falseAnswer2 = '孔融、许攸'}
SeniorQu[244] = {ID = 244, examType = 2, question = '刘琮:在诸葛亮的出师表中提到“先帝称之曰能”的是谁？', trueAnswerId = 1, trueAnswer = '向宠', falseAnswer1 = '糜竺', falseAnswer2 = '简雍'}
SeniorQu[245] = {ID = 245, examType = 2, question = '刘璝:“人情势利古犹今，谁识英雄是白身”这句话指的是谁？', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '吕布', falseAnswer2 = '张角'}
SeniorQu[246] = {ID = 246, examType = 2, question = '刘表:然而我们刘氏不会甘居人后，今年我们宗室便有三人担任不同州的州牧，哪个州并不包括在内？', trueAnswerId = 1, trueAnswer = '冀州', falseAnswer1 = '益州', falseAnswer2 = '并州'}
SeniorQu[247] = {ID = 247, examType = 2, question = '刘表:来来来，老夫来考较考较你。“君子之道,淡而不厌,简而文,温而理。”这一句你可知出自哪里？', trueAnswerId = 1, trueAnswer = '《大学》', falseAnswer1 = '《春秋》', falseAnswer2 = '《左传》'}
SeniorQu[248] = {ID = 248, examType = 2, question = '刘表:魏蜀吴三国中，谁是在位时间最长的皇帝？', trueAnswerId = 1, trueAnswer = '刘禅', falseAnswer1 = '曹丕', falseAnswer2 = '孙皓'}
SeniorQu[249] = {ID = 249, examType = 2, question = '刘琦:赤壁之战时，担任东吴军副都督的人是谁？', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '黄盖', falseAnswer2 = '韩当'}
SeniorQu[250] = {ID = 250, examType = 2, question = '刘度:关羽与曹操约定中的第一条是什么？', trueAnswerId = 1, trueAnswer = '降汉不降曹', falseAnswer1 = '皇叔俸禄给予两嫂', falseAnswer2 = '得知刘备去向，就告辞。'}
SeniorQu[251] = {ID = 251, examType = 2, question = '刘繇:关羽平生最喜欢读的书时哪一本？', trueAnswerId = 1, trueAnswer = '《春秋》', falseAnswer1 = '《大学》', falseAnswer2 = '《左传》'}
SeniorQu[252] = {ID = 252, examType = 2, question = '鲁肃:皇帝刘协同曹操一帮大臣田猎时，用的什么弓？', trueAnswerId = 1, trueAnswer = '宝雕弓', falseAnswer1 = '麒麟弓', falseAnswer2 = '龙舌弓'}
SeniorQu[253] = {ID = 253, examType = 2, question = '陆抗:哪件事中，以下这四人中，哪一人曾落井下石，造谣我父对东吴不忠？', trueAnswerId = 1, trueAnswer = '杨竺', falseAnswer1 = '虞翻', falseAnswer2 = '张昭'}
SeniorQu[254] = {ID = 254, examType = 2, question = '陆抗:曹操的铜雀台建在哪条河的河畔？', trueAnswerId = 1, trueAnswer = '漳河', falseAnswer1 = '淮河', falseAnswer2 = '黄河'}
SeniorQu[255] = {ID = 255, examType = 2, question = '陆逊:从兵法角度上来讲，你可知公瑾用的是哪一计，杀死了蔡瑁、张允。', trueAnswerId = 1, trueAnswer = '借刀杀人', falseAnswer1 = '反间计', falseAnswer2 = '声东击西'}
SeniorQu[256] = {ID = 256, examType = 2, question = '陆逊:吴郡四姓各有各的家世品格，主公可知我们陆氏最突出的品格？', trueAnswerId = 1, trueAnswer = '忠', falseAnswer1 = '义', falseAnswer2 = '廉'}
SeniorQu[257] = {ID = 257, examType = 2, question = '陆绩:诸葛亮草船借箭，是利用了什么样的天气？', trueAnswerId = 1, trueAnswer = '大雾', falseAnswer1 = '大风', falseAnswer2 = '大雨'}
SeniorQu[258] = {ID = 258, examType = 2, question = '骆统:“煮酒论英雄”时，刘备借什么自然现象掩饰自己内心的震惊？', trueAnswerId = 1, trueAnswer = '雷电', falseAnswer1 = '狂风', falseAnswer2 = '暴雨'}
SeniorQu[259] = {ID = 259, examType = 2, question = '骆统:关羽封金挂印离开曹操去投刘备时，谁建议曹操斩杀关羽？', trueAnswerId = 1, trueAnswer = '程昱', falseAnswer1 = '贾诩', falseAnswer2 = '郭嘉'}
SeniorQu[260] = {ID = 260, examType = 2, question = '吕岱:是谁在落凤坡射杀了庞统？', trueAnswerId = 1, trueAnswer = '张任', falseAnswer1 = '张绣', falseAnswer2 = '严颜'}
SeniorQu[261] = {ID = 261, examType = 2, question = '吕岱:后来审配代替袁本初写下遗书，让哪一位公子继承爵位？', trueAnswerId = 1, trueAnswer = '袁尚', falseAnswer1 = '袁熙', falseAnswer2 = '袁谭'}
SeniorQu[262] = {ID = 262, examType = 2, question = '吕布:刘琮投降曹操前，蔡瑁告知曹操荆州的军马共有多少？', trueAnswerId = 1, trueAnswer = '二十八万', falseAnswer1 = '三十万', falseAnswer2 = '五十万'}
SeniorQu[263] = {ID = 263, examType = 2, question = '吕布:你可知，下列官职中，哪一个不属于“三司”？', trueAnswerId = 1, trueAnswer = '太师', falseAnswer1 = '司空', falseAnswer2 = '司徒'}
SeniorQu[264] = {ID = 264, examType = 2, question = '吕布:赤兔得来不易，在得到赤兔之前我曾研读《相马经》，主公可知何种形象不是神驹之状', trueAnswerId = 1, trueAnswer = '虎', falseAnswer1 = '兔', falseAnswer2 = '鹰'}
SeniorQu[265] = {ID = 265, examType = 2, question = '吕蒙:《易》有三，分别为《周易》、《连山》、《归藏》，你可知这三部书，哪一部最早呢？', trueAnswerId = 1, trueAnswer = '连山', falseAnswer1 = '周易', falseAnswer2 = '归藏'}
SeniorQu[266] = {ID = 266, examType = 2, question = '吕蒙:仲谋是好读书，犹好三史，历朝史书中不为三史的是哪一部？', trueAnswerId = 1, trueAnswer = '左传', falseAnswer1 = '史记', falseAnswer2 = '汉书'}
SeniorQu[267] = {ID = 267, examType = 2, question = '吕蒙:天子田猎时，刘备射中了什么动物？', trueAnswerId = 1, trueAnswer = '兔', falseAnswer1 = '鸡', falseAnswer2 = '狐'}
SeniorQu[268] = {ID = 268, examType = 2, question = '吕蒙:不属于董卓讨伐战十八路路诸侯中任意一员的是何人？', trueAnswerId = 1, trueAnswer = '刘表', falseAnswer1 = '孙坚', falseAnswer2 = '袁绍'}
SeniorQu[269] = {ID = 269, examType = 2, question = '吕翔:当孙权在犹豫是否降曹时，吴国太提醒他去听谁的意见？', trueAnswerId = 1, trueAnswer = '周瑜', falseAnswer1 = '张昭', falseAnswer2 = '黄盖'}
SeniorQu[270] = {ID = 270, examType = 2, question = '雷铜:关羽的籍贯在今天的什么省？', trueAnswerId = 1, trueAnswer = '山西', falseAnswer1 = '江苏', falseAnswer2 = '河北'}
SeniorQu[271] = {ID = 271, examType = 2, question = '雷铜:诸葛亮和司马懿对阵中送了什么给司马懿挑衅他？', trueAnswerId = 1, trueAnswer = '凤冠霞帔', falseAnswer1 = '围巾', falseAnswer2 = '裙子'}
SeniorQu[272] = {ID = 272, examType = 2, question = '卢植:以下何人被描述为“身长七尺七寸，美须髯，独臂善射。弦不虚发。”？', trueAnswerId = 1, trueAnswer = '太史慈', falseAnswer1 = '甘宁', falseAnswer2 = '凌统'}
SeniorQu[273] = {ID = 273, examType = 2, question = '马休:以下诸人中，谁自称“才高八斗”？', trueAnswerId = 1, trueAnswer = '曹植', falseAnswer1 = '曹彰', falseAnswer2 = '曹丕'}
SeniorQu[274] = {ID = 274, examType = 2, question = '马忠:街亭之战前，谁向马谡建议不要在山上进行布阵，而马谡无视了他？', trueAnswerId = 1, trueAnswer = '王平', falseAnswer1 = '魏延', falseAnswer2 = '马岱'}
SeniorQu[275] = {ID = 275, examType = 2, question = '马铁:赤壁之战中谁没有参与苦肉计', trueAnswerId = 1, trueAnswer = '凌统', falseAnswer1 = '黄盖', falseAnswer2 = '周瑜'}
SeniorQu[276] = {ID = 276, examType = 2, question = '马腾:凉州是我马家的归属。凉州历任刺史中，有一人既任凉州刺史，又辖益州，他是谁？', trueAnswerId = 1, trueAnswer = '钟劭', falseAnswer1 = '韩遂', falseAnswer2 = '韦端'}
SeniorQu[277] = {ID = 277, examType = 2, question = '马腾:董卓生前风光，死后却是被万人唾弃，唯有一人，敢在他尸体上痛哭，你可知是谁？', trueAnswerId = 1, trueAnswer = '蔡邕', falseAnswer1 = '李儒', falseAnswer2 = '胡车儿'}
SeniorQu[278] = {ID = 278, examType = 2, question = '马腾:曹操中了公瑾之计而误斩张允蔡冒后，改任哪两人做水军都督？', trueAnswerId = 1, trueAnswer = '毛玠和于禁', falseAnswer1 = '毛玠和徐晃', falseAnswer2 = '于禁和徐晃'}
SeniorQu[279] = {ID = 279, examType = 2, question = '马超:孙坚四将中最早离世的是谁？', trueAnswerId = 1, trueAnswer = '祖茂', falseAnswer1 = '黄盖', falseAnswer2 = '程普'}
SeniorQu[280] = {ID = 280, examType = 2, question = '马超:三辅自古又称为“三秦”，请问下列这些地方，哪些地方不属于三辅地区？', trueAnswerId = 1, trueAnswer = '河内', falseAnswer1 = '京兆', falseAnswer2 = '右扶风'}
SeniorQu[281] = {ID = 281, examType = 2, question = '马超:我儿秋被张鲁所害，最后只剩下一个女儿，嫁于梁王为妻。主公可知小婿刘理何时被封安平王？', trueAnswerId = 1, trueAnswer = '建兴八年', falseAnswer1 = '建兴九年', falseAnswer2 = '建兴十年'}
SeniorQu[282] = {ID = 282, examType = 2, question = '马岱:临终之时，丞相尚念念不忘国事，主公可知丞相最放心不下的是哪一位人谋反吗？', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '马岱', falseAnswer2 = '费祎'}
SeniorQu[283] = {ID = 283, examType = 2, question = '马岱:曹操同济北相鲍信一道破贼后组建的精锐部队是哪一支？', trueAnswerId = 1, trueAnswer = '青州兵', falseAnswer1 = '并州兵', falseAnswer2 = '冀州兵'}
SeniorQu[284] = {ID = 284, examType = 2, question = '马岱:马家并非马姓，因先祖被封为马服君，后人均称马氏。主公可知这位马家先祖是何人？', trueAnswerId = 1, trueAnswer = '赵奢', falseAnswer1 = '廉颇', falseAnswer2 = '白起'}
SeniorQu[285] = {ID = 285, examType = 2, question = '马岱:十八路诸侯讨伐董卓时，北平太守公孙瓒统领多少兵马？', trueAnswerId = 1, trueAnswer = '一万五千', falseAnswer1 = '一万二千', falseAnswer2 = '一万八千'}
SeniorQu[286] = {ID = 286, examType = 2, question = '马良:濮阳攻城战中，曹操军中由谁想到了将计就计的方法反败为胜？', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '郭嘉', falseAnswer2 = '程昱'}
SeniorQu[287] = {ID = 287, examType = 2, question = '马良:几十年前，朝廷增五溪蛮租赋以致反叛，主公可知此次叛乱发生于何年？', trueAnswerId = 1, trueAnswer = '永和元年', falseAnswer1 = '永和一年', falseAnswer2 = '永和二年'}
SeniorQu[288] = {ID = 288, examType = 2, question = '马良:从前乡里人叫我们兄弟“马氏五常”，又说我“白眉最良”，主公可知道白眉指的是我的是什么吗？', trueAnswerId = 1, trueAnswer = '外貌', falseAnswer1 = '名字', falseAnswer2 = '身材'}
SeniorQu[289] = {ID = 289, examType = 2, question = '马良:司马昭死后姜维伐魏，谁曾屡次劝他适可而止？', trueAnswerId = 1, trueAnswer = '廖化', falseAnswer1 = '马岱', falseAnswer2 = '费祎'}
SeniorQu[290] = {ID = 290, examType = 2, question = '马谡:诸葛公在兵书中写到多种将领之材，主公可知“宽而能刚，勇而多计”为何种将材？', trueAnswerId = 1, trueAnswer = '大将', falseAnswer1 = '礼将', falseAnswer2 = '信将'}
SeniorQu[291] = {ID = 291, examType = 2, question = '马谡:主公可曾熟读兵书么？主公可知，三十六计中，第五计是哪一计？', trueAnswerId = 1, trueAnswer = '趁火打劫', falseAnswer1 = '走为上计', falseAnswer2 = '围魏救赵'}
SeniorQu[292] = {ID = 292, examType = 2, question = '马谡:陶谦托付刘备徐州时，推荐了谁担任刘备的辅官？', trueAnswerId = 1, trueAnswer = '孙乾', falseAnswer1 = '简雍', falseAnswer2 = '糜竺'}
SeniorQu[293] = {ID = 293, examType = 2, question = '糜芳:群英会上，称孔明“好为大言，未必真有实学”的东吴谋士是谁？', trueAnswerId = 1, trueAnswer = '程德枢', falseAnswer1 = '张昭', falseAnswer2 = '虞翻'}
SeniorQu[294] = {ID = 294, examType = 2, question = '糜兰:与曹仁的女儿结婚的孙姓武将是？', trueAnswerId = 1, trueAnswer = '孙匡', falseAnswer1 = '孙皓', falseAnswer2 = '孙休'}
SeniorQu[295] = {ID = 295, examType = 2, question = '糜兰:在刘璋与刘备得酒宴上，谁舞剑欲伺机杀死刘璋，但没有成功。', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '张飞', falseAnswer2 = '文聘'}
SeniorQu[296] = {ID = 296, examType = 2, question = '满宠:下列不属于三国时期战役的是？', trueAnswerId = 1, trueAnswer = '江陵攻城战', falseAnswer1 = '赤壁之战', falseAnswer2 = '官渡之战'}
SeniorQu[297] = {ID = 297, examType = 2, question = '满宠:试问下列诸人中不属于法家的是谁？', trueAnswerId = 1, trueAnswer = '杨朱', falseAnswer1 = '韩非子', falseAnswer2 = '李斯'}
SeniorQu[298] = {ID = 298, examType = 2, question = '孟获:诸葛孔明入川时候，用了什么计谋擒住了张任？', trueAnswerId = 1, trueAnswer = '十面埋伏', falseAnswer1 = '声东击西', falseAnswer2 = '围魏救赵'}
SeniorQu[299] = {ID = 299, examType = 2, question = '孟获:曹操和袁绍争夺北方霸权的一场决战叫什么名字？', trueAnswerId = 1, trueAnswer = '官渡攻城战', falseAnswer1 = '宛城之战', falseAnswer2 = '扬州之战'}
SeniorQu[300] = {ID = 300, examType = 2, question = '孟达:“帝非帝，王非王，千乘万骑走北邙”是哪里传出来的童谣？', trueAnswerId = 1, trueAnswer = '洛阳', falseAnswer1 = '长安', falseAnswer2 = '许都'}
SeniorQu[301] = {ID = 301, examType = 2, question = '孟达:刘备在小沛一战中败给吕布后逃跑，是谁出面与吕布交涉，保护刘备的妻子？', trueAnswerId = 1, trueAnswer = '糜竺', falseAnswer1 = '关羽', falseAnswer2 = '张飞'}
SeniorQu[302] = {ID = 302, examType = 2, question = '牛辅:是谁劝说并阻止刘封救援关羽？', trueAnswerId = 1, trueAnswer = '孟达', falseAnswer1 = '李严', falseAnswer2 = '简雍'}
SeniorQu[303] = {ID = 303, examType = 2, question = '潘璋:官渡攻城战中，袁绍方面的谁投靠了曹操，而使得曹操获得了胜利？', trueAnswerId = 1, trueAnswer = '许攸', falseAnswer1 = '沮授', falseAnswer2 = '审配'}
SeniorQu[304] = {ID = 304, examType = 2, question = '庞德:汉昌是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '益州', falseAnswer1 = '荆州', falseAnswer2 = '扬州'}
SeniorQu[305] = {ID = 305, examType = 2, question = '麹义:庞统期初没有受到重用的原因是什么？', trueAnswerId = 1, trueAnswer = '太丑', falseAnswer1 = '太矮', falseAnswer2 = '太胖'}
SeniorQu[306] = {ID = 306, examType = 2, question = '沙摩柯:许多年前，东吴有个很有名的少年英雄，大名叫做孙策，你可知道他的外号？', trueAnswerId = 1, trueAnswer = '小霸王', falseAnswer1 = '小魔王', falseAnswer2 = '麒麟子'}
SeniorQu[307] = {ID = 307, examType = 2, question = '沙摩柯:三国时期，孙吴所在的江东属于哪个州？', trueAnswerId = 1, trueAnswer = '扬州', falseAnswer1 = '荆州', falseAnswer2 = '益州'}
SeniorQu[308] = {ID = 308, examType = 2, question = '沙摩柯:不说他了，俺们巴郡南郡有五姓，都出自五落钟离山，主公知不知道，哪一姓是生于赤穴的？', trueAnswerId = 1, trueAnswer = '巴氏', falseAnswer1 = '樊氏', falseAnswer2 = '郑氏'}
SeniorQu[309] = {ID = 309, examType = 2, question = '审配:下列诸人中，谁的书法造诣最高？', trueAnswerId = 1, trueAnswer = '钟繇', falseAnswer1 = '孔融', falseAnswer2 = '郑玄'}
SeniorQu[310] = {ID = 310, examType = 2, question = '审配:以下诸人中，谁好梦中杀人？', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '刘备', falseAnswer2 = '孙权'}
SeniorQu[311] = {ID = 311, examType = 2, question = '司马懿:阆中是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '益州', falseAnswer1 = '并州', falseAnswer2 = '凉州'}
SeniorQu[312] = {ID = 312, examType = 2, question = '司马懿:我父亲有八个儿子，我排行第二。我兄弟众人的名字中，有一个字是一样的 主公可知是什么字？', trueAnswerId = 1, trueAnswer = '达', falseAnswer1 = '忠', falseAnswer2 = '武'}
SeniorQu[313] = {ID = 313, examType = 2, question = '司马懿:当我被曹睿革去兵权时，有谁信任我不会谋反？', trueAnswerId = 1, trueAnswer = '曹真', falseAnswer1 = '曹休', falseAnswer2 = '邓艾'}
SeniorQu[314] = {ID = 314, examType = 2, question = '宋宪:宋国是了不起的大国，国君曾为春秋五霸一员，主公知道这位国君是谁吗？', trueAnswerId = 1, trueAnswer = '宋襄公', falseAnswer1 = '宋桓公', falseAnswer2 = '宋成公'}
SeniorQu[315] = {ID = 315, examType = 2, question = '宋宪:诸葛亮死后蜀汉的丞相是谁？', trueAnswerId = 1, trueAnswer = '蒋琬', falseAnswer1 = '费祎', falseAnswer2 = '姜维'}
SeniorQu[316] = {ID = 316, examType = 2, question = '孙策:张绣的偏将胡车儿可日行几百里？', trueAnswerId = 1, trueAnswer = '七百里', falseAnswer1 = '八百里', falseAnswer2 = '九百里'}
SeniorQu[317] = {ID = 317, examType = 2, question = '孙策:不过古往今来，春秋五霸的说法有好几种，下面哪一位不属于传统的春秋五霸的说法之中？', trueAnswerId = 1, trueAnswer = '秦孝公', falseAnswer1 = '秦襄公', falseAnswer2 = '秦穆公'}
SeniorQu[318] = {ID = 318, examType = 2, question = '孙策:扬州一带的郡守多是袁公路亲信，其中并非袁术任命的太守是谁？', trueAnswerId = 1, trueAnswer = '九江太守周昂', falseAnswer1 = '丹杨太守袁胤', falseAnswer2 = '广陵太守吴景'}
SeniorQu[319] = {ID = 319, examType = 2, question = '孙策:赤壁攻城战中，东吴方面献策诈降曹操的人是谁？', trueAnswerId = 1, trueAnswer = '黄盖', falseAnswer1 = '鲁肃', falseAnswer2 = '周瑜'}
SeniorQu[320] = {ID = 320, examType = 2, question = '孙权:名人铸造六柄宝剑，下列哪个是？', trueAnswerId = 1, trueAnswer = '白虹', falseAnswer1 = '青釭', falseAnswer2 = '倚天'}
SeniorQu[321] = {ID = 321, examType = 2, question = '孙权:魏帝以九锡之礼赏赐于孤，九锡中的这些人物，数目不对的是哪个？', trueAnswerId = 1, trueAnswer = '彤弓十彤矢百', falseAnswer1 = '玄牡二驷', falseAnswer2 = '虎贲百人'}
SeniorQu[322] = {ID = 322, examType = 2, question = '孙坚:我前后担任了三县县丞，与乡民感情深厚，主公知道哪一县不是这三县之内？', trueAnswerId = 1, trueAnswer = '高邮', falseAnswer1 = '盐渎', falseAnswer2 = '盱眙'}
SeniorQu[323] = {ID = 323, examType = 2, question = '孙坚:你且看，以下这些人中，哪位是最早就追随我左右的人？', trueAnswerId = 1, trueAnswer = '程普', falseAnswer1 = '周瑜', falseAnswer2 = '鲁肃'}
SeniorQu[324] = {ID = 324, examType = 2, question = '孙坚:臧霸在加入曹操帐下之前是什么贼寇的首领？', trueAnswerId = 1, trueAnswer = '泰山贼', falseAnswer1 = '黑山贼', falseAnswer2 = '没删贼'}
SeniorQu[325] = {ID = 325, examType = 2, question = '孙尚香:孙策借给袁术什么才同意借兵', trueAnswerId = 1, trueAnswer = '玉玺', falseAnswer1 = '虎符', falseAnswer2 = '玉鼎'}
SeniorQu[326] = {ID = 326, examType = 2, question = '孙尚香:赵夫人特别擅长女工，有三绝之称，非她三绝之一的才能是哪一项？', trueAnswerId = 1, trueAnswer = '绣绝', falseAnswer1 = '织锦', falseAnswer2 = '刺绣'}
SeniorQu[327] = {ID = 327, examType = 2, question = '孙尚香:被张飞打得曹豹是谁的丈人', trueAnswerId = 1, trueAnswer = '吕布', falseAnswer1 = '高顺', falseAnswer2 = '张辽'}
SeniorQu[328] = {ID = 328, examType = 2, question = '孙瑜:白马之战，杀死魏续、宋宪，斗败徐晃的武将是谁？', trueAnswerId = 1, trueAnswer = '颜良', falseAnswer1 = '文丑', falseAnswer2 = '高览'}
SeniorQu[329] = {ID = 329, examType = 2, question = '孙静:箭射陈生，力喝张虎的东吴猛将是谁？', trueAnswerId = 1, trueAnswer = '孙策', falseAnswer1 = '黄盖', falseAnswer2 = '程普'}
SeniorQu[330] = {ID = 330, examType = 2, question = '孙静:朱治与朱然是什么关系？', trueAnswerId = 1, trueAnswer = '舅甥', falseAnswer1 = '叔侄', falseAnswer2 = '父子'}
SeniorQu[331] = {ID = 331, examType = 2, question = '太史慈:自孙伯符占领江东之后，丹杨太守的位子几度更替，有一人两任其职，他是谁呢？', trueAnswerId = 1, trueAnswer = '吴景', falseAnswer1 = '周尚', falseAnswer2 = '孙翊'}
SeniorQu[332] = {ID = 332, examType = 2, question = '太史慈:那么近来人们口中传送的“江东二张”又是哪两位俊杰呢？', trueAnswerId = 1, trueAnswer = '张昭、张纮', falseAnswer1 = '张昭、张超', falseAnswer2 = '张纮、张超'}
SeniorQu[333] = {ID = 333, examType = 2, question = '陶谦:你可知灵帝继位后，是哪个宦官在把持朝政吗？', trueAnswerId = 1, trueAnswer = '曹节', falseAnswer1 = '张让', falseAnswer2 = '赵忠'}
SeniorQu[334] = {ID = 334, examType = 2, question = '陶谦:关羽身高多长？', trueAnswerId = 1, trueAnswer = '九尺', falseAnswer1 = '八尺', falseAnswer2 = '八尺五'}
SeniorQu[335] = {ID = 335, examType = 2, question = '田豫:孙策以进攻谁为名义向袁术抵押玉玺借兵？', trueAnswerId = 1, trueAnswer = '刘繇', falseAnswer1 = '袁绍', falseAnswer2 = '张绣'}
SeniorQu[336] = {ID = 336, examType = 2, question = '田楷:司马徽“水镜”之名是谁起的？', trueAnswerId = 1, trueAnswer = '庞德公', falseAnswer1 = '黄承彦', falseAnswer2 = '刘表'}
SeniorQu[337] = {ID = 337, examType = 2, question = '王粲:曹操死后留下了多少遗冢？', trueAnswerId = 1, trueAnswer = '七十二', falseAnswer1 = '六十四', falseAnswer2 = '八十一'}
SeniorQu[338] = {ID = 338, examType = 2, question = '王粲:你可知在曹公和子建的带动下，产生了什么文学吗？', trueAnswerId = 1, trueAnswer = '建安文学', falseAnswer1 = '许都文学', falseAnswer2 = '曹魏文学'}
SeniorQu[339] = {ID = 339, examType = 2, question = '王粲:是谁下手杀死的阿会喃', trueAnswerId = 1, trueAnswer = '孟获', falseAnswer1 = '赵云', falseAnswer2 = '诸葛亮'}
SeniorQu[340] = {ID = 340, examType = 2, question = '王允:八门金锁阵的八个门当中，除死门外，还有哪个门入则亡？', trueAnswerId = 1, trueAnswer = '杜门', falseAnswer1 = '惊门', falseAnswer2 = '景门'}
SeniorQu[341] = {ID = 341, examType = 2, question = '王允:为了大汉天下，我不惜得罪了许多权贵，主公你认为他们之间谁与我有隙？', trueAnswerId = 1, trueAnswer = '中常侍张让', falseAnswer1 = '中常侍赵忠', falseAnswer2 = '中常侍宋典'}
SeniorQu[342] = {ID = 342, examType = 2, question = '王朗:请问关羽被孙权斩首时候，年龄多大？', trueAnswerId = 1, trueAnswer = '五十八', falseAnswer1 = '六十', falseAnswer2 = '六十二'}
SeniorQu[343] = {ID = 343, examType = 2, question = '王甫:逍遥津一役中，谁在危急时刻纵马跃过被拆断的小师桥而得逃一命？', trueAnswerId = 1, trueAnswer = '孙权', falseAnswer1 = '鲁肃', falseAnswer2 = '吕蒙'}
SeniorQu[344] = {ID = 344, examType = 2, question = '魏续:你知道魏军阵营中的荀攸是怎么评价陈宫的吗？', trueAnswerId = 1, trueAnswer = '有谋而迟', falseAnswer1 = '勇决果敢', falseAnswer2 = '足智多谋'}
SeniorQu[345] = {ID = 345, examType = 2, question = '魏续:被刘备评价为“名称八俊，威震九州”的人是谁？', trueAnswerId = 1, trueAnswer = '刘表', falseAnswer1 = '袁术', falseAnswer2 = '袁绍'}
SeniorQu[346] = {ID = 346, examType = 2, question = '魏续:不过听说袁公路的女儿孙女都入了孙仲谋的宫里，主公打听过他孙女嫁给了谁吗？', trueAnswerId = 1, trueAnswer = '孙奋', falseAnswer1 = '孙皓', falseAnswer2 = '孙翊'}
SeniorQu[347] = {ID = 347, examType = 2, question = '魏续:是谁将孙权推荐给诸葛瑾？', trueAnswerId = 1, trueAnswer = '鲁肃', falseAnswer1 = '周瑜', falseAnswer2 = '张昭'}
SeniorQu[348] = {ID = 348, examType = 2, question = '魏延:满宠是由谁举荐给曹操的？', trueAnswerId = 1, trueAnswer = '刘晔', falseAnswer1 = '郭嘉', falseAnswer2 = '戏志才'}
SeniorQu[349] = {ID = 349, examType = 2, question = '魏延:主公可知下列哪件事情，是丞相的得意之作。', trueAnswerId = 1, trueAnswer = '七擒孟获', falseAnswer1 = '水淹七军', falseAnswer2 = '割须弃袍'}
SeniorQu[350] = {ID = 350, examType = 2, question = '魏延:杨仪平日没少给我使绊子，后来他终于被贬为庶民，真是恶有恶报，主公可知这是什么时候的事情？', trueAnswerId = 1, trueAnswer = '建兴十三年', falseAnswer1 = '建兴十二年', falseAnswer2 = '建兴十一年'}
SeniorQu[351] = {ID = 351, examType = 2, question = '魏延:是谁提出“三八纵横，定军之南，黄猪遇虎，伤折一股”的预言？', trueAnswerId = 1, trueAnswer = '管辂', falseAnswer1 = '贾诩', falseAnswer2 = '满宠'}
SeniorQu[352] = {ID = 352, examType = 2, question = '文聘:荆州最后为曹操所得，城破之后，刘表的手下没有立刻降曹的有谁？', trueAnswerId = 1, trueAnswer = '刘琦', falseAnswer1 = '蔡瑁', falseAnswer2 = '张允'}
SeniorQu[353] = {ID = 353, examType = 2, question = '文鸯:楪榆是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '益州', falseAnswer1 = '并州', falseAnswer2 = '冀州'}
SeniorQu[354] = {ID = 354, examType = 2, question = '文鸯:害死我父亲文钦的凶手是', trueAnswerId = 1, trueAnswer = '诸葛诞', falseAnswer1 = '司马师', falseAnswer2 = '钟会'}
SeniorQu[355] = {ID = 355, examType = 2, question = '吴景:是谁攥写讨伐曹操的檄文，曹操听后头痛病痊愈', trueAnswerId = 1, trueAnswer = '陈琳', falseAnswer1 = '审配', falseAnswer2 = '孔融'}
SeniorQu[356] = {ID = 356, examType = 2, question = '吴景:袁绍是听了谁的建议，杀死了田丰？', trueAnswerId = 1, trueAnswer = '逢纪', falseAnswer1 = '沮授', falseAnswer2 = '审配'}
SeniorQu[357] = {ID = 357, examType = 2, question = '吴班:他的表字是什么？', trueAnswerId = 1, trueAnswer = '元雄', falseAnswer1 = '元虎', falseAnswer2 = '元英'}
SeniorQu[358] = {ID = 358, examType = 2, question = '吴班:赵云在长坂坡救出了哪一位夫人?', trueAnswerId = 1, trueAnswer = '甘夫人', falseAnswer1 = '糜夫人', falseAnswer2 = '邹夫人'}
SeniorQu[359] = {ID = 359, examType = 2, question = '吴班:著名才女蔡琰回到中原后嫁给了谁', trueAnswerId = 1, trueAnswer = '董祀', falseAnswer1 = '曹植', falseAnswer2 = '嵇康'}
SeniorQu[360] = {ID = 360, examType = 2, question = '辛毗:诸葛亮在七星坛被东吴追杀，安排谁来接应自己？', trueAnswerId = 1, trueAnswer = '赵云', falseAnswer1 = '张飞', falseAnswer2 = '关羽'}
SeniorQu[361] = {ID = 361, examType = 2, question = '徐盛:曹丕退兵之后，仲谋公让赵达算吴寿命，主公你猜距此时还有多少年', trueAnswerId = 1, trueAnswer = '五十八年', falseAnswer1 = '五十九年', falseAnswer2 = '六十年'}
SeniorQu[362] = {ID = 362, examType = 2, question = '徐盛:主公命我与丁奉派人拦截，若不是赵云勇猛，找捉了他回来。你可知我当时带了多少人去拦截这厮？', trueAnswerId = 1, trueAnswer = '三千', falseAnswer1 = '四千', falseAnswer2 = '五千'}
SeniorQu[363] = {ID = 363, examType = 2, question = '徐晃:当年樊城一战，我治军严谨，还被人比作西汉时候的一位名将呢！主公可知是哪一位？', trueAnswerId = 1, trueAnswer = '周亚夫', falseAnswer1 = '樊哙', falseAnswer2 = '韩信'}
SeniorQu[364] = {ID = 364, examType = 2, question = '徐晃:六安是哪一州属治下呢？', trueAnswerId = 1, trueAnswer = '扬州', falseAnswer1 = '益州', falseAnswer2 = '荆州'}
SeniorQu[365] = {ID = 365, examType = 2, question = '徐晃:杨奉与曹操交战时候，谁作为曹操的说客来说降我？', trueAnswerId = 1, trueAnswer = '满宠', falseAnswer1 = '戏志才', falseAnswer2 = '程昱'}
SeniorQu[366] = {ID = 366, examType = 2, question = '戏志才:七步成诗的魏国才子是谁？', trueAnswerId = 1, trueAnswer = '曹植', falseAnswer1 = '嵇康', falseAnswer2 = '曹丕'}
SeniorQu[367] = {ID = 367, examType = 2, question = '戏志才:下列诸人中，谁以“黄须”著称？', trueAnswerId = 1, trueAnswer = '曹彰', falseAnswer1 = '关羽', falseAnswer2 = '张辽'}
SeniorQu[368] = {ID = 368, examType = 2, question = '戏志才:颍川四长颇为有名，曹公将他们的后人招揽于麾下，实在厉害。但有一人不为曹公做事，主公您知道是谁嘛？', trueAnswerId = 1, trueAnswer = '韩韶', falseAnswer1 = '钟皓', falseAnswer2 = '荀淑'}
SeniorQu[369] = {ID = 369, examType = 2, question = '戏志才:以下不属于韩遂八部将的人是谁？', trueAnswerId = 1, trueAnswer = '杨扈', falseAnswer1 = '梁兴', falseAnswer2 = '侯选'}
SeniorQu[370] = {ID = 370, examType = 2, question = '夏侯威:“平蛮指掌图”是何人献给诸葛亮的？', trueAnswerId = 1, trueAnswer = '吕凯', falseAnswer1 = '法正', falseAnswer2 = '张松'}
SeniorQu[371] = {ID = 371, examType = 2, question = '夏侯霸:你可知道“西凉军”的统帅是何人吗？', trueAnswerId = 1, trueAnswer = '李傕', falseAnswer1 = '胡车儿', falseAnswer2 = '李儒'}
SeniorQu[372] = {ID = 372, examType = 2, question = '夏侯霸:司马家以“八达”闻名，其中一人也为幼字辈，主公认识他吗？', trueAnswerId = 1, trueAnswer = '司马敏', falseAnswer1 = '司马通', falseAnswer2 = '司马恂'}
SeniorQu[373] = {ID = 373, examType = 2, question = '夏侯惇:胥浦是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '交州', falseAnswer1 = '扬州', falseAnswer2 = '益州'}
SeniorQu[374] = {ID = 374, examType = 2, question = '夏侯惇:当年我在徐州攻防战时候，被曹性射伤了眼睛，虽然我已经杀了曹性报仇，主公可知这曹性是谁的部下吗？', trueAnswerId = 1, trueAnswer = '吕布', falseAnswer1 = '刘备', falseAnswer2 = '袁术'}
SeniorQu[375] = {ID = 375, examType = 2, question = '夏侯惇:家中小辈为我整理一些官职文件，我一时想不起来哪个职位我不曾担任过，还请主公帮忙！', trueAnswerId = 1, trueAnswer = '都护将军', falseAnswer1 = '奋威将军', falseAnswer2 = '振威将军'}
SeniorQu[376] = {ID = 376, examType = 2, question = '夏侯渊:被曹操赞为“虎步关右，所向无前”的猛将是谁？', trueAnswerId = 1, trueAnswer = '夏侯渊', falseAnswer1 = '典韦', falseAnswer2 = '许褚'}
SeniorQu[377] = {ID = 377, examType = 2, question = '夏侯渊:当日谋东吴士步骘举了哪两位古人讥笑诸葛亮？', trueAnswerId = 1, trueAnswer = '苏秦张仪', falseAnswer1 = '管仲乐毅', falseAnswer2 = '苏秦管仲'}
SeniorQu[378] = {ID = 378, examType = 2, question = '夏侯渊:自官渡一役打败袁本初后，我曾经负责督管三州的军粮，主公可知哪个州并非我督管的三州之一？', trueAnswerId = 1, trueAnswer = '青州', falseAnswer1 = '兖州', falseAnswer2 = '豫州'}
SeniorQu[379] = {ID = 379, examType = 2, question = '夏侯惠:诸葛亮总共进行了多少次北伐？', trueAnswerId = 1, trueAnswer = '五次', falseAnswer1 = '四次', falseAnswer2 = '六次'}
SeniorQu[380] = {ID = 380, examType = 2, question = '夏侯和:以下诸人中，谁因为脸长而受到众人调笑？', trueAnswerId = 1, trueAnswer = '诸葛瑾', falseAnswer1 = '鲁肃', falseAnswer2 = '张松'}
SeniorQu[381] = {ID = 381, examType = 2, question = '小乔:刘繇旗下何人最终投奔了孙策了？', trueAnswerId = 1, trueAnswer = '太史慈', falseAnswer1 = '樊能', falseAnswer2 = '张英'}
SeniorQu[382] = {ID = 382, examType = 2, question = '小乔:班昭修史也是因为她兄长班固修汉书，未完就过世了，主公知道是哪几篇是未完成的吗？', trueAnswerId = 1, trueAnswer = '天文志', falseAnswer1 = '汉书', falseAnswer2 = '八表'}
SeniorQu[383] = {ID = 383, examType = 2, question = '小乔:我夫君周瑜机智百出，主公可知我夫君用了什么办法让曹操信任黄盖老将军的投降。', trueAnswerId = 1, trueAnswer = '苦肉计', falseAnswer1 = '连环计', falseAnswer2 = '反间计'}
SeniorQu[384] = {ID = 384, examType = 2, question = '辛评:蛮王沙摩柯用的是什么兵刃？', trueAnswerId = 1, trueAnswer = '铁蒺藜骨朵', falseAnswer1 = '斩马刀', falseAnswer2 = '梨花枪'}
SeniorQu[385] = {ID = 385, examType = 2, question = '辛宪英:你可知这篇《仇国论》，是何人所写吗？', trueAnswerId = 1, trueAnswer = '谯周', falseAnswer1 = '陈琳', falseAnswer2 = '孔融'}
SeniorQu[386] = {ID = 386, examType = 2, question = '辛宪英:我为泰山羊氏羊耽之妻，与夫君生下二男一女，女婿为夏侯仲容，主公可知他是夏侯何家之子？', trueAnswerId = 1, trueAnswer = '夏侯威', falseAnswer1 = '夏侯霸', falseAnswer2 = '夏侯渊'}
SeniorQu[387] = {ID = 387, examType = 2, question = '许劭:甘夫人怀孕的时候梦到什么异象？', trueAnswerId = 1, trueAnswer = '北斗', falseAnswer1 = '极光', falseAnswer2 = '贪狼'}
SeniorQu[388] = {ID = 388, examType = 2, question = '许攸:姜维在归降诸葛亮之前是为谁效力的？', trueAnswerId = 1, trueAnswer = '马遵', falseAnswer1 = '韦康', falseAnswer2 = '钟繇'}
SeniorQu[389] = {ID = 389, examType = 2, question = '许攸:是谁接受了孙策得玉玺，而自立为王？', trueAnswerId = 1, trueAnswer = '袁术', falseAnswer1 = '孙坚', falseAnswer2 = '袁绍'}
SeniorQu[390] = {ID = 390, examType = 2, question = '许褚:不过我的手下告诫我不要小看身材矮小的人，近日我也要去会会这样的对手，主公知道是谁嘛？', trueAnswerId = 1, trueAnswer = '乐进', falseAnswer1 = '于禁', falseAnswer2 = '徐晃'}
SeniorQu[391] = {ID = 391, examType = 2, question = '许褚:建安九年随曹公建业之后被封什么官职？', trueAnswerId = 1, trueAnswer = '关内侯', falseAnswer1 = '关外侯', falseAnswer2 = '亭侯'}
SeniorQu[392] = {ID = 392, examType = 2, question = '许褚:临汝是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '扬州', falseAnswer1 = '益州', falseAnswer2 = '荆州'}
SeniorQu[393] = {ID = 393, examType = 2, question = '许褚:下列这些官爵中，哪一个不是属于我的？', trueAnswerId = 1, trueAnswer = '汉寿亭侯', falseAnswer1 = '万岁亭侯', falseAnswer2 = '关内侯'}
SeniorQu[394] = {ID = 394, examType = 2, question = '许靖:三国之中，被称为“锦帆贼”的人是谁？', trueAnswerId = 1, trueAnswer = '甘宁', falseAnswer1 = '凌统', falseAnswer2 = '周泰'}
SeniorQu[395] = {ID = 395, examType = 2, question = '许靖:以下几人中，哪一位不属于“江夏八俊之中”？', trueAnswerId = 1, trueAnswer = '王粲', falseAnswer1 = '孔昱', falseAnswer2 = '张俭'}
SeniorQu[396] = {ID = 396, examType = 2, question = '许贡:关羽刮骨疗伤时，与之对弈的人是哪位？', trueAnswerId = 1, trueAnswer = '马良', falseAnswer1 = '马仲常', falseAnswer2 = '马谡'}
SeniorQu[397] = {ID = 397, examType = 2, question = '许贡:吕布被曹操俘虏后请求投降，是谁进言曹操要处决吕布的？', trueAnswerId = 1, trueAnswer = '刘备', falseAnswer1 = '贾诩', falseAnswer2 = '郭嘉'}
SeniorQu[398] = {ID = 398, examType = 2, question = '荀谌:“后人休把留候比，临没无颜见汉君。”指的是谁？', trueAnswerId = 1, trueAnswer = '荀彧', falseAnswer1 = '荀攸', falseAnswer2 = '程昱'}
SeniorQu[399] = {ID = 399, examType = 2, question = '荀攸:说出“人苦不知足，既得陇，复望蜀”的人是谁？', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '刘备', falseAnswer2 = '孙权'}
SeniorQu[400] = {ID = 400, examType = 2, question = '荀攸:这几位吴国大臣中谁不是孙权的女婿？', trueAnswerId = 1, trueAnswer = '陆抗', falseAnswer1 = '朱据', falseAnswer2 = '周循'}
SeniorQu[401] = {ID = 401, examType = 2, question = '荀攸:自上古起，八人之群多为逸才，帝喾之八元，帝颛顼之八恺，而这些古人中不为八元的是何人？', trueAnswerId = 1, trueAnswer = '仲容', falseAnswer1 = '伯奋', falseAnswer2 = '季仲'}
SeniorQu[402] = {ID = 402, examType = 2, question = '荀攸:我最近在读史记，斗胆问主公，《史记》中有多少列传呢？', trueAnswerId = 1, trueAnswer = '七十', falseAnswer1 = '七十五', falseAnswer2 = '八十'}
SeniorQu[403] = {ID = 403, examType = 2, question = '荀彧:小时候我也颇有才名，后来南阳名士何颙见到我时，是如何称赞我的？', trueAnswerId = 1, trueAnswer = '王佐之才', falseAnswer1 = '管仲之才', falseAnswer2 = '乐毅之才'}
SeniorQu[404] = {ID = 404, examType = 2, question = '荀彧:高阳氏乃是上古著名的帝王，主公可知世人常以何种尊号称呼他？', trueAnswerId = 1, trueAnswer = '帝颛顼', falseAnswer1 = '帝喾', falseAnswer2 = '帝尧'}
SeniorQu[405] = {ID = 405, examType = 2, question = '荀彧:陆逊娶了孙家何人的女儿为妻？', trueAnswerId = 1, trueAnswer = '孙策', falseAnswer1 = '孙权', falseAnswer2 = '周瑜'}
SeniorQu[406] = {ID = 406, examType = 2, question = '荀彧:曹操账下为定辽东，于途中病故的是谁？', trueAnswerId = 1, trueAnswer = '郭嘉', falseAnswer1 = '荀彧', falseAnswer2 = '荀攸'}
SeniorQu[407] = {ID = 407, examType = 2, question = '向朗:虎牢关攻城战后，董卓烧毁洛阳并迁都，请问迁往何处？', trueAnswerId = 1, trueAnswer = '长安', falseAnswer1 = '洛阳', falseAnswer2 = '许都'}
SeniorQu[408] = {ID = 408, examType = 2, question = '薛综:从背后斩杀魏延的蜀汉大将是谁？', trueAnswerId = 1, trueAnswer = '马岱', falseAnswer1 = '马超', falseAnswer2 = '廖化'}
SeniorQu[409] = {ID = 409, examType = 2, question = '薛综:下列中不属于曹魏四友的人是谁？', trueAnswerId = 1, trueAnswer = '华歆', falseAnswer1 = '司马懿', falseAnswer2 = '吴质'}
SeniorQu[410] = {ID = 410, examType = 2, question = '袁绍:周公瑾于何地训练水军？', trueAnswerId = 1, trueAnswer = '鄱阳湖', falseAnswer1 = '洞庭湖', falseAnswer2 = '太湖'}
SeniorQu[411] = {ID = 411, examType = 2, question = '袁术:不过被黄祖截杀，也是他咎由自取，你可知黄祖杀孙坚，是受谁的指使？', trueAnswerId = 1, trueAnswer = '刘表', falseAnswer1 = '蔡瑁', falseAnswer2 = '张允'}
SeniorQu[412] = {ID = 412, examType = 2, question = '袁尚:在庞统施展“连环船”之计后，徐庶借口去防范谁而从曹营离开？', trueAnswerId = 1, trueAnswer = '马超', falseAnswer1 = '轲比能', falseAnswer2 = '刘璋'}
SeniorQu[413] = {ID = 413, examType = 2, question = '袁谭:以下几人中，谁没有担任过东吴的大都督？', trueAnswerId = 1, trueAnswer = '张昭', falseAnswer1 = '鲁肃', falseAnswer2 = '陆逊'}
SeniorQu[414] = {ID = 414, examType = 2, question = '严颜:益州与荆州相邻，而益州巴郡又临近荆州哪一郡？', trueAnswerId = 1, trueAnswer = '武陵郡', falseAnswer1 = '广陵郡', falseAnswer2 = '零陵郡'}
SeniorQu[415] = {ID = 415, examType = 2, question = '严颜:是谁为曹操招募了徐晃?', trueAnswerId = 1, trueAnswer = '满宠', falseAnswer1 = '郭嘉', falseAnswer2 = '程昱'}
SeniorQu[416] = {ID = 416, examType = 2, question = '严白虎:你可知刘焉发榜招军时，刘备多少岁？', trueAnswerId = 1, trueAnswer = '二十八岁', falseAnswer1 = '二十九岁', falseAnswer2 = '三十岁'}
SeniorQu[417] = {ID = 417, examType = 2, question = '严白虎:主公对我吴地历史是否有兴趣，吴王曾是春秋五霸，在《荀子·王霸》中提到的春秋五霸谁不是其中之一呢', trueAnswerId = 1, trueAnswer = '秦穆公', falseAnswer1 = '齐桓公', falseAnswer2 = '晋文公'}
SeniorQu[418] = {ID = 418, examType = 2, question = '严纲:袁绍的谋士中，谁被评为“专而无谋”？', trueAnswerId = 1, trueAnswer = '审配', falseAnswer1 = '郭图', falseAnswer2 = '田丰'}
SeniorQu[419] = {ID = 419, examType = 2, question = '杨弘:周瑜在宴请蒋干时派谁执剑监酒，不容其游说？', trueAnswerId = 1, trueAnswer = '太史慈', falseAnswer1 = '甘宁', falseAnswer2 = '凌统'}
SeniorQu[420] = {ID = 420, examType = 2, question = '杨弘:荀彧是收到了曹操赠送的什么礼物，而选择自尽的？', trueAnswerId = 1, trueAnswer = '空盒子', falseAnswer1 = '书', falseAnswer2 = '酒'}
SeniorQu[421] = {ID = 421, examType = 2, question = '杨弘:谁觉得刘备作为败军将军出征不吉利', trueAnswerId = 1, trueAnswer = '文丑', falseAnswer1 = '高览', falseAnswer2 = '颜良'}
SeniorQu[422] = {ID = 422, examType = 2, question = '杨修:曹操帐下有名人才，名叫任峻，他主管何事？', trueAnswerId = 1, trueAnswer = '粮食耕种', falseAnswer1 = '礼仪祭祀', falseAnswer2 = '后勤补给'}
SeniorQu[423] = {ID = 423, examType = 2, question = '杨修:子建曾品评过当世作者六人，主公可知他是如何形容刘桢的文采的？', trueAnswerId = 1, trueAnswer = '振藻于海隅', falseAnswer1 = '鹰扬于河朔', falseAnswer2 = '擅名于青土'}
SeniorQu[424] = {ID = 424, examType = 2, question = '杨修:中常侍中，谁是汉灵帝的“阿父”？', trueAnswerId = 1, trueAnswer = '张让', falseAnswer1 = '赵忠', falseAnswer2 = '夏恽'}
SeniorQu[425] = {ID = 425, examType = 2, question = '杨彪:华佗临死前，将什么托付给了看管自己的狱吏？', trueAnswerId = 1, trueAnswer = '青囊医书', falseAnswer1 = '吴普本草', falseAnswer2 = '本草经'}
SeniorQu[426] = {ID = 426, examType = 2, question = '杨彪:刘备三顾茅庐时，第一次将谁误认为诸葛亮？', trueAnswerId = 1, trueAnswer = '崔州平', falseAnswer1 = '石广元', falseAnswer2 = '孟公威'}
SeniorQu[427] = {ID = 427, examType = 2, question = '羊祜:司马师的原配可是被他毒杀的，继室嫁去不久也被休出，说起来原配好像是某个夏侯的女儿？', trueAnswerId = 1, trueAnswer = '夏侯尚', falseAnswer1 = '夏侯霸', falseAnswer2 = '夏侯惇'}
SeniorQu[428] = {ID = 428, examType = 2, question = '羊祜:我若遭逢不测，主公认为，谁可取我而代之？', trueAnswerId = 1, trueAnswer = '杜预', falseAnswer1 = '邓艾', falseAnswer2 = '钟会'}
SeniorQu[429] = {ID = 429, examType = 2, question = '羊祜:曹操在何时建成了铜雀台？', trueAnswerId = 1, trueAnswer = '建安十五年', falseAnswer1 = '建安十六年', falseAnswer2 = '建安十七年'}
SeniorQu[430] = {ID = 430, examType = 2, question = '虞翻:我收了不少门徒，讲学的闲暇之余，为一些古书训注，主公可知哪部古书我不曾训注过。', trueAnswerId = 1, trueAnswer = '春秋', falseAnswer1 = '左传', falseAnswer2 = '大学'}
SeniorQu[431] = {ID = 431, examType = 2, question = '虞翻:关羽在离开曹操，带走了曹操送给他的什么？', trueAnswerId = 1, trueAnswer = '赤兔马', falseAnswer1 = '官印', falseAnswer2 = '金银'}
SeniorQu[432] = {ID = 432, examType = 2, question = '阎象:长坂坡攻城战，赵云从夏侯恩手中夺走了哪一把宝剑？', trueAnswerId = 1, trueAnswer = '青虹剑', falseAnswer1 = '倚天剑', falseAnswer2 = '白虹剑'}
SeniorQu[433] = {ID = 433, examType = 2, question = '阎柔:谁奉了曹操之命杀了刘崇母子？', trueAnswerId = 1, trueAnswer = '于禁', falseAnswer1 = '乐进', falseAnswer2 = '徐晃'}
SeniorQu[434] = {ID = 434, examType = 2, question = '于禁:曹公看了开心，诗兴大发，其中有一句诗叫揽什么于东南来着？', trueAnswerId = 1, trueAnswer = '二乔', falseAnswer1 = '大乔', falseAnswer2 = '小乔'}
SeniorQu[435] = {ID = 435, examType = 2, question = '于禁:关羽的赤兔马是谁赠送的？', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '董卓', falseAnswer2 = '刘备'}
SeniorQu[436] = {ID = 436, examType = 2, question = '于禁:赤壁之战时，是谁拿假书信骗取曹操信任，而使得曹操彻底相信了黄盖的苦肉计？', trueAnswerId = 1, trueAnswer = '阚泽', falseAnswer1 = '蒋干', falseAnswer2 = '庞统'}
SeniorQu[437] = {ID = 437, examType = 2, question = '尹礼:广陵太守得华佗所救，而免于腹虫之死。这个广陵太守为何人？', trueAnswerId = 1, trueAnswer = '陈登', falseAnswer1 = '陈群', falseAnswer2 = '陈肃'}
SeniorQu[438] = {ID = 438, examType = 2, question = '臧霸:静国寺中，谁给关羽暗示秦琪埋伏？', trueAnswerId = 1, trueAnswer = '普净', falseAnswer1 = '普度', falseAnswer2 = '普贤'}
SeniorQu[439] = {ID = 439, examType = 2, question = '张济:“堕泪碑”是为谁所建？', trueAnswerId = 1, trueAnswer = '羊祜', falseAnswer1 = '邓艾', falseAnswer2 = '钟会'}
SeniorQu[440] = {ID = 440, examType = 2, question = '张允:七擒七纵孟获中，第三次抓住孟获的武将是谁？', trueAnswerId = 1, trueAnswer = '马岱', falseAnswer1 = '赵云', falseAnswer2 = '张苞'}
SeniorQu[441] = {ID = 441, examType = 2, question = '张苞:那吕布也不过是三姓家奴罢了，你知道下列哪一位不是吕布曾经侍奉过的主公吗？', trueAnswerId = 1, trueAnswer = '曹操', falseAnswer1 = '丁原', falseAnswer2 = '董卓'}
SeniorQu[442] = {ID = 442, examType = 2, question = '张苞:董卓的女婿是谁？', trueAnswerId = 1, trueAnswer = '牛辅', falseAnswer1 = '胡车儿', falseAnswer2 = '李肃'}
SeniorQu[443] = {ID = 443, examType = 2, question = '张苞:主公可知，家父是于何时被刘公封为右将军？', trueAnswerId = 1, trueAnswer = '汉中称王', falseAnswer1 = '赤壁之战', falseAnswer2 = '成都称帝'}
SeniorQu[444] = {ID = 444, examType = 2, question = '张辽:祖先显赫，后人往往也多有成就，主公你可知这几人中谁才是布衣出生？', trueAnswerId = 1, trueAnswer = '邓艾', falseAnswer1 = '钟会', falseAnswer2 = '张苞'}
SeniorQu[445] = {ID = 445, examType = 2, question = '张辽:以下哪一位，不是“五子良将”中的一员？', trueAnswerId = 1, trueAnswer = '典韦', falseAnswer1 = '徐晃', falseAnswer2 = '张辽'}
SeniorQu[446] = {ID = 446, examType = 2, question = '张辽:德阳是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '益州', falseAnswer1 = '并州', falseAnswer2 = '凉州'}
SeniorQu[447] = {ID = 447, examType = 2, question = '张达:功成身被害，魂绕汉江云。形容的是哪位武将？', trueAnswerId = 1, trueAnswer = '邓艾', falseAnswer1 = '钟会', falseAnswer2 = '姜维'}
SeniorQu[448] = {ID = 448, examType = 2, question = '张飞:讨伐董卓时孙坚以先锋身份前往哪个关隘挑战董卓大军？', trueAnswerId = 1, trueAnswer = '汜水关', falseAnswer1 = '虎牢关', falseAnswer2 = '洛阳'}
SeniorQu[449] = {ID = 449, examType = 2, question = '张飞:以下几人中，身在曹营心在汉的是谁？', trueAnswerId = 1, trueAnswer = '徐庶', falseAnswer1 = '郭嘉', falseAnswer2 = '程昱'}
SeniorQu[450] = {ID = 450, examType = 2, question = '张燕:下列诸人中，哪一位是宦官？', trueAnswerId = 1, trueAnswer = '赵忠', falseAnswer1 = '王允', falseAnswer2 = '杨彪'}
SeniorQu[451] = {ID = 451, examType = 2, question = '张燕:黑山的兄弟们都称我为“飞燕”。说到飞燕，本朝的有位皇后名讳也为“飞燕”，主公知道是谁嘛？', trueAnswerId = 1, trueAnswer = '孝成皇后', falseAnswer1 = '孝感皇后', falseAnswer2 = '孝仁皇后'}
SeniorQu[452] = {ID = 452, examType = 2, question = '张纮:甄宓本是袁家谁的妻子？', trueAnswerId = 1, trueAnswer = '袁熙', falseAnswer1 = '袁谭', falseAnswer2 = '袁尚'}
SeniorQu[453] = {ID = 453, examType = 2, question = '张纮:主公可知道这茂才对应的，是哪种取士制度吗？', trueAnswerId = 1, trueAnswer = '察举制', falseAnswer1 = '孝廉制', falseAnswer2 = '九品制'}
SeniorQu[454] = {ID = 454, examType = 2, question = '张纮:主公可知，桓灵二帝时期，受五府（太傅太尉司徒司空大将军）辟召，又为党锢三君之一的是何人？', trueAnswerId = 1, trueAnswer = '刘淑', falseAnswer1 = '荀昱', falseAnswer2 = '朱寓'}
SeniorQu[455] = {ID = 455, examType = 2, question = '张角:我门中大道博大精深，我来考考你，你可知《庄子》一书，又被叫做什么吗？', trueAnswerId = 1, trueAnswer = '南华经', falseAnswer1 = '道德经', falseAnswer2 = '太平经'}
SeniorQu[456] = {ID = 456, examType = 2, question = '张角:十八路诸侯讨伐董卓时候的总盟主是哪一位？', trueAnswerId = 1, trueAnswer = '袁绍', falseAnswer1 = '曹操', falseAnswer2 = '袁术'}
SeniorQu[457] = {ID = 457, examType = 2, question = '张角:对于我们太平道来说，甲子意义重大，主公知道甲子对应的阴阳五行吗？', trueAnswerId = 1, trueAnswer = '阳木阳水', falseAnswer1 = '阴火阴木', falseAnswer2 = '阳火阴木'}
SeniorQu[458] = {ID = 458, examType = 2, question = '张梁:兄长专研的是《太平清领书》一书，但他命我们兄弟二人多读黄帝四经，眼下似乎有卷经混了进来。', trueAnswerId = 1, trueAnswer = '道德经', falseAnswer1 = '经法', falseAnswer2 = '十大经'}
SeniorQu[459] = {ID = 459, examType = 2, question = '张梁:诸葛亮一生擅长火攻，当年他初出茅庐，第一把火烧在何处？', trueAnswerId = 1, trueAnswer = '博望坡', falseAnswer1 = '赤壁', falseAnswer2 = '新野'}
SeniorQu[460] = {ID = 460, examType = 2, question = '张梁:我教中素有“三灾八难”的说法，下列哪一灾，不属于“三灾”之中呢？', trueAnswerId = 1, trueAnswer = '雷灾', falseAnswer1 = '风灾', falseAnswer2 = '火灾'}
SeniorQu[461] = {ID = 461, examType = 2, question = '张梁:张达和笵疆因为准备什么不利而被张飞责打？', trueAnswerId = 1, trueAnswer = '孝服', falseAnswer1 = '弓箭', falseAnswer2 = '粮草'}
SeniorQu[462] = {ID = 462, examType = 2, question = '张宝:抬棺木战关羽的魏将是谁？', trueAnswerId = 1, trueAnswer = '庞德', falseAnswer1 = '于禁', falseAnswer2 = '乐进'}
SeniorQu[463] = {ID = 463, examType = 2, question = '张宝:我且问你，正月初九是什么日子？', trueAnswerId = 1, trueAnswer = '玉帝生辰', falseAnswer1 = '老子生辰', falseAnswer2 = '王母生辰'}
SeniorQu[464] = {ID = 464, examType = 2, question = '张任:益州士族也有吃里扒外的东西跟着赵贼一起策反季玉，主公听说哪个郡没有响应叛贼赵韪的作乱吗？', trueAnswerId = 1, trueAnswer = '巴郡', falseAnswer1 = '蜀郡', falseAnswer2 = '广汉'}
SeniorQu[465] = {ID = 465, examType = 2, question = '张任:以下人中谁是丹凤眼、卧蚕眉？', trueAnswerId = 1, trueAnswer = '关羽', falseAnswer1 = '赵云', falseAnswer2 = '张飞'}
SeniorQu[466] = {ID = 466, examType = 2, question = '张任:你可知刘备的手下庞统在席上命谁舞剑，欲害刘璋性命吗？', trueAnswerId = 1, trueAnswer = '魏延', falseAnswer1 = '赵云', falseAnswer2 = '黄忠'}
SeniorQu[467] = {ID = 467, examType = 2, question = '张任:下面没有参与行刺曹操的是？', trueAnswerId = 1, trueAnswer = '韩遂', falseAnswer1 = '种辑', falseAnswer2 = '董承'}
SeniorQu[468] = {ID = 468, examType = 2, question = '张郃:下列哪个成语相关联的事迹是和我有关系的？', trueAnswerId = 1, trueAnswer = '屈指可数', falseAnswer1 = '草船借箭', falseAnswer2 = '三顾茅庐'}
SeniorQu[469] = {ID = 469, examType = 2, question = '张郃:被曹操赞为“古之召虎”的猛将是谁？', trueAnswerId = 1, trueAnswer = '张辽', falseAnswer1 = '典韦', falseAnswer2 = '许褚'}
SeniorQu[470] = {ID = 470, examType = 2, question = '张绣:那么被陈群评价为“不治行检”的是曹操手下哪一位谋士呢？', trueAnswerId = 1, trueAnswer = '郭嘉', falseAnswer1 = '贾诩', falseAnswer2 = '程昱'}
SeniorQu[471] = {ID = 471, examType = 2, question = '张绣:听说袁绍在官渡战败后的消息。谁在狱中自杀？', trueAnswerId = 1, trueAnswer = '田丰', falseAnswer1 = '沮授', falseAnswer2 = '审配'}
SeniorQu[472] = {ID = 472, examType = 2, question = '张昭:我随伯符入吴后，曾寻访过吴地出名的左氏春秋学者的后人，主公可知我结识了谁？', trueAnswerId = 1, trueAnswer = '高彪', falseAnswer1 = '顾雍', falseAnswer2 = '虞翻'}
SeniorQu[473] = {ID = 473, examType = 2, question = '张昭:那如果外交战争方面的事情不能决断，应该去问谁呢？', trueAnswerId = 1, trueAnswer = '周瑜', falseAnswer1 = '张昭', falseAnswer2 = '鲁肃'}
SeniorQu[474] = {ID = 474, examType = 2, question = '张昭:曹操设置了什么官职行掘墓盗宝之事？', trueAnswerId = 1, trueAnswer = '摸金校尉', falseAnswer1 = '中郎将', falseAnswer2 = '典军校尉'}
SeniorQu[475] = {ID = 475, examType = 2, question = '张松:汜水关一战中，担任十八路诸侯先锋的是哪一位？', trueAnswerId = 1, trueAnswer = '孙坚', falseAnswer1 = '袁术', falseAnswer2 = '曹操'}
SeniorQu[476] = {ID = 476, examType = 2, question = '赵云:主公可知下列这些战役，哪一战是我参与的？', trueAnswerId = 1, trueAnswer = '当阳攻城战', falseAnswer1 = '官渡之战', falseAnswer2 = '宛城之战'}
SeniorQu[477] = {ID = 477, examType = 2, question = '赵云:孙坚被黄祖所杀时孙策的年纪？', trueAnswerId = 1, trueAnswer = '十七岁', falseAnswer1 = '十八岁', falseAnswer2 = '十九岁'}
SeniorQu[478] = {ID = 478, examType = 2, question = '甄宓:青蛉是哪一个州属治下呢？', trueAnswerId = 1, trueAnswer = '益州', falseAnswer1 = '扬州', falseAnswer2 = '并州'}
SeniorQu[479] = {ID = 479, examType = 2, question = '甄宓:主公可知道，妾身在嫁予曹丕公子之前，是袁家哪位公子的侧室？', trueAnswerId = 1, trueAnswer = '袁熙', falseAnswer1 = '袁尚', falseAnswer2 = '袁谭'}
SeniorQu[480] = {ID = 480, examType = 2, question = '甄宓:甄家为我调查了郭女王的身世背景，主公你觉得哪一点才是真的？', trueAnswerId = 1, trueAnswer = '以子为贵', falseAnswer1 = '家族势大', falseAnswer2 = '皇帝恩宠'}
SeniorQu[481] = {ID = 481, examType = 2, question = '周泰:曹魏灭吴之心不死，因此我们经常能遇上老熟人打上一仗，主公克制我与子邵交手过的曹姓大将是谁？', trueAnswerId = 1, trueAnswer = '曹仁', falseAnswer1 = '曹洪', falseAnswer2 = '曹彰'}
SeniorQu[482] = {ID = 482, examType = 2, question = '周泰:曹操因将士口渴，称前方有梅林的这件事引申成了哪个成语？', trueAnswerId = 1, trueAnswer = '望梅止渴', falseAnswer1 = '望河止渴', falseAnswer2 = '望林止渴'}
SeniorQu[483] = {ID = 483, examType = 2, question = '周泰:主公记得我的好，建安十三年赐予我一样宝贝，你可知道是什么？', trueAnswerId = 1, trueAnswer = '青罗伞盖', falseAnswer1 = '名剑', falseAnswer2 = '宝马'}
SeniorQu[484] = {ID = 484, examType = 2, question = '周瑜:曹操最后选定的继承人是谁？', trueAnswerId = 1, trueAnswer = '曹丕', falseAnswer1 = '曹植', falseAnswer2 = '曹彰'}
SeniorQu[485] = {ID = 485, examType = 2, question = '周瑜:袁术称帝后发七路兵征讨徐州，他手下的张勋是何官职？', trueAnswerId = 1, trueAnswer = '大将军', falseAnswer1 = '左将军', falseAnswer2 = '右将军'}
SeniorQu[486] = {ID = 486, examType = 2, question = '周瑜:求东风之事不容有失，主公可知我派了多少兵马筑造七星台？', trueAnswerId = 1, trueAnswer = '五百', falseAnswer1 = '三百', falseAnswer2 = '八百'}
SeniorQu[487] = {ID = 487, examType = 2, question = '周仓:吕蒙西取荆州三郡，与家公关云长对峙，荆州哪一郡不在此三郡中？', trueAnswerId = 1, trueAnswer = '武陵', falseAnswer1 = '长沙', falseAnswer2 = '零陵'}
SeniorQu[488] = {ID = 488, examType = 2, question = '周仓:关老爷最出名的就是他的青龙偃月刀，你可知道这把刀多重啊？', trueAnswerId = 1, trueAnswer = '八十二斤', falseAnswer1 = '七十二斤', falseAnswer2 = '六十四斤'}
SeniorQu[489] = {ID = 489, examType = 2, question = '周仓:公孙瓒与哪个异族作战而自号“白马将军”。', trueAnswerId = 1, trueAnswer = '羌', falseAnswer1 = '鲜卑', falseAnswer2 = '匈奴'}
SeniorQu[490] = {ID = 490, examType = 2, question = '诸葛瑾:葛伯故国仍有迹可循，主公可知此地今在豫州何郡国？', trueAnswerId = 1, trueAnswer = '梁国', falseAnswer1 = '越国', falseAnswer2 = '楚国'}
SeniorQu[491] = {ID = 491, examType = 2, question = '诸葛瑾:你可知他常常把自己比作古代哪两位有名的政治家吗？', trueAnswerId = 1, trueAnswer = '管仲、乐毅', falseAnswer1 = '苏秦、张仪', falseAnswer2 = '管仲、苏秦'}
SeniorQu[492] = {ID = 492, examType = 2, question = '诸葛瑾:祢衡评点曹操手下文武大臣，他形容程昱的能力是什么？', trueAnswerId = 1, trueAnswer = '关门闭户', falseAnswer1 = '看坟守墓', falseAnswer2 = '吊丧问疾'}
SeniorQu[493] = {ID = 493, examType = 2, question = '诸葛亮:治军严苛得以有精锐之师。我军有七禁，违者皆斩之。“闻鼓不行，鸣金不止。”违反了哪条禁令？', trueAnswerId = 1, trueAnswer = '背军', falseAnswer1 = '慢军', falseAnswer2 = '乱军'}
SeniorQu[494] = {ID = 494, examType = 2, question = '诸葛亮:故此当年他来访我，我以《隆中对》授他平定天下之计，你可知这隆中对中的奥义', trueAnswerId = 1, trueAnswer = '三分天下', falseAnswer1 = '一统天下', falseAnswer2 = '败魏抗吴'}
SeniorQu[495] = {ID = 495, examType = 2, question = '祝融:祝融后人有八姓，为己、董、彭、秃、妘、曹、斟、芈。主公可知邹、莒当为何姓？', trueAnswerId = 1, trueAnswer = '曹姓', falseAnswer1 = '孙姓', falseAnswer2 = '刘姓'}
SeniorQu[496] = {ID = 496, examType = 2, question = '祝融:我于阵前生擒张嶷、马忠二人，你却道我夫君为何不杀？', trueAnswerId = 1, trueAnswer = '感念诸葛恩德', falseAnswer1 = '招降二人', falseAnswer2 = '怕被报复'}
SeniorQu[497] = {ID = 497, examType = 2, question = '朱然:张辽最初侍奉的主公是哪一位？', trueAnswerId = 1, trueAnswer = '丁原', falseAnswer1 = '袁绍', falseAnswer2 = '曹操'}
SeniorQu[498] = {ID = 498, examType = 2, question = '朱然:下列诸人中，哪一位不是王元姬和司马昭的孩子？', trueAnswerId = 1, trueAnswer = '司马防', falseAnswer1 = '司马炎', falseAnswer2 = '司马攸'}
SeniorQu[499] = {ID = 499, examType = 2, question = '朱治:以下诸人中，谁不是建安七子之一？', trueAnswerId = 1, trueAnswer = '曹植', falseAnswer1 = '王粲', falseAnswer2 = '孔融'}
SeniorQu[500] = {ID = 500, examType = 2, question = '朱治:下列诸人中，何人和刘备是同一地方出生的？', trueAnswerId = 1, trueAnswer = '简雍', falseAnswer1 = '孙乾', falseAnswer2 = '糜竺'}
SeniorQu[501] = {ID = 501, examType = 2, question = '左慈:随曹孟德征战沙场的良驹是哪一匹', trueAnswerId = 1, trueAnswer = '绝影', falseAnswer1 = '的卢', falseAnswer2 = '赤兔'}
SeniorQu[502] = {ID = 502, examType = 2, question = '左慈:诸葛家族在三国显赫一时，当时人称：“蜀得其龙，吴得其虎，魏得其犬”龙指诸葛亮，虎指诸葛瑾，那犬指谁呢？', trueAnswerId = 1, trueAnswer = '诸葛诞', falseAnswer1 = '诸葛均', falseAnswer2 = '诸葛恪'}
SeniorQu[503] = {ID = 503, examType = 2, question = '笮融:诸葛亮用添灶之法退军的事发生在第几次北伐战役中？', trueAnswerId = 1, trueAnswer = '第四次', falseAnswer1 = '第三次', falseAnswer2 = '第二次'}
return SeniorQu