local ShowControl = {} 
ShowControl[0] = {ID = 0, showType = 0, shieldID = '[]'}
ShowControl[1] = {ID = 1, showType = 1, shieldID = '[]'}
ShowControl[2] = {ID = 2, showType = 2, shieldID = '[]'}
ShowControl[3] = {ID = 3, showType = 0, shieldID = '[]'}
ShowControl[4] = {ID = 4, showType = 0, shieldID = '[]'}
ShowControl[5] = {ID = 5, showType = 0, shieldID = '[]'}
ShowControl[6] = {ID = 6, showType = 3, shieldID = '[]'}
ShowControl[7] = {ID = 7, showType = 2, shieldID = '[]'}
ShowControl[8] = {ID = 8, showType = 0, shieldID = '[]'}
ShowControl[9] = {ID = 9, showType = 2, shieldID = '[]'}
ShowControl[10] = {ID = 10, showType = 0, shieldID = '[]'}
ShowControl[11] = {ID = 11, showType = 2, shieldID = '[]'}
ShowControl[12] = {ID = 12, showType = 2, shieldID = '[]'}
ShowControl[13] = {ID = 13, showType = 1, shieldID = '[]'}
ShowControl[14] = {ID = 14, showType = 0, shieldID = '[]'}
ShowControl[15] = {ID = 15, showType = 3, shieldID = '[]'}
ShowControl[16] = {ID = 16, showType = 3, shieldID = '[]'}
ShowControl[17] = {ID = 17, showType = 3, shieldID = '[]'}
ShowControl[18] = {ID = 18, shieldID = '[]'}
ShowControl[19] = {ID = 19, showType = 2, shieldID = '[]'}
ShowControl[20] = {ID = 20, showType = 2, shieldID = '[]'}
ShowControl[21] = {ID = 21, showType = 0, shieldID = '[]'}
ShowControl[22] = {ID = 22, showType = 0, shieldID = '[]'}
ShowControl[23] = {ID = 23, showType = 2, shieldID = '[]'}
ShowControl[24] = {ID = 24, showType = 1, shieldID = '[406]'}
ShowControl[25] = {ID = 25, showType = 0, shieldID = '[]'}
ShowControl[26] = {ID = 26, showType = 3, shieldID = '[]'}
ShowControl[27] = {ID = 27, showType = 3, shieldID = '[]'}
ShowControl[28] = {ID = 28, showType = 0, shieldID = '[]'}
ShowControl[29] = {ID = 29, showType = 1, shieldID = '[]'}
ShowControl[30] = {ID = 30, showType = 2, shieldID = '[]'}
ShowControl[31] = {ID = 31, showType = 2, shieldID = '[]'}
ShowControl[32] = {ID = 32, showType = 0, shieldID = '[]'}
ShowControl[33] = {ID = 33, showType = 3, shieldID = '[]'}
ShowControl[34] = {ID = 34, showType = 1, shieldID = '[]'}
ShowControl[35] = {ID = 35, showType = 1, shieldID = '[]'}
ShowControl[36] = {ID = 36, showType = 2, shieldID = '[]'}
ShowControl[37] = {ID = 37, showType = 2, shieldID = '[]'}
ShowControl[38] = {ID = 38, showType = 2, shieldID = '[]'}
ShowControl[39] = {ID = 39, showType = 0, shieldID = '[]'}
ShowControl[40] = {ID = 40, showType = 0, shieldID = '[]'}
ShowControl[41] = {ID = 41, showType = 0, shieldID = '[]'}
ShowControl[42] = {ID = 42, showType = 2, shieldID = '[]'}
ShowControl[43] = {ID = 43, showType = 2, shieldID = '[]'}
ShowControl[44] = {ID = 44, showType = 2, shieldID = '[]'}
ShowControl[45] = {ID = 45, showType = 0, shieldID = '[]'}
ShowControl[46] = {ID = 46, showType = 2, shieldID = '[]'}
ShowControl[47] = {ID = 47, shieldID = '[]'}
ShowControl[48] = {ID = 48, showType = 1, shieldID = '[406]'}
ShowControl[49] = {ID = 49, showType = 0, shieldID = '[]'}
ShowControl[50] = {ID = 50, showType = 2, shieldID = '[]'}
ShowControl[51] = {ID = 51, showType = 1, shieldID = '[]'}
ShowControl[52] = {ID = 52, showType = 2, shieldID = '[]'}
ShowControl[53] = {ID = 53, showType = 1, shieldID = '[]'}
ShowControl[54] = {ID = 54, showType = 1, shieldID = '[]'}
ShowControl[55] = {ID = 55, showType = 0, shieldID = '[]'}
ShowControl[56] = {ID = 56, showType = 2, shieldID = '[]'}
ShowControl[57] = {ID = 57, showType = 2, shieldID = '[]'}
ShowControl[58] = {ID = 58, showType = 3, shieldID = '[]'}
ShowControl[59] = {ID = 59, showType = 0, shieldID = '[]'}
ShowControl[60] = {ID = 60, showType = 2, shieldID = '[]'}
ShowControl[61] = {ID = 61, showType = 2, shieldID = '[]'}
ShowControl[62] = {ID = 62, showType = 1, shieldID = '[]'}
ShowControl[63] = {ID = 63, showType = 0, shieldID = '[]'}
ShowControl[64] = {ID = 64, showType = 0, shieldID = '[]'}
ShowControl[65] = {ID = 65, showType = 1, shieldID = '[]'}
ShowControl[66] = {ID = 66, showType = 0, shieldID = '[]'}
ShowControl[67] = {ID = 67, showType = 0, shieldID = '[]'}
ShowControl[68] = {ID = 68, showType = 0, shieldID = '[]'}
ShowControl[69] = {ID = 69, showType = 0, shieldID = '[]'}
ShowControl[70] = {ID = 70, showType = 2, shieldID = '[]'}
ShowControl[71] = {ID = 71, showType = 2, shieldID = '[]'}
ShowControl[72] = {ID = 72, showType = 0, shieldID = '[]'}
ShowControl[73] = {ID = 73, shieldID = '[]'}
ShowControl[74] = {ID = 74, showType = 0, shieldID = '[]'}
ShowControl[75] = {ID = 75, showType = 0, shieldID = '[]'}
ShowControl[76] = {ID = 76, showType = 0, shieldID = '[]'}
ShowControl[77] = {ID = 77, showType = 0, shieldID = '[]'}
ShowControl[78] = {ID = 78, showType = 3, shieldID = '[]'}
ShowControl[79] = {ID = 79, shieldID = '[]'}
ShowControl[80] = {ID = 80, showType = 2, shieldID = '[]'}
ShowControl[81] = {ID = 81, showType = 1, shieldID = '[]'}
ShowControl[82] = {ID = 82, showType = 0, shieldID = '[]'}
ShowControl[83] = {ID = 83, showType = 0, shieldID = '[]'}
ShowControl[84] = {ID = 84, showType = 0, shieldID = '[]'}
ShowControl[85] = {ID = 85, showType = 2, shieldID = '[]'}
ShowControl[86] = {ID = 86, showType = 0, shieldID = '[]'}
ShowControl[87] = {ID = 87, showType = 0, shieldID = '[]'}
ShowControl[88] = {ID = 88, showType = 0, shieldID = '[]'}
ShowControl[89] = {ID = 89, showType = 2, shieldID = '[]'}
ShowControl[90] = {ID = 90, showType = 2, shieldID = '[]'}
ShowControl[91] = {ID = 91, showType = 2, shieldID = '[]'}
ShowControl[92] = {ID = 92, showType = 3, shieldID = '[]'}
ShowControl[93] = {ID = 93, showType = 0, shieldID = '[]'}
ShowControl[94] = {ID = 94, showType = 0, shieldID = '[]'}
ShowControl[95] = {ID = 95, showType = 0, shieldID = '[]'}
ShowControl[96] = {ID = 96, showType = 2, shieldID = '[]'}
ShowControl[97] = {ID = 97, showType = 2, shieldID = '[]'}
ShowControl[98] = {ID = 98, showType = 2, shieldID = '[]'}
ShowControl[99] = {ID = 99, showType = 0, shieldID = '[]'}
ShowControl[100] = {ID = 100, showType = 0, shieldID = '[]'}
ShowControl[101] = {ID = 101, showType = 0, shieldID = '[]'}
ShowControl[102] = {ID = 102, showType = 2, shieldID = '[]'}
ShowControl[103] = {ID = 103, shieldID = '[]'}
ShowControl[104] = {ID = 104, shieldID = '[]'}
ShowControl[105] = {ID = 105, shieldID = '[]'}
ShowControl[106] = {ID = 106, shieldID = '[]'}
ShowControl[107] = {ID = 107, shieldID = '[]'}
ShowControl[118] = {ID = 118, showType = 0, shieldID = '[]'}
ShowControl[119] = {ID = 119, showType = 0, shieldID = '[]'}
ShowControl[1144] = {ID = 1144, showType = 0, shieldID = '[]'}
ShowControl[1145] = {ID = 1145, showType = 0, shieldID = '[]'}
ShowControl[125] = {ID = 125, showType = 0, shieldID = '[]'}
ShowControl[127] = {ID = 127, showType = 0, shieldID = '[]'}
ShowControl[128] = {ID = 128, showType = 0, shieldID = '[]'}
ShowControl[136] = {ID = 136, showType = 1, shieldID = '[406]'}
ShowControl[137] = {ID = 137, showType = 0, shieldID = '[]'}
ShowControl[138] = {ID = 138, showType = 0, shieldID = '[]'}
ShowControl[139] = {ID = 139, showType = 0, shieldID = '[]'}
ShowControl[140] = {ID = 140, showType = 0, shieldID = '[]'}
ShowControl[141] = {ID = 141, showType = 1, shieldID = '[]'}
ShowControl[142] = {ID = 142, showType = 0, shieldID = '[]'}
ShowControl[144] = {ID = 144, showType = 0, shieldID = '[]'}
ShowControl[145] = {ID = 145, showType = 0, shieldID = '[]'}
ShowControl[146] = {ID = 146, showType = 0, shieldID = '[]'}
ShowControl[147] = {ID = 147, showType = 0, shieldID = '[]'}
ShowControl[149] = {ID = 149, showType = 0, shieldID = '[]'}
ShowControl[150] = {ID = 150, showType = 0, shieldID = '[]'}
ShowControl[163] = {ID = 163, showType = 0, shieldID = '[]'}
ShowControl[164] = {ID = 164, showType = 0, shieldID = '[]'}
ShowControl[165] = {ID = 165, showType = 0, shieldID = '[]'}
ShowControl[1052] = {ID = 1052, showType = 1, shieldID = '[406]'}
ShowControl[172] = {ID = 172, showType = 1, shieldID = '[]'}
ShowControl[173] = {ID = 173, showType = 0, shieldID = '[]'}
ShowControl[1053] = {ID = 1053, showType = 1, shieldID = '[406]'}
ShowControl[1054] = {ID = 1054, showType = 1, shieldID = '[406]'}
ShowControl[1142] = {ID = 1142, showType = 0, shieldID = '[]'}
ShowControl[1143] = {ID = 1143, showType = 0, shieldID = '[]'}
ShowControl[1064] = {ID = 1064, showType = 0, shieldID = '[]'}
ShowControl[1051] = {ID = 1051, showType = 1, shieldID = '[406]'}
return ShowControl