local Warriors = {} 
Warriors[11] = {ID = 11, name = '铁剑', info = '每级增加0.1%武将攻击力。', massage = '每级+0.1%', icon = 11, littleicon = 1, quality = 1, isRarity = 0, partId = 1, upproperty = 12, suitId = 0, eatedExp = 0, sellPrice = 100, sound = 1, checkinfo = '所属部队攻击力'}
Warriors[12] = {ID = 12, name = '皮甲', info = '每级增加0.1%武将血量上限。', massage = '每级+0.1%', icon = 12, littleicon = 5, quality = 1, isRarity = 0, partId = 2, upproperty = 11, suitId = 0, eatedExp = 0, sellPrice = 100, sound = 1, checkinfo = '所属部队生命上限'}
Warriors[13] = {ID = 13, name = '皮护手', info = '每级增加0.1%武将命中。', massage = '每级+0.1%', icon = 13, littleicon = 4, quality = 1, isRarity = 0, partId = 3, upproperty = 4, suitId = 0, eatedExp = 0, sellPrice = 100, sound = 1, checkinfo = '所属部队命中'}
Warriors[14] = {ID = 14, name = '皮靴', info = '每级增加0.1%武将闪避。', massage = '每级+0.1%', icon = 14, littleicon = 6, quality = 1, isRarity = 0, partId = 4, upproperty = 5, suitId = 0, eatedExp = 0, sellPrice = 100, sound = 1, checkinfo = '所属部队闪避'}
Warriors[15] = {ID = 15, name = '匕首', info = '每级增加0.1%武将暴击。', massage = '每级+0.1%', icon = 15, littleicon = 2, quality = 1, isRarity = 0, partId = 5, upproperty = 6, suitId = 0, eatedExp = 0, sellPrice = 100, sound = 1, checkinfo = '所属部队暴击'}
Warriors[16] = {ID = 16, name = '皮头盔', info = '每级增加0.1%武将抗暴。', massage = '每级+0.1%', icon = 16, littleicon = 3, quality = 1, isRarity = 0, partId = 6, upproperty = 7, suitId = 0, eatedExp = 0, sellPrice = 100, sound = 1, checkinfo = '所属部队抗暴'}
Warriors[21] = {ID = 21, name = '铁剑', info = '每级增加0.2%武将攻击力。', massage = '每级+0.2%', icon = 21, littleicon = 1, quality = 2, isRarity = 0, partId = 1, upproperty = 12, suitId = 0, eatedExp = 0, sellPrice = 200, sound = 2, checkinfo = '所属部队攻击力'}
Warriors[22] = {ID = 22, name = '皮甲', info = '每级增加0.2%武将血量上限。', massage = '每级+0.2%', icon = 22, littleicon = 5, quality = 2, isRarity = 0, partId = 2, upproperty = 11, suitId = 0, eatedExp = 0, sellPrice = 200, sound = 2, checkinfo = '所属部队生命上限'}
Warriors[23] = {ID = 23, name = '皮护手', info = '每级增加0.2%武将命中。', massage = '每级+0.2%', icon = 23, littleicon = 4, quality = 2, isRarity = 0, partId = 3, upproperty = 4, suitId = 0, eatedExp = 0, sellPrice = 200, sound = 2, checkinfo = '所属部队命中'}
Warriors[24] = {ID = 24, name = '皮靴', info = '每级增加0.2%武将闪避。', massage = '每级+0.2%', icon = 24, littleicon = 6, quality = 2, isRarity = 0, partId = 4, upproperty = 5, suitId = 0, eatedExp = 0, sellPrice = 200, sound = 2, checkinfo = '所属部队闪避'}
Warriors[25] = {ID = 25, name = '匕首', info = '每级增加0.2%武将暴击。', massage = '每级+0.2%', icon = 25, littleicon = 2, quality = 2, isRarity = 0, partId = 5, upproperty = 6, suitId = 0, eatedExp = 0, sellPrice = 200, sound = 2, checkinfo = '所属部队暴击'}
Warriors[26] = {ID = 26, name = '皮盔', info = '每级增加0.2%武将抗暴。', massage = '每级+0.2%', icon = 26, littleicon = 3, quality = 2, isRarity = 0, partId = 6, upproperty = 7, suitId = 0, eatedExp = 0, sellPrice = 200, sound = 2, checkinfo = '所属部队抗暴'}
Warriors[31] = {ID = 31, name = '铁剑', info = '每级增加0.5%武将攻击力。', massage = '每级+0.5%', icon = 31, littleicon = 1, quality = 3, isRarity = 0, partId = 1, upproperty = 12, suitId = 1, eatedExp = 0, sellPrice = 400, sound = 1, checkinfo = '所属部队攻击力'}
Warriors[32] = {ID = 32, name = '皮甲', info = '每级增加0.5%武将血量上限。', massage = '每级+0.5%', icon = 32, littleicon = 5, quality = 3, isRarity = 0, partId = 2, upproperty = 11, suitId = 1, eatedExp = 0, sellPrice = 400, sound = 1, checkinfo = '所属部队生命上限'}
Warriors[33] = {ID = 33, name = '皮护手', info = '每级增加0.5%武将命中。', massage = '每级+0.5%', icon = 33, littleicon = 4, quality = 3, isRarity = 0, partId = 3, upproperty = 4, suitId = 1, eatedExp = 0, sellPrice = 400, sound = 1, checkinfo = '所属部队命中'}
Warriors[34] = {ID = 34, name = '皮靴', info = '每级增加0.5%武将闪避。', massage = '每级+0.5%', icon = 34, littleicon = 6, quality = 3, isRarity = 0, partId = 4, upproperty = 5, suitId = 1, eatedExp = 0, sellPrice = 400, sound = 1, checkinfo = '所属部队闪避'}
Warriors[35] = {ID = 35, name = '匕首', info = '每级增加0.5%武将暴击。', massage = '每级+0.5%', icon = 35, littleicon = 2, quality = 3, isRarity = 0, partId = 5, upproperty = 6, suitId = 1, eatedExp = 0, sellPrice = 400, sound = 1, checkinfo = '所属部队暴击'}
Warriors[36] = {ID = 36, name = '皮盔', info = '每级增加0.5%武将抗暴。', massage = '每级+0.5%', icon = 36, littleicon = 3, quality = 3, isRarity = 0, partId = 6, upproperty = 7, suitId = 1, eatedExp = 0, sellPrice = 400, sound = 1, checkinfo = '所属部队抗暴'}
Warriors[41] = {ID = 41, name = '龙鳞枪', info = '每级增加1%武将攻击力。', massage = '每级+1%', icon = 41, littleicon = 1, quality = 4, isRarity = 1, partId = 1, upproperty = 12, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队攻击力'}
Warriors[42] = {ID = 42, name = '龙鳞铠', info = '每级增加1%武将血量上限。', massage = '每级+1%', icon = 42, littleicon = 5, quality = 4, isRarity = 1, partId = 2, upproperty = 11, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队生命上限'}
Warriors[43] = {ID = 43, name = '龙鳞护手', info = '每级增加1%武将命中。', massage = '每级+1%', icon = 43, littleicon = 4, quality = 4, isRarity = 1, partId = 3, upproperty = 4, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队命中'}
Warriors[44] = {ID = 44, name = '龙鳞靴', info = '每级增加1%武将闪避。', massage = '每级+1%', icon = 44, littleicon = 6, quality = 4, isRarity = 1, partId = 4, upproperty = 5, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队闪避'}
Warriors[45] = {ID = 45, name = '龙牙匕首', info = '每级增加1%武将暴击。', massage = '每级+1%', icon = 45, littleicon = 2, quality = 4, isRarity = 1, partId = 5, upproperty = 6, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队暴击'}
Warriors[46] = {ID = 46, name = '龙鳞盔', info = '每级增加1%武将抗暴。', massage = '每级+1%', icon = 46, littleicon = 3, quality = 4, isRarity = 1, partId = 6, upproperty = 7, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队抗暴'}
Warriors[51] = {ID = 51, name = '麒麟刀', info = '每级增加1%武将攻击力。', massage = '每级+1%', icon = 51, littleicon = 1, quality = 4, isRarity = 1, partId = 1, upproperty = 12, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队攻击力'}
Warriors[52] = {ID = 52, name = '麒麟铠', info = '每级增加1%武将血量上限。', massage = '每级+1%', icon = 52, littleicon = 5, quality = 4, isRarity = 1, partId = 2, upproperty = 11, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队生命上限'}
Warriors[53] = {ID = 53, name = '麒麟护手', info = '每级增加1%武将命中。', massage = '每级+1%', icon = 53, littleicon = 4, quality = 4, isRarity = 1, partId = 3, upproperty = 4, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队命中'}
Warriors[54] = {ID = 54, name = '麒麟靴', info = '每级增加1%武将闪避。', massage = '每级+1%', icon = 54, littleicon = 6, quality = 4, isRarity = 1, partId = 4, upproperty = 5, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队闪避'}
Warriors[55] = {ID = 55, name = '麒麟护臂', info = '每级增加1%武将暴击。', massage = '每级+1%', icon = 55, littleicon = 2, quality = 4, isRarity = 1, partId = 5, upproperty = 6, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队暴击'}
Warriors[56] = {ID = 56, name = '麒麟盔', info = '每级增加1%武将抗暴。', massage = '每级+1%', icon = 56, littleicon = 3, quality = 4, isRarity = 1, partId = 6, upproperty = 7, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队抗暴'}
Warriors[61] = {ID = 61, name = '凤羽弓', info = '每级增加1%武将攻击力。', massage = '每级+1%', icon = 61, littleicon = 1, quality = 4, isRarity = 1, partId = 1, upproperty = 12, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队攻击力'}
Warriors[62] = {ID = 62, name = '凤翅甲', info = '每级增加1%武将血量上限。', massage = '每级+1%', icon = 62, littleicon = 5, quality = 4, isRarity = 1, partId = 2, upproperty = 11, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队生命上限'}
Warriors[63] = {ID = 63, name = '凤翎护手', info = '每级增加1%武将命中。', massage = '每级+1%', icon = 63, littleicon = 4, quality = 4, isRarity = 1, partId = 3, upproperty = 4, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队命中'}
Warriors[64] = {ID = 64, name = '凤尾靴', info = '每级增加1%武将闪避。', massage = '每级+1%', icon = 64, littleicon = 6, quality = 4, isRarity = 1, partId = 4, upproperty = 5, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队闪避'}
Warriors[65] = {ID = 65, name = '凤焰箭矢', info = '每级增加1%武将暴击。', massage = '每级+1%', icon = 65, littleicon = 2, quality = 4, isRarity = 1, partId = 5, upproperty = 6, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队暴击'}
Warriors[66] = {ID = 66, name = '凤冠盔', info = '每级增加1%武将抗暴。', massage = '每级+1%', icon = 66, littleicon = 3, quality = 4, isRarity = 1, partId = 6, upproperty = 7, suitId = 2, eatedExp = 0, sellPrice = 1000, sound = 1, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles', checkinfo = '所属部队抗暴'}
Warriors[71] = {ID = 71, name = '神龙鳞枪', info = '每级增加1%武将攻击力。', massage = '每级+1%', icon = 71, littleicon = 1, quality = 5, isRarity = 1, partId = 1, upproperty = 12, suitId = 3, eatedExp = 0, sellPrice = 2000, sound = 1, effectframe = 'Item_orange', effectbigframe = 'rpg-Yellow-particles', checkinfo = '所属部队攻击力'}
Warriors[72] = {ID = 72, name = '神龙鳞铠', info = '每级增加1%武将血量上限。', massage = '每级+1%', icon = 72, littleicon = 5, quality = 5, isRarity = 1, partId = 2, upproperty = 11, suitId = 3, eatedExp = 0, sellPrice = 2000, sound = 1, effectframe = 'Item_orange', effectbigframe = 'rpg-Yellow-particles', checkinfo = '所属部队生命上限'}
Warriors[73] = {ID = 73, name = '神龙鳞护手', info = '每级增加1%武将命中。', massage = '每级+1%', icon = 73, littleicon = 4, quality = 5, isRarity = 1, partId = 3, upproperty = 4, suitId = 3, eatedExp = 0, sellPrice = 2000, sound = 1, effectframe = 'Item_orange', effectbigframe = 'rpg-Yellow-particles', checkinfo = '所属部队命中'}
Warriors[74] = {ID = 74, name = '神龙鳞靴', info = '每级增加1%武将闪避。', massage = '每级+1%', icon = 74, littleicon = 6, quality = 5, isRarity = 1, partId = 4, upproperty = 5, suitId = 3, eatedExp = 0, sellPrice = 2000, sound = 1, effectframe = 'Item_orange', effectbigframe = 'rpg-Yellow-particles', checkinfo = '所属部队闪避'}
Warriors[75] = {ID = 75, name = '神龙牙匕首', info = '每级增加1%武将暴击。', massage = '每级+1%', icon = 75, littleicon = 2, quality = 5, isRarity = 1, partId = 5, upproperty = 6, suitId = 3, eatedExp = 0, sellPrice = 2000, sound = 2, effectframe = 'Item_orange', effectbigframe = 'rpg-Yellow-particles', checkinfo = '所属部队暴击'}
Warriors[76] = {ID = 76, name = '神龙鳞盔', info = '每级增加1%武将抗暴。', massage = '每级+1%', icon = 76, littleicon = 3, quality = 5, isRarity = 1, partId = 6, upproperty = 7, suitId = 3, eatedExp = 0, sellPrice = 2000, sound = 1, effectframe = 'Item_orange', effectbigframe = 'rpg-Yellow-particles', checkinfo = '所属部队抗暴'}
Warriors[101] = {ID = 101, name = '装备经验[50]', info = '装备升级材料:提供50经验值。', massage = '经验+50', icon = 101, littleicon = 0, quality = 1, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 50, sellPrice = 100, sound = 0}
Warriors[102] = {ID = 102, name = '装备经验[100]', info = '装备升级材料:提供100经验值。', massage = '经验+100', icon = 101, littleicon = 0, quality = 2, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 100, sellPrice = 100, sound = 0}
Warriors[103] = {ID = 103, name = '装备经验[200]', info = '装备升级材料:提供200经验值。', massage = '经验+200', icon = 102, littleicon = 0, quality = 2, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 200, sellPrice = 100, sound = 0}
Warriors[104] = {ID = 104, name = '装备经验[500]', info = '装备升级材料:提供500经验值。', massage = '经验+500', icon = 102, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 500, sellPrice = 100, sound = 0}
Warriors[105] = {ID = 105, name = '装备经验[1K]', info = '装备升级材料:提供1000经验值。', massage = '经验+1000', icon = 103, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1000, sellPrice = 100, sound = 0}
Warriors[106] = {ID = 106, name = '装备经验[2K]', info = '装备升级材料:提供2000经验值。', massage = '经验+2000', icon = 104, littleicon = 0, quality = 4, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 2000, sellPrice = 100, sound = 0, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles'}
Warriors[107] = {ID = 107, name = '装备经验[5K]', info = '装备升级材料:提供5000经验值。', massage = '经验+5000', icon = 104, littleicon = 0, quality = 4, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 5000, sellPrice = 100, sound = 0, effectframe = 'Item_purple', effectbigframe = 'rpg-purple-particles'}
Warriors[108] = {ID = 108, name = '装备经验[10K]', info = '装备升级材料:提供10000经验值。', massage = '经验+10000', icon = 105, littleicon = 0, quality = 5, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 10000, sellPrice = 100, sound = 0, effectframe = 'Item_orange', effectbigframe = 'rpg-Yellow-particles'}
Warriors[109] = {ID = 109, name = '装备经验[800]', info = '装备升级材料:提供800经验值。', massage = '经验+800', icon = 103, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 800, sellPrice = 100, sound = 0}
Warriors[110] = {ID = 110, name = '装备经验[1K2]', info = '装备升级材料:提供1200经验值。', massage = '经验+1200', icon = 103, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1200, sellPrice = 100, sound = 0}
Warriors[501] = {ID = 501, name = '白色装备', info = '有几率获得任意一件白色装备。', massage = '有几率获得任意一件白色装备。', icon = 111, littleicon = 0, quality = 1, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[502] = {ID = 502, name = '绿色装备', info = '有几率获得任意一件绿色装备。', massage = '有几率获得任意一件绿色装备。', icon = 112, littleicon = 0, quality = 2, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[503] = {ID = 503, name = '蓝色装备', info = '有几率获得任意一件蓝色装备。', massage = '有几率获得任意一件蓝色装备。', icon = 113, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[504] = {ID = 504, name = '紫色装备', info = '有几率获得任意一件紫色装备。', massage = '有几率获得任意一件紫色装备。', icon = 114, littleicon = 0, quality = 4, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[505] = {ID = 505, name = '蓝色装备', info = '有机会获得蓝·攻击强化、蓝·血量强化。', massage = '有机会获得蓝·攻击强化、蓝·生命强化。', icon = 115, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[506] = {ID = 506, name = '蓝色装备', info = '有机会获得蓝·命中强化、蓝·闪避强化。', massage = '有机会获得蓝·命中强化、蓝·闪避强化。', icon = 116, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[507] = {ID = 507, name = '蓝色装备', info = '有机会获得蓝·暴击强化、蓝·抗暴强化。', massage = '有机会获得蓝·暴击强化、蓝·抗暴强化。', icon = 117, littleicon = 0, quality = 3, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[508] = {ID = 508, name = '紫色装备', info = '有机会获得紫·攻击强化、紫·血量强化。', massage = '有机会获得紫·攻击强化、紫·生命强化。', icon = 118, littleicon = 0, quality = 4, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[509] = {ID = 509, name = '紫色装备', info = '有机会获得紫·命中强化、紫·闪避强化。', massage = '有机会获得紫·命中强化、紫·闪避强化。', icon = 119, littleicon = 0, quality = 4, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
Warriors[510] = {ID = 510, name = '紫色装备', info = '有机会获得紫·暴击强化、紫·抗暴强化。', massage = '有机会获得紫·暴击强化、紫·抗暴强化。', icon = 120, littleicon = 0, quality = 4, isRarity = 0, partId = 0, upproperty = 0, suitId = 0, eatedExp = 1, sellPrice = 1, sound = 0}
return Warriors