require("component.BasicComponent")
require("component.UILinearLayout")
require("component.UILoading")
require("component.UIMessageBox")
require("component.UISkin")
require("component.UISysMessage")
require("component.UIPanelBg")
require("component.UIPanelBgNew")
require("component.UIIcon")
require("component.UITabControl")
require("component.UITabControlOld")
require("component.UITabForTanChuang")
require("component.ComponentUtils")
require("component.UIMapNodeExtend")
require("component.UIBaseMap")
require("component.SpineModel")
require("component.SpineEffect")
require("component.IDrag")
require("component.UIExpandListView")
require("component.UIMoveBtn")
require("component.UIBuilding")
require("component.UIAcceleration")
require("component.UIGoodsPanel")
require("component.UISoldierInfo")
require("component.UISetTeamPanel")
require("component.UIRetPacket")
require("component.UIRetPacketNew")
require("component.UIRankPanel")
require("component.UITabRankPanel")
require("component.UIHeroPanel")
require("component.UIHeroCard")
require("component.UIExpandScrollView")
require("component.UIAnimation")
require("component.UIParticle")
require("component.UIResourceBuy")
require("component.UIWatchPlayerInfo")
require("component.UIWatchOrdnance")
require("component.UIWatchOrdnancePiece")
require("component.UIResolvePreview")
-- require("component.UIWorldBuilding")
require("component.UIWorldFloorSafe")
require("component.UIWorldNodeBase")
require("component.UIWorldNodeBanditDungeon")
require("component.UIWorldNodeBuilding")
require("component.UIWorldNodeEmpty")
require("component.UIWorldNodeRebels")
require("component.UIWorldNodeResource")
require("component.UIWorldNodeCity")
require("component.UIWorldCityWar")
require("component.UITip")
require("component.UIBuildingTip")
require("component.UIExpandPageView")
require("component.UIHeadImg")
require("component.UIRadioGroup")
require("component.UICheckBox")
require("component.UINumKeyBoard")
require("component.UITeamInfo")
require("component.UIGuideReward")
require("component.UIFightNum")
require("component.UIGetProp")
require("component.UIHeroInfoPanel")
require("component.UIBuyEnergy")
require("component.UIAdviserInfo")
require("component.UIAdviserList")
require("component.UIPayPanel")
require("component.UITreasureSelect")


require("component.UITileWidget")
require("component.UISecLvPanelBg")
require("component.UISharePanel")

require("component.UIMovieClip")
require("component.UIDottedLine")
require("component.UIDottedLineActor")
require("component.UIMarchLine")
require("component.UIActionQueue")
--require("component.UISoldierPosition")
require("component.UIRecharge")
require("component.UIDownloading")

require("component.UIPreDownloading")

require("component.SceneMap")
require("component.UIOtherIcon")
require("component.UISkillIcon")

require("component.UIExpandTableView")
require("component.UIStandardBg")

require("component.UICCBLayer")

require("component.UITeamMiPanel")
require("component.UITeamMessPanel")
require("component.UIBattleActivityPanel")
require("component.UIFightInfosPanel")
require("component.UITeamDetailPanel")
require("component.UITeamSleepPanel")
require("component.UISoldilerMainPos")
require("component.UIRewardWithAct")
require("component.UIGuideRewardWithAct")
require("component.UIMoveNode")

require("component.UICommand")
require("component.UICityInfoPanel")
require("component.UIChatScrollviewExpand")

require("component.UIWarBookFight")
require("component.UILordCityInfo")
require("component.UILordCityVote")
require("component.UILordCityReward")
require("component.UIShowFightBuff")
require("component.UIWatchWorldPlayerInfo")
require("component.UIRankToRewardPanel")
require("component.UIShowEarnPanel")
require("component.UIWorldNodeEmperorCity")


require("component.UIRewardTips")
require("component.UIShowReward")
require("component.UIFightDialogPanel")

require("component.UIChatBarrage")                                                                    --//null 聊天弹幕公用组件
require("component.UIBuySaleCommand") 

require("component.UIChooseLegionMember")   
require("component.UIFindPlayerPanel")   
require("component.UICountrySkillPanel")   