local data = {
['ccb/shijiebing/shijie_youshang.png'] = true,
['ccb/gb-jian.png'] = true,
['ccb/wfsm-jiantou.png'] = true,
['ccb/gb-attack.png'] = true,
['ccb/wfsm-zi.png'] = true,
['ccb/gb-run.png'] = true,
['ccb/glow_guang.png'] = true,
['ccb/wfsm-tie.png'] = true,
['ccb/wfsm-mu.png'] = true,
['ccb/huo2.png'] = true,
['ccb/yan.png'] = true,
['ccb/zs-attack.png'] = true,
['ccb/qb2-run.png'] = true,
['ccb/xian.png'] = true,
['ccb/shijiebing/shijie_youxia.png'] = true,
['ccb/Efa_star03.png'] = true,
['ccb/quanglow_fangshe.png'] = true,
['ccb/wfsm-shitou.png'] = true,
['ccb/qb2-attack.png'] = true,
['ccb/zs-run.png'] = true,
['ccb/lizi_y.png'] = true,
}
return data